### ISSUE TITLE
Not downloading more than 100 files content in a directory

### ISSUE THREAD

**Issue by gandhimaulik** [liximomo/vscode-sftp#100]
## Expected Behavior
Download All files in the directory via download/sync to local command

## Actual Behavior
It creates all the files, but only first 100 files have content and rest all files are blank everytime. It throws Below error on rest of all files. we can still open blank file and click download it fetches that file.

```
[debug]: 
------
target: /path1/file2.txt
context: transmission file
error: Error: Failure
	at SFTPStream._transform (C:\Users\*\.vscode\extensions\liximomo.sftp-1.0.3\node_modules\ssh2-streams\lib\sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\*\.vscode\extensions\liximomo.sftp-1.0.3\node_modules\ssh2-streams\lib\sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
```

  

## Steps to Reproduce the Problem

  1. sftp connection with interactiveAuth
  2. download/sync to local directory with more than 100 files

I am not sure if it has anything to do with server configuration or not.
If sftp has some configuration that at max 100 or some configurable download are allowed, how to configure extension to do so.

I do not have permission to change any setting in ftp server. It has strict checks like interactiveAuth only etc.

### Extension Logs
```
[debug]: task: download c:\Users\*\Desktop\*\Dir1
[debug]: transmission file /path1/file1.txt at Tue Feb 06 2018 13:51:13 GMT+0530 (India Standard Time)
[debug]: transmission file /path1/file2.txt at Tue Feb 06 2018 13:51:13 GMT+0530 (India Standard Time)

 ---- 98 more such successful transmission  and below error for rest of all files ---

------
[debug]: 
------
target: /path1/file101.txt
context: transmission file
error: Error: Failure
	at SFTPStream._transform (C:\Users\*\.vscode\extensions\liximomo.sftp-1.0.3\node_modules\ssh2-streams\lib\sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\*\.vscode\extensions\liximomo.sftp-1.0.3\node_modules\ssh2-streams\lib\sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
```

## Specifications

  - Extension Version: 1.0.3 - 2018-02-05
  - Platform: Windows 10 , VSCODE 1.19.3

**Comment by liximomo** [comment]
I'm going to need some more information:
* OpenSSH sftp server debug output with -l DEBUG3

**Comment by gandhimaulik** [comment]
Sorry i don't have access to server log files. 

is there any configuration like  max concurrent connection or something ? 
Do you know how to request file one after another if i don't care about performance? 
i am trying to understand code but never worked on ts and promises so could not update it.
if you know let me know, i can test and report back.

Real problem here is once you do sync to local, it gets content of only 100 files by any chance you had noticed and updated any file, tried to sync to remote it will upload rest all files empty making all other files in server getting empty. and could result in data loss if you have missed status of error for few seconds.

i suggestion, to prevent this, if you get error while file transfer it should delete that file in local copy so it does not cause data loss on sync to remote

**Comment by liximomo** [comment]
Please try [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge). Set `concurrency: 99` in config file see if it can solve your problem.

**Comment by gandhimaulik** [comment]
Works Like a Charm. I set it at 20 to be on safe side.
Add this to feature list 👍 

Thanks a lot @liximomo 

Issue #61 may be the same.
You can ask them to confirm.

**Comment by liximomo** [comment]
V1.0.4 has been published.
