### ISSUE TITLE
Why can't I sync files?

### ISSUE THREAD

**Issue by gray311** [liximomo/vscode-sftp#1002]
This error occurs every time when I click   **sync local -> remote**

`[07-10 15:23:31] [error] Error: please select one of the assets
    at 101 (c:\Users\gray\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\SFTP.js:2618:19)
    at SFTP.push (c:\Users\gray\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\SFTP.js:278:11)
    at CHANNEL_DATA (c:\Users\gray\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\client.js:525:23)
    at 94 (c:\Users\gray\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\handlers.misc.js:859:16)
    at Protocol.onPayload (c:\Users\gray\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)
    at AESGCMDecipherNative.decrypt (c:\Users\gray\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\crypto.js:987:26)
    at Protocol.parsePacket [as _parse] (c:\Users\gray\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
    at Protocol.parse (c:\Users\gray\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\Protocol.js:293:16)
    at Socket.<anonymous> (c:\Users\gray\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\client.js:713:21)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) `

**Comment by WMQing** [comment]
I guess some file paths are symbol link， you can try add it to "ignore" list...
