### ISSUE TITLE
TypeError: Cannot set property closed of #<Writable> which has only a getter

### ISSUE THREAD

**Issue by zptr1** [liximomo/vscode-sftp#1019]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Uploading any file results in the following error:
```
TypeError: Cannot set property closed of #<Writable> which has only a getter
	at new WriteStream (/home/.../.vscode-oss/extensions/liximomo.sftp-1.12.10/node_modules/ssh2/lib/protocol/SFTP.js:3585:15)
	at SFTP.createWriteStream (/home/.../.vscode-oss/extensions/liximomo.sftp-1.12.10/node_modules/ssh2/lib/protocol/SFTP.js:311:12)
	at /home/.../.vscode-oss/extensions/liximomo.sftp-1.12.10/dist/extension.js:70:131256
	at new Promise (<anonymous>)
	at a._put (/home/.../.vscode-oss/extensions/liximomo.sftp-1.12.10/dist/extension.js:70:131218)
	at a.<anonymous> (/home/.../.vscode-oss/extensions/liximomo.sftp-1.12.10/dist/extension.js:70:129943)
	at Generator.next (<anonymous>)
	at s (/home/.../.vscode-oss/extensions/liximomo.sftp-1.12.10/dist/extension.js:70:128197)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) when local ➞ remote /home/.../.../index.js
```
It also erases the file on the remote server.

**To Reproduce**
1. Upload any file
2. Error!

**Expected behavior**
A file gets properly uploaded to the remote server.

**Desktop:**
 - OS: Void Linux
 - VSCode Version: Code OSS 1.80.1
 - Extension Version: 1.12.10

**Extension Logs from Startup**
[log.txt](https://github.com/liximomo/vscode-sftp/files/12209980/log.txt)

**Comment by zptr1** [comment]
nevermind, i thought i've installed the fork ...

**Comment by jianfengye** [comment]
what it means installed the fork ?

**Comment by jianfengye** [comment]
i get the same issue
