### ISSUE TITLE
file not exist

### ISSUE THREAD

**Issue by miyaohua** [liximomo/vscode-sftp#1020]
[08-14 20:50:06] [error] Error: file not exist
    at f.<anonymous> (/Users/m/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:263172)
    at Generator.next (<anonymous>)
    at s (/Users/m/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:261862)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 

{
    "name": "My Server",
    "host": "211.101.235.189",
    "protocol": "ftp",
    "port": 21,
    "username": "test",
    "password": "kj56jYXMt568Ns3y",
    "remotePath": "/www/wwwroot/www.vpskee.cn",
    "connectTimeout": 100000,
    "uploadOnSave": true,
    "useTempFile": false,
    "openSsh": false
}

**Comment by sohow** [comment]
same
