### ISSUE TITLE
Error: Config Not Found and No such file

### ISSUE THREAD

**Issue by ValbadExe** [liximomo/vscode-sftp#1022]
**Do you read the FAQ?**
- [X] Yes.

**Describe the bug**
When saving changes and attempting to upload them to the FTP, the following error occurs: Configuration not found.

The issue may be similar to this link: https://github.com/liximomo/vscode-sftp/issues/394

Initially, the debugging package 1.7.5 had worked for me, and everything was functioning perfectly. However, after installing Node on my computer, it stopped working. It even seems that the console mentions something related to the error.

It should be clarified that these same files can be modified by my colleagues, and they also have Node installed on their computers, but from different text editors, such as Sublime, for example. Therefore, these files are not protected against editing.

**To Reproduce**
1. Install VS Code on Windows 10.
2. Install SFTP.
3. Open the workspace and create a configuration file in the .vscode folder.
4. Reload VS Code.
5. Try to load something by right-clicking and choosing to upload.

**Expected behavior**
It should upload the file correctly.

**Screenshots**
sftp.json:
![image](https://github.com/liximomo/vscode-sftp/assets/76501398/818ffb03-2ebf-4c39-8cef-4fe4d5b63c19)

Config Not Found:
![image](https://github.com/liximomo/vscode-sftp/assets/76501398/de2e81af-d55b-4758-b9bd-23a3f5ff52f2)

No such file:
![image](https://github.com/liximomo/vscode-sftp/assets/76501398/79f93f65-36e1-4e4a-bba1-5856a884bede)

**Desktop:**
 - OS: Windows 10
 - VSCode Version 1.84.0
 - Extension Version 1.12.10

**Extension Logs from Startup** - *required*

```
[11-03 10:42:10] [info] [file-open] z:\DESARROLLOWEB\FE_FASE2\.vscode\sftp.json
[11-03 10:42:16] [debug] Outbound: Sending DISCONNECT (11)
[11-03 10:42:16] [debug] Socket ended
[11-03 10:42:16] [debug] Socket closed
[11-03 10:42:16] [info] config at z:\DESARROLLOWEB\FE_FASE2 {"remotePath":"/delta/ambiente_web/w_fe/FE_FASE2_DEV/","uploadOnSave":true,"downloadOnOpen":true,"ignore":[".vscode",".git",".DS_Store","sftp-config.json"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"Factura Electronica 0.100","host":"192.168.0.100","port":222,"username":"******","password":"******"}
[11-03 10:42:23] [info] [file-save] z:\DESARROLLOWEB\FE_FASE2\PruebaAndres\pruebaAndres.php
[11-03 10:42:23] [trace] handle upload file for z:\DESARROLLOWEB\FE_FASE2\PruebaAndres\pruebaAndres.php
[11-03 10:42:23] [debug] Custom crypto binding not available
[11-03 10:42:23] [debug] Local ident: 'SSH-2.0-ssh2js1.5.0'
[11-03 10:42:23] [debug] Client: Trying 192.168.0.100 on port 222 ...
[11-03 10:42:23] [debug] Socket connected
[11-03 10:42:23] [debug] Remote ident: 'SSH-2.0-OpenSSH_7.4'
[11-03 10:42:23] [debug] Outbound: Sending KEXINIT
[11-03 10:42:23] [debug] Inbound: Handshake in progress
[11-03 10:42:23] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[11-03 10:42:23] [debug] Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[11-03 10:42:23] [debug] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[11-03 10:42:23] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[11-03 10:42:23] [debug] Handshake: (remote) Host key format: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[11-03 10:42:23] [debug] Handshake: Host key format: ssh-ed25519
[11-03 10:42:23] [debug] Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[11-03 10:42:23] [debug] Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
[11-03 10:42:23] [debug] Handshake: C->S Cipher: aes128-gcm@openssh.com
[11-03 10:42:23] [debug] Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[11-03 10:42:23] [debug] Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
[11-03 10:42:23] [debug] Handshake: S->C cipher: aes128-gcm@openssh.com
[11-03 10:42:23] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[11-03 10:42:23] [debug] Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[11-03 10:42:23] [debug] Handshake: C->S MAC: <implicit>
[11-03 10:42:23] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[11-03 10:42:23] [debug] Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[11-03 10:42:23] [debug] Handshake: S->C MAC: <implicit>
[11-03 10:42:23] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[11-03 10:42:23] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[11-03 10:42:23] [debug] Handshake: C->S compression: none
[11-03 10:42:23] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[11-03 10:42:23] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[11-03 10:42:23] [debug] Handshake: S->C compression: none
[11-03 10:42:23] [debug] Outbound: Sending KEXECDH_INIT
[11-03 10:42:23] [debug] Received DH Reply
[11-03 10:42:23] [debug] Host accepted by default (no verification)
[11-03 10:42:23] [debug] Host accepted (verified)
[11-03 10:42:23] [debug] Outbound: Sending NEWKEYS
[11-03 10:42:23] [debug] Inbound: NEWKEYS
[11-03 10:42:23] [debug] Verifying signature ...
[11-03 10:42:23] [debug] Verified signature
[11-03 10:42:23] [debug] Handshake completed
[11-03 10:42:23] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[11-03 10:42:23] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[11-03 10:42:23] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[11-03 10:42:23] [debug] Inbound: Received USERAUTH_FAILURE (publickey,gssapi-keyex,gssapi-with-mic,password)
[11-03 10:42:23] [debug] Client: none auth failed
[11-03 10:42:23] [debug] Outbound: Sending USERAUTH_REQUEST (password)
[11-03 10:42:23] [debug] Inbound: Received USERAUTH_SUCCESS
[11-03 10:42:23] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[11-03 10:42:23] [debug] Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
[11-03 10:42:23] [debug] Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
[11-03 10:42:23] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[11-03 10:42:23] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[11-03 10:42:23] [debug] Inbound: REQUEST_SUCCESS
[11-03 10:42:23] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
[11-03 10:42:23] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[11-03 10:42:23] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[11-03 10:42:23] [debug] Inbound: CHANNEL_DATA (r:0, 154)
[11-03 10:42:23] [debug] SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com,fsync@openssh.com)
[11-03 10:42:23] [debug] Outbound: Sending CHANNEL_DATA (r:0, 67)
[11-03 10:42:23] [debug] SFTP: Outbound: Buffered MKDIR
[11-03 10:42:23] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[11-03 10:42:23] [debug] SFTP: Inbound: Received STATUS (id:0, 4, "Failure")
[11-03 10:42:23] [debug] Outbound: Sending CHANNEL_DATA (r:0, 63)
[11-03 10:42:23] [debug] SFTP: Outbound: Buffered LSTAT
[11-03 10:42:23] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[11-03 10:42:23] [debug] SFTP: Inbound: Received ATTRS (id:1)
[11-03 10:42:23] [debug] Outbound: Sending CHANNEL_DATA (r:0, 88)
[11-03 10:42:23] [debug] SFTP: Outbound: Buffered OPEN
[11-03 10:42:23] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[11-03 10:42:23] [debug] SFTP: Inbound: Received HANDLE (id:2)
[11-03 10:42:23] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[11-03 10:42:23] [debug] SFTP: Outbound: Buffered FSTAT
[11-03 10:42:23] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[11-03 10:42:23] [debug] SFTP: Inbound: Received ATTRS (id:3)
[11-03 10:42:23] [debug] Outbound: Sending CHANNEL_DATA (r:0, 25)
[11-03 10:42:23] [debug] SFTP: Outbound: Buffered FSETSTAT
[11-03 10:42:23] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[11-03 10:42:23] [debug] SFTP: Inbound: Received STATUS (id:4, 0, "Success")
[11-03 10:42:23] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[11-03 10:42:23] [debug] SFTP: Outbound: Buffered CLOSE
[11-03 10:42:23] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[11-03 10:42:23] [debug] SFTP: Inbound: Received STATUS (id:5, 0, "Success")
[11-03 10:42:23] [error] TypeError: Cannot set property closed of #<Writable> which has only a getter
    at new WriteStream (c:\Users\german.lopez\.vscode\extensions\liximomo.sftp-1.12.10\node_modules\ssh2\lib\protocol\SFTP.js:3585:15)
    at SFTP.createWriteStream (c:\Users\german.lopez\.vscode\extensions\liximomo.sftp-1.12.10\node_modules\ssh2\lib\protocol\SFTP.js:311:12)
    at c:\Users\german.lopez\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:70:131256
    at new Promise (<anonymous>)
    at a._put (c:\Users\german.lopez\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:70:131218)
    at a.<anonymous> (c:\Users\german.lopez\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:70:129943)
    at Generator.next (<anonymous>)
    at s (c:\Users\german.lopez\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:70:128197)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) when local ➞ remote z:\DESARROLLOWEB\FE_FASE2\PruebaAndres\pruebaAndres.php
```

**Comment by ValbadExe** [comment]
F for me.
