### ISSUE TITLE
Files not getting synced correctly

### ISSUE THREAD

**Issue by thetheodoros** [liximomo/vscode-sftp#113]
## Expected Behavior
Files get synced from local to remote

## Actual Behavior
Some files and folders get synced initially but get deleted again.

## Steps to Reproduce the Problem

  1. Config:
```
{
    "host": "my.srv.com",
    "port": 21,
    "context": "./app/src/html",
    "username": "user",
    "password": "secretpw",
    "protocol": "ftp",
    "passive": false,
    "remotePath": "httpdocs/devs/folder",
    "uploadOnSave": true,
    "syncMode": "full",
    "watcher": {
        "files": "**/**",
        "autoUpload": true,
        "autoDelete": true
    },
    "ignore": [
        "docs/**",
        ".vscode/**",
        ".git/**",
        ".DS_Store",
        "vendor/**"
    ]
}
```
  2. Press F1 and select "SFTP Sync To Remote"
  3. Wait for sync to finish

## Requisites (**important to diagnose the problem!**)
My repository worktree:
![image](https://user-images.githubusercontent.com/34158395/36272074-c1da69a0-1280-11e8-9d35-fc4acae5c8e7.png)

  ### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
Lots of these errors
```
[debug]: try to get httpdocs/devs/folder/migrations/m170717_140650_create_all_tables.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/ApereoCas.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/web/favicon.ico mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/RoundtripOnly.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/Risks.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/Result.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/Report.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/Recommendation.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/Questionblock.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/PdfRenderer.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/Lang.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/Insurances.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/Insurancepolicy.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/components/Field.php mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/.gitignore mode fail, default to 0666
[debug]: try to get httpdocs/devs/folder/README.md mode fail, default to 0666
```

and with debug disabled: 

```
[error]: change httpdocs/devs/folder/modules/neo/widgets/AnswerRowWidget.php mode to 644 Error: httpdocs/devs/folder/modules/neo/widgets/AnswerRowWidget.php: No such file or directory
	at makeError (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
[error]: change httpdocs/devs/folder/web/js/comp/admin.js mode to 644 Error: httpdocs/devs/folder/web/js/comp/admin.js: No such file or directory
	at makeError (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
[error]: change httpdocs/devs/folder/web/js/vendor/autoNumeric.min.js mode to 666 Error: httpdocs/devs/folder/web/js/vendor/autoNumeric.min.js: No such file or directory
	at makeError (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\User\.vscode\extensions\liximomo.sftp-1.0.4\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
```

## Specifications

  - Version: 1.0.4
  - Platform: Windows

**Comment by liximomo** [comment]
Try v1.0.5.

**Comment by thetheodoros** [comment]
I am using v1.0.5. now and the problem is still the same. Now I get these errors:
```
[debug]: remove dir httpdocs_work/devs/user/models at Thu Mar 08 2018 18:55:04 GMT+0100 (Mitteleuropäische Zeit)
[debug]: 
------
target: httpdocs_work/devs/user/web/js/vendor/cytoscape/cytoscape.js-klay-master
context: remove dir
error: Error: httpdocs_work/devs/user/web/js/vendor/cytoscape/cytoscape.js-klay-master/example-graphs: No such file or directory
	at makeError (C:\Users\user\.vscode\extensions\liximomo.sftp-1.0.5\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.0.5\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\user\.vscode\extensions\liximomo.sftp-1.0.5\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\user\.vscode\extensions\liximomo.sftp-1.0.5\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
------
[debug]: 
------
target: httpdocs_work/devs/user/web/js/vendor/cytoscape/cytoscape.js-klay-master
context: remove dir
error: Error: httpdocs_work/devs/user/web/js/vendor/cytoscape/cytoscape.js-klay-master/LICENSE: No such file or directory
	at makeError (C:\Users\user\.vscode\extensions\liximomo.sftp-1.0.5\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.0.5\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\user\.vscode\extensions\liximomo.sftp-1.0.5\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\user\.vscode\extensions\liximomo.sftp-1.0.5\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
```

**Comment by liximomo** [comment]
Ignore the error, is the actual result correct?

**Comment by thetheodoros** [comment]
No it is still not syncing correctly.
This is how the worktree looks after sync is with SFTP is finished.
![image](https://user-images.githubusercontent.com/34158395/37205081-9ca1f3aa-2393-11e8-8d16-620bac4f2659.png)
You can see the original worktree in the issue.

What I changed was adding "context" in my sftp settings to only sync the html folder in my worktree.
Did I configure something wrong?

**Comment by liximomo** [comment]
```
"remotePath": "httpdocs/devs/folder",
```
`remotePath` should be an absoluate path.

**Comment by thetheodoros** [comment]
I changed remotePath to "/httpdocs/devs/folder"
the issue remains unchanged. 

What can I try next?

**Comment by liximomo** [comment]
Try v1.1.3.

**Comment by thetheodoros** [comment]
@liximomo sync seems to be working for the most part except for the folder "components"
worktree:
![image](https://user-images.githubusercontent.com/34158395/37599248-9420d644-2b84-11e8-8cca-1e8b6fff2004.png)

FTP:
![image](https://user-images.githubusercontent.com/34158395/37599322-bf4c7f62-2b84-11e8-9909-1741e25286ae.png)


my conf:
```
{
    "host": "my.srv.com",
    "port": 21,
    "context": "./app/src/html",
    "username": "username",
    "password": "password",
    "protocol": "ftp",
    "passive": true,
    "remotePath": "/httpdocs_work/devs/name",
    "uploadOnSave": true,
    "syncMode": "full",
    "watcher": {
        "files": "./app/src/html/**",
        "autoUpload": true,
        "autoDelete": true
    },
    "ignore": [
        "./app/src/html/docs/**",
        "./app/src/html/runtime/*"
    ]
}
```

**Comment by liximomo** [comment]
Try to only sync the `components ` folder (right click on components in file explorer -> select `sftp: sync to remote`), then post the logs.

**Comment by thetheodoros** [comment]
This is the complete log after right click on components and "sync to remote"
```
[info] run command sync to remote {"$mid":1,"fsPath":"c:\\Users\\user\\Documents\\GIT VSC\\frontend\\app\\src\\html\\components","external":"file:///c%3A/Users/user/Documents/GIT%20VSC/frontend/app/src/html/components","path":"/c:/Users/user/Documents/GIT VSC/frontend/app/src/html/components","scheme":"file"} [{"$mid":1,"fsPath":"c:\\Users\\user\\Documents\\GIT VSC\\frontend\\app\\src\\html\\components","external":"file:///c%3A/Users/user/Documents/GIT%20VSC/frontend/app/src/html/components","path":"/c:/Users/user/Documents/GIT VSC/frontend/app/src/html/components","scheme":"file"}]
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\prio-detail.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\vergleich-header-block.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\cockpit-dropdown.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\debug.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\empfehlung-box-item.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\empfehlung-box.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\empfehlung-report-part.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\ergebnis-begruendung.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\ergebnis-box.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\ergebnis-header.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\haushaltsrechner-zeile.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\insurance-detail-subitem.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\insurance-detail.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\loop-navigation.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\pdf-report-part.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\polizzencheck-zeile.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\analyse-bar-box.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\priorisierung-bar-box.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\question-tf-element.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\recommendation-ergebnis-begruendung.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\recommendation-ergebnis-box.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\report-cc-empfehlung-box.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\report-contact-data.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\report-empfehlung-box-item.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\report-empfehlung-box.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\report-risk.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\risk-detail-subitem.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\risk-detail.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\unternehmenscheck-bar-box.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\unternehmenscheck-custom-detail.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\vergleich-block.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\views\vergleich-footer-block.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\AnalyseBarBoxWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\utility\HtmlClass.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\utility\RoundtripBuilder.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\VergleichBlockWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\UnternehmenscheckCustomDetailWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\extenders\ActiveForm.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\extenders\BasePdf.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\extenders\Controller.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\extenders\Formatter.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\extenders\RoundtripSender.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\extenders\SectionController.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\extenders\SimpleDbMessageSource.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\extenders\TimestampBehavior.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\VergleichHeaderBlockWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\VergleichFooterBlockWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\utility\ApiRequest.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\utility\DataRequest.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\utility\Div.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\utility\HeaderBuilder.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\UnternehmenscheckBarBoxWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\RiskDetailWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\extenders\BaseField.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\CockpitDropdownWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\DebugWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\EmpfehlungBoxItemWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\EmpfehlungBoxWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\EmpfehlungReportPartWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\ErgebnisBegruendungWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\ErgebnisBoxWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\ErgebnisHeaderWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\ErgebnisReportPartWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\HaushaltsrechnerZeileWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\InsuranceDetailSubitemWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\InsuranceDetailWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\LoopNavigationWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\PdfPartWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\PolizzencheckZeileWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\PrioDetailWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\PriorisierungBarBoxWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\QuestionTFElement.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\RecommendationErgebnisBegruendungWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\RecommendationErgebnisBoxWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\ReportCCEmpfehlungBoxWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\ReportContactDataWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\ReportEmpfehlungBoxItemWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\ReportEmpfehlungBoxWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\ReportRiskWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\widgets\RiskDetailSubitemWidget.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\Insurancepolicy.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\Result.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\RoundtripOnly.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\Risks.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\ApereoCas.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\CompareField.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\CoverConceptReport.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\Field.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\FieldWrapper.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\UCheckOffer.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\Insurances.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\Lang.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\OfferComparison.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\PdfRenderer.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\Questionblock.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\Recommendation.php
[info] transfer c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components\Report.php
[error] Error: /httpdocs_work/devs/user/components/widgets/AnalyseBarBoxWidget.php: No such file or directory
	at makeError (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20) remove /httpdocs_work/devs/user/components/widgets
[info] remove /httpdocs_work/devs/user/components/widgets
[error] Error: /httpdocs_work/devs/user/components/ApereoCas.php: No such file or directory
	at makeError (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20) remove /httpdocs_work/devs/user/components
[info] remove /httpdocs_work/devs/user/components
[error] Error: /httpdocs_work/devs/user/components/ApereoCas.php: No such file or directory
	at makeError (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20) remove /httpdocs_work/devs/user/components
[info] remove /httpdocs_work/devs/user/components
[error] Error: /httpdocs_work/devs/user/components/ApereoCas.php: No such file or directory
	at makeError (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20) remove /httpdocs_work/devs/user/components
[info] remove /httpdocs_work/devs/user/components
[error] Error: /httpdocs_work/devs/user/components/FieldWrapper.php: No such file or directory
	at makeError (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20) remove /httpdocs_work/devs/user
[info] remove /httpdocs_work/devs/user
[info] remove /httpdocs_work/devs/user/components/utility
[info] remove /httpdocs_work/devs/user/components/extenders
[error] Error: /httpdocs_work/devs/user/components/extenders: No such file or directory
	at makeError (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20) remove /httpdocs_work/devs/user/components
[info] remove /httpdocs_work/devs/user/components
[info] remove /httpdocs_work/devs/user/components/widgets/views
[error] Error: /httpdocs_work/devs/user/components/widgets/views: No such file or directory
	at makeError (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.3\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20) remove /httpdocs_work/devs/user/components/widgets
[info] remove /httpdocs_work/devs/user/components/widgets
[info] sync to remote c:\Users\user\Documents\GIT VSC\frontend\app\src\html\components
```

**Comment by liximomo** [comment]
I am confused. Please tell me what's the `components` folder's full path in your remote server.

**Comment by thetheodoros** [comment]
the absolute path to components folder on ftp: `/httpdocs_work/devs/user/components/`

my sftp config:
```
{
    "host": "my.srv.com",
    "port": 21,
    "context": "./app/src/html",
    "username": "user",
    "password": "password",
    "protocol": "ftp",
    "passive": true,
    "remotePath": "/httpdocs_work/devs/user",
    "uploadOnSave": true,
    "syncMode": "full",
    "watcher": {
        "files": "./app/src/html/**",
        "autoUpload": true,
        "autoDelete": true
    },
    "ignore": [
        "./app/src/html/docs/**",
        "./app/src/html/runtime/*"
    ]
}
```

**Comment by liximomo** [comment]
Try v1.1.4.

**Comment by liximomo** [comment]
@thetheodoros  I make a [debug-package](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) with verbose logs. Please try with it and send me the logs.

**Comment by thetheodoros** [comment]
@liximomo 
Seems to be working correctly now! 👍 Thank you very much!

**Comment by liximomo** [comment]
The new version is published!
