### ISSUE TITLE
File upload: remote error Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by pet3r** [liximomo/vscode-sftp#116]
## Expected Behavior
The plugin uploads a file to the remote server

## Actual Behavior
Get an error message saying:
[sftp] connect ECONNREFUSED 192.168.83.10:22

## Steps to Reproduce the Problem

  1. Open the Command Palette
  1. Type `SFTP: Upload`
  1. Select the project's folder

### Extension Logs

 ```
[info]: config at /home/pet3r/Documents/myProject {
    "protocol": "ftp",
    "host": "192.168.83.10",
    "port": 22,
    "username": "pet3r",
    "password": "pet3r",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "interactiveAuth": false,
    "secure": false,
    "secureOptions": null,
    "passive": false,
    "remotePath": "/myProject",
    "uploadOnSave": false,
    "syncMode": "update",
    "ignore": [
        ".vscode",
        ".svn"
    ],
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "concurrency": 512,
    "context": "/home/pet3r/Documents/myProject"
}


[debug]: task: upload /home/pet3r/Documents/myProject
[debug]: connect to remote
[debug]: remote error Error: connect ECONNREFUSED 192.168.83.10:22
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
[error]: context: undefined reason: Error: connect ECONNREFUSED 192.168.83.10:22
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
[debug]: connect close`
```
## Specifications

  - Version: VSCode: 1.20.1, sftp: 1.0.4
  - Platform: Ubuntu 17.10 x64

**Comment by pet3r** [comment]
I solved it.
The default port is 22.
For FTP it should be 21.

**Comment by dyaroshevich** [comment]
Thanks a lot!
