### ISSUE TITLE
Error: Malformed Packet when attempting to download a large (~242 KB) File

### ISSUE THREAD

**Issue by raytmilan** [liximomo/vscode-sftp#117]
## Expected Behavior
A successful download of the file with no errors

## Actual Behavior
`[debug]: remote error Error: Malformed packet`

`     at SSH2Stream._cleanup (/nfs/2018/m/mray/.vscode/extensions/liximomo.sftp-1.0.4/node_modules/ssh2-streams/lib/ssh.js:263:24)`

`     at readString (/nfs/2018/m/mray/.vscode/extensions/liximomo.sftp-1.0.4/node_modules/ssh2-streams/lib/utils.js:800:22)`

`     at parsePacket (~workspace-path/.vscode/extensions/liximomo.sftp-1.0.4/node_modules/ssh2-streams/lib/ssh.js:3433:12)`

`     at SSH2Stream._transform (~workspace-path/.vscode/extensions/liximomo.sftp-1.0.4/node_modules/ssh2-streams/lib/ssh.js:667:13)`

`     at SSH2Stream.Transform._read (_stream_transform.js:167:10)`

`     at SSH2Stream._read (~workspace-path/.vscode/extensions/liximomo.sftp-1.0.4/node_modules/ssh2-streams/lib/ssh.js:251:15)`

`     at SSH2Stream.Transform._write (_stream_transform.js:155:12)`

`     at doWrite (_stream_writable.js:329:12)`

`     at writeOrBuffer (_stream_writable.js:315:5)`

`     at SSH2Stream.Writable.write (_stream_writable.js:241:11)`

## Other details
I actually tried many/all other ftp/sftp clients for vscode, but this extension was the only one that did what I desired, simple file auto upload and download. This was working fine for my smaller .html and .js files, but when I got to my main js file which is 242 KB... the extension gave this **malformed packet error** upon the requested download. To clarify, the server did not have any connection issues, as I selected the file by using the sftp list command, which worked fine.

## Specifications

  - Version: VSCode 1.19.2
  - Local Platform: MacOSX
  - Remote sftp Platform: Windows (NTFS drive)

**Comment by liximomo** [comment]
The underlying problem here is that the server is sending a packet larger than the maximum channel packet size we said we were willing to accept ([32768 bytes](https://tools.ietf.org/html/rfc4253#section-6.1)). So there should be a bug in your ssh server.

**Comment by raytmilan** [comment]
Actually, I used the normal sftp command built into mac, and the transfer of the files went smoothly... who is the "we" that set this limit?
Thanks.

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/36524460-0a67e26e-17e1-11e8-91c0-4fb99a1d4bc0.png)
https://tools.ietf.org/html/rfc4253#section-6.1

**Comment by raytmilan** [comment]
@liximomo I see, but then why was I able to successfully sftp the same exact file with no issues? Are you not using the sftp command in this extension? I am a bit confused on this context.
Thank you again.

**Comment by liximomo** [comment]
I use [ss2](https://github.com/mscdex/ssh2).

**Comment by raytmilan** [comment]
@liximomo I wonder why this is happening if it's just the same ssh/sftp...shouldn't it work either way? Maybe there is a way to fix this issue, because it is a big problem to not be able to edit large files...
Currently I am using an except script to run everytime I save a file, which uploads my file to the server. But it would be convienient if it would work on any platform as an extension that I could use elsewhere, and it is more convenient.
Maybe there is a way to increase this arbirtary limit that is set by the cisco link you sent me, as this is not applied to the sftp by the operating system in Mac osx.
Thanks.
