### ISSUE TITLE
Unable to upload to server

### ISSUE THREAD

**Issue by mgborgman** [liximomo/vscode-sftp#120]
## Expected Behavior
[Description of the expected behavior]
I access the command palette and select SFTP: Upload and then the most recent saved version of my files are saved to my EC2 instance. 

## Actual Behavior
[Description of the actual behavior]
After selecting SFTP: Upload from the command palette I get "Upload done (27 failed)" 

## Steps to Reproduce the Problem

  1. Open VSCode
  2. Open Command Palette and Run SFTP: Upload

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 ```
------
[debug]: task: upload /Users/mattborgman/Development/portfolio
[debug]: try to get /var/www/html/todo-app/schema.sql mode fail, default to 0666
[debug]: try to get /var/www/html/blog/add_post.php mode fail, default to 0666
[debug]: try to get /var/www/html/blog/config.php mode fail, default to 0666
[debug]: try to get /var/www/html/blog/index.php mode fail, default to 0666
[debug]: try to get /var/www/html/blog/post.php mode fail, default to 0666
[debug]: try to get /var/www/html/blog/schema.sql mode fail, default to 0666
[debug]: try to get /var/www/html/todo-app/add-todo.php mode fail, default to 0666
[debug]: try to get /var/www/html/todo-app/config.php mode fail, default to 0666
[debug]: try to get /var/www/html/todo-app/delete-list.php mode fail, default to 0666
[debug]: try to get /var/www/html/todo-app/delete-todo.php mode fail, default to 0666
[debug]: try to get /var/www/html/todo-app/edit-list.php mode fail, default to 0666
[debug]: try to get /var/www/html/todo-app/index.php mode fail, default to 0666
[debug]: try to get /var/www/html/todo-app/list.php mode fail, default to 0666
[debug]: try to get /var/www/html/todo-app/new-list.html mode fail, default to 0666
[debug]: try to get /var/www/html/todo-app/new-list.php mode fail, default to 0666
[debug]: try to get /var/www/html/todo-app/rename-list.php mode fail, default to 0666
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/COMMIT_EDITMSG
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/HEAD
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/ORIG_HEAD
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/config
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/description
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/hooks
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/index
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/info
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/logs
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/objects
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/refs
[debug]: ignore: /Users/mattborgman/Development/portfolio/.vscode/sftp.json
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/FETCH_HEAD
[debug]: ignore: /Users/mattborgman/Development/portfolio/.gitignore
[debug]: ignore: /Users/mattborgman/Development/portfolio/.DS_Store
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/schema.sql
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/blog/add_post.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/blog/config.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/blog/index.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/blog/post.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/blog/schema.sql
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/images/apple_hat.jpg
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/images/apple_hat2.jpg
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/images/desk.jpeg
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/images/yoda_hat.jpg
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/images/yoda_hat2.jpg
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/scripts/javascripts.js
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/styles/style.css
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/styles/whitespace-reset.css
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/add-todo.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/config.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/delete-list.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/delete-todo.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/edit-list.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/index.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/list.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/new-list.html
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/new-list.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/rename-list.php
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/index.html
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/README.md
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/googlea3775e81f62f594b.html
context: transmission file
error: Error: Failure
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
```

## Specifications

  - Version: VSCode: 1.20.1 
                   SFTP: 1.0.5
  - Platform: macOS 10.13.3

**Comment by liximomo** [comment]
Is this always happens? And please run `sftp: upload` command only on `/Users/mattborgman/Development/portfolio/todo-app/schema.sql` and tell me the result.

**Comment by mgborgman** [comment]
This has just started happening yesterday. When I attempt to upload only a single file `/Users/mattborgman/Development/portfolio/todo-app/schema.sql` I get the same result as before. Here are my logs below.

```
[debug]: task: upload /Users/mattborgman/Development/portfolio
[debug]: connect to remote
[debug]: try to get /var/www/html/todo-app/schema.sql mode fail, default to 0666
[debug]: ignore: /Users/mattborgman/Development/portfolio/.vscode/sftp.json
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/HEAD
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/ORIG_HEAD
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/config
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/description
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/hooks
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/index
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/info
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/logs
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/objects
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/refs
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/FETCH_HEAD
[debug]: ignore: /Users/mattborgman/Development/portfolio/.git/COMMIT_EDITMSG
[debug]: ignore: /Users/mattborgman/Development/portfolio/todo-app/add-todo.php
[debug]: ignore: /Users/mattborgman/Development/portfolio/todo-app/config.php
[debug]: ignore: /Users/mattborgman/Development/portfolio/todo-app/delete-list.php
[debug]: ignore: /Users/mattborgman/Development/portfolio/todo-app/delete-todo.php
[debug]: ignore: /Users/mattborgman/Development/portfolio/todo-app/edit-list.php
[debug]: ignore: /Users/mattborgman/Development/portfolio/todo-app/index.php
[debug]: ignore: /Users/mattborgman/Development/portfolio/todo-app/list.php
[debug]: ignore: /Users/mattborgman/Development/portfolio/todo-app/new-list.html
[debug]: ignore: /Users/mattborgman/Development/portfolio/todo-app/new-list.php
[debug]: ignore: /Users/mattborgman/Development/portfolio/todo-app/rename-list.php
[debug]: ignore: /Users/mattborgman/Development/portfolio/.gitignore
[debug]: ignore: /Users/mattborgman/Development/portfolio/googlea3775e81f62f594b.html
[debug]: ignore: /Users/mattborgman/Development/portfolio/images
[debug]: ignore: /Users/mattborgman/Development/portfolio/index.html
[debug]: ignore: /Users/mattborgman/Development/portfolio/scripts
[debug]: ignore: /Users/mattborgman/Development/portfolio/styles
[debug]: ignore: /Users/mattborgman/Development/portfolio/.DS_Store
[debug]: ignore: /Users/mattborgman/Development/portfolio/README.md
[debug]: ignore: /Users/mattborgman/Development/portfolio/blog
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/schema.sql
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
```

**Comment by liximomo** [comment]
The log says that you have executed `sftp: upload` on `/Users/mattborgman/Development/portfolio`. What I mean is that run `sftp: upload` command only on `/Users/mattborgman/Development/portfolio/todo-app/schema.sql`, you can do this by select `sftp: upload` on explorer context menu.

**Comment by mgborgman** [comment]
If you look at the `target` of the logs it shows that the target file is `target: /Users/mattborgman/Development/portfolio/todo-app/schema.sql`

**Comment by mgborgman** [comment]
Here are the logs when I specify just the schema.sql file and don't use ignore to only upload it.

```
[debug]: task: upload /Users/mattborgman/Development/portfolio/todo-app/schema.sql
[debug]: connect to remote
[debug]: try to get /var/www/html/todo-app/schema.sql mode fail, default to 0666
[debug]: 
------
target: /Users/mattborgman/Development/portfolio/todo-app/schema.sql
context: transmission file
error: Error: No such file
	at SFTPStream._transform (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/mattborgman/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
------
```

**Comment by liximomo** [comment]
Does `/var/www/html/todo-app/` directory exist in your server? Do you have the permissions sufficient at `/var/www/html`?
