### ISSUE TITLE
Error: Handshake failed: no matching key exchange algorithm

### ISSUE THREAD

**Issue by keen0927** [liximomo/vscode-sftp#124]
## Requisites (**important to diagnose the problem!**)

not working sftp extension.

i'ts my sftp config. 

`

    "privateKeyPath": null, 
    "agent": null,
    "passphrase": null,
    "interactiveAuth": false,
    "protocol": "sftp",
    "host": "~~~~~~",
    "username": "~~~~",
    "password": "~~~~~",
    "remotePath": "~~~~~",
    "uploadOnSave": true,
    "syncMode": "update",
    "ignore":[
        ".vscode",
        ".git",
        ".DS_Store"
    ],
    "watcher":{
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
    },
    "algorithms": {
        "kex": [
          "diffie-hellman-group1-sha1",
          "ecdh-sha2-nistp256",
          "ecdh-sha2-nistp384",
          "ecdh-sha2-nistp521",
          "diffie-hellman-group-exchange-sha256",
          "diffie-hellman-group14-sha1"
        ],
        "cipher": [
          "3des-cbc",
          "aes128-ctr",
          "aes192-ctr",
          "aes256-ctr",
          "aes128-gcm",
          "aes128-gcm@openssh.com",
          "aes256-gcm",
          "aes256-gcm@openssh.com"
        ],
        "serverHostKey": [
          "ssh-rsa",
          "ecdsa-sha2-nistp256",
          "ecdsa-sha2-nistp384",
          "ecdsa-sha2-nistp521"
        ],
        "hmac": [
          "hmac-sha2-256",
          "hmac-sha2-512",
          "hmac-sha1"
        ]
    }
`

  ### Extension Logs
`	

at check_KEXINIT (/Users/keen/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/ssh.js:2279:15)
at check (/Users/keen/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/ssh.js:2217:9)
at onKEXINIT (/Users/keen/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/ssh.js:2214:5)
at SSH2Stream.<anonymous> (/Users/keen/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/ssh.js:206:5)
at emitTwo (events.js:106:13)
at SSH2Stream.emit (events.js:194:7)
at parse_KEXINIT (/Users/keen/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/ssh.js:4105:8)
at parsePacket (/Users/keen/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/ssh.js:4001:12)
at SSH2Stream._transform (/Users/keen/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/ssh.js:667:13)
at SSH2Stream.Transform._read (_stream_transform.js:167:10)
at SSH2Stream._read (/Users/keen/.vscode/extensions/liximomo.sftp-1.0.5/node_modules/ssh2-streams/lib/ssh.js:251:15)
at SSH2Stream.Transform._write (_stream_transform.js:155:12)
at doWrite (_stream_writable.js:329:12)
at writeOrBuffer (_stream_writable.js:315:5)`
 

## Specifications

  - Version: 1.0.5
  - Platform: High Sierra 10.13.1

**Comment by liximomo** [comment]
What is the valid kex algorithms for your server?  If you don't know, you can set all kex algorithms.
```
{
 "kex": [
      "ecdh-sha2-nistp256",
      "ecdh-sha2-nistp384",
      "ecdh-sha2-nistp521",
      "diffie-hellman-group-exchange-sha256",
      "diffie-hellman-group14-sha1",
      "diffie-hellman-group-exchange-sha1",
      "diffie-hellman-group1-sha1"
 ]
}
```

**Comment by liximomo** [comment]
Try 1.1.0. It should be fixed.

**Comment by keen0927** [comment]
so~~~ amazing thank you!!! so much!!

**Comment by pivdets** [comment]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/37371804/41593696-813a6d3a-73f3-11e8-975e-ef9a4778df16.png">


@liximomo sorry to re-open this issue. I got the same error.

My sftp version is 1.2.2 with my macOS 10.13.5

**Comment by liximomo** [comment]
@evannalikeyou Please file a new issue.
