### ISSUE TITLE
connecting not working

### ISSUE THREAD

**Issue by web-vitality** [liximomo/vscode-sftp#135]
The connection to the server does not work. password and name are correct.

[debug]: remote error Error: Timeout while connecting to server
    at Timeout._onTimeout (C:\***\***\.vscode\extensions\liximomo.sftp-1.1.2\node_modules\ftp\lib\connection.js:304:24)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

I can not figure out what I'm doing wrong.
Thanks.

**Comment by liximomo** [comment]
I will add a timeout option. Then you can set it bigger.

Vitaliy Obukhov <notifications@github.com> 于 2018年3月16日周五 22:16写道：

**Comment by web-vitality** [comment]
when you can try it in action?

**Comment by marekmaurizio** [comment]
Same problem.

**Comment by liximomo** [comment]
Try v1.1.4.

**Comment by web-vitality** [comment]
Hi, still can not connect.I set the time for 60 seconds.

[error]: Error: Timeout while connecting to server
    at Timeout.setTimeout (C:\Users\Vitaliy\.vscode\extensions\liximomo.sftp-1.1.7\out\src\model\Client\FTPClient.js:31:28)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
