### ISSUE TITLE
[sftp] Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Offerel** [liximomo/vscode-sftp#136]
## Expected Behavior
Open configuration

## Actual Behavior
a error message appears "[sftp] Cannot read property 'length' of undefined"

## Steps to Reproduce the Problem
1. fresh install of vsc 1.21.1
2. fresh install of sftp 1.1.2
3. restart vsc
4. press ctrl+shift+p
5. enter "sftp"
6. choose "sftp: config" 

### Extension Logs
```
 [error] TypeError: Cannot read property 'length' of undefined
	at editConfig (C:\Users\sebas\.vscode\extensions\liximomo.sftp-1.1.2\out\src\actions\config.js:8:25)
	at Command.args [as handler] (C:\Users\sebas\.vscode\extensions\liximomo.sftp-1.1.2\out\src\commands\Command.js:36:29)
	at Command.<anonymous> (C:\Users\sebas\.vscode\extensions\liximomo.sftp-1.1.2\out\src\commands\Command.js:46:28)
	at Generator.next (<anonymous>)
	at C:\Users\sebas\.vscode\extensions\liximomo.sftp-1.1.2\out\src\commands\Command.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\sebas\.vscode\extensions\liximomo.sftp-1.1.2\out\src\commands\Command.js:3:12)
	at Command.run (C:\Users\sebas\.vscode\extensions\liximomo.sftp-1.1.2\out\src\commands\Command.js:43:16)
	at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:620:380)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:620:797)
```
 

## Specifications
  - Version: vsc 1.21.1
  - Platform: Windows 10 Home 64bit

**Comment by Offerel** [comment]
Ahh, i have to open first a workspace. If that's the case and i have a workspace open, no such error message comes out. That should be noted in the documentation.

**Comment by liximomo** [comment]
I will show an error message when you try to use sftp without an open workspace folder.
