### ISSUE TITLE
FIle not found when using array of multiple sited on sftp.json 

### ISSUE THREAD

**Issue by davidcsi** [liximomo/vscode-sftp#154]
## Expected Behavior
To download an syn file to:

workspace/david (from remote /homer/david/)
workspace/freeswitch (from remote /etc/freeswitch/)

## Actual Behavior
VisualCode error "file not found"

## Steps to Reproduce the Problem

  1. create a new folder
  1. add sftp.json with the following:
```
[
    {
        "context": "david",
        "host": "192.168.2.201",
        "port": 22,
        "username": "root",
        "password": null,
        "protocol": "sftp",
        "agent": null,
        "privateKeyPath": "/Users/david/.ssh/id_rsa",
        "passphrase": null,
        "passive": false,
        "interactiveAuth": false,
        "remotePath": "/home/david",
        "uploadOnSave": true,
        "syncMode": "update",
        "watcher": {
            "files": false,
            "autoUpload": false,
            "autoDelete": false
        },
        "ignore": [
            "**/.vscode/**",
            "**/.git/**",
            "**/.DS_Store"
        ]
    }
    ,
    {
        "context": "freeswitch",
        "host": "192.168.2.201",
        "port": 22,
        "username": "root",
        "password": null,
        "protocol": "sftp",
        "agent": null,
        "privateKeyPath": "/Users/david/.ssh/id_rsa",
        "passphrase": null,
        "passive": false,
        "interactiveAuth": false,
        "remotePath": "/etc/freeswitch",
        "uploadOnSave": true,
        "syncMode": "update",
        "watcher": {
            "files": false,
            "autoUpload": false,
            "autoDelete": false
        },
        "ignore": [
            "**/.vscode/**",
            "**/.git/**",
            "**/.DS_Store"
        ]
    }
]
```
  1. Click on sftp->Download 

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 

## Specifications

  - Version:
  - Platform:

**Comment by liximomo** [comment]
Please provide the logs.

**Comment by davidcsi** [comment]
Sorry about that, I saw the requirement, but wasn't sure how to get the logs. Here they are:

[info] config at /worksapce/david {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/david","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/worksapce/david"}
[info] config at /workspace/freeswitch {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/etc/freeswitch","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/workspace/freeswitch"}
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[info] config at /worksapce/david {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/david","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/worksapce/david"}
[info] config at /workspace/freeswitch {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/etc/freeswitch","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/workspace/freeswitch"}
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[info] config at /worksapce/david {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/david","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/worksapce/david"}
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[info] config at /worksapce/david {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/david","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/worksapce/david"}
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[error]: SyntaxError: /Users/david/Documents/local_ubuntu/.vscode/sftp.json: Unexpected token , in JSON at position 689
	at JSON.parse (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/node_modules/jsonfile/index.js:36:18
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/node_modules/graceful-fs/graceful-fs.js:78:16
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
[info] config at /worksapce/david {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/david","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/worksapce/david"}
[info] config at /workspace/freeswitch {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/etc/freeswitch","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/workspace/freeswitch"}
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[error]: SyntaxError: /Users/david/Documents/local_ubuntu/.vscode/sftp.json: Unexpected token } in JSON at position 686
	at JSON.parse (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/node_modules/jsonfile/index.js:36:18
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/node_modules/graceful-fs/graceful-fs.js:78:16
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[error]: Error: (/Users/david/Documents/local_ubuntu/.vscode/sftp.json) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[error]: SyntaxError: /Users/david/Documents/local_ubuntu/.vscode/sftp.json: Unexpected token } in JSON at position 675
	at JSON.parse (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/node_modules/jsonfile/index.js:36:18
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/node_modules/graceful-fs/graceful-fs.js:78:16
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
[info] config at /Users/david/Documents/local_ubuntu/david {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/david","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/Users/david/Documents/local_ubuntu/david"}
[info] config at /Users/david/Documents/local_ubuntu/freeswitch {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/etc/freeswitch","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/Users/david/Documents/local_ubuntu/freeswitch"}
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[info] config at /Users/david/Documents/local_ubuntu/david {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/david","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/Users/david/Documents/local_ubuntu/david"}
[info] config at /Users/david/Documents/local_ubuntu/freeswitch {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/etc/freeswitch","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/Users/david/Documents/local_ubuntu/freeswitch"}
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[info] config at /Users/david/Documents/local_ubuntu/david {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/david","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/Users/david/Documents/local_ubuntu/david"}
[info] config at /Users/david/Documents/local_ubuntu/freeswitch {"protocol":"sftp","host":"192.168.2.201","port":22,"username":"root","password":null,"connectTimeout":10000,"agent":null,"privateKeyPath":"/Users/david/.ssh/id_rsa","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/etc/freeswitch","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/Users/david/Documents/local_ubuntu/freeswitch"}
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)
[error]: Error: (/Users/david/Documents/local_ubuntu) config file not found
	at Object.getConfig (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/modules/config.js:133:15)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:28:41)
	at Generator.next (<anonymous>)
	at /Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:25:16)
	at pendingTasks.concat.map.target (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/out/src/commands/FileCommand.js:45:53)

**Comment by liximomo** [comment]
You config context are /Users/david/Documents/local_ubuntu/david  and /Users/david/Documents/local_ubuntu/david. You could only get sftp worked under these two directory. The `/Users/david/Documents/local_ubuntu/` is parent of them.

**Comment by davidcsi** [comment]
Hello, thanks for helping me out. 
I don't understand what you mean, can you provide a working sample?

**Comment by liximomo** [comment]
Just use a single config with `context` setting to ` /Users/david/Documents/local_ubuntu/`

**Comment by davidcsi** [comment]
Sorry, i'm now coming back to this...
i tried:

```
[
    {
        "context": "/Users/david/Documents/local_ubuntu/",
        "host": "192.168.2.201",
        "port": 22,
        "username": "root",
        "password": null,
        "protocol": "sftp",
        "agent": null,
        "privateKeyPath": "/Users/david/.ssh/id_rsa",
        "passphrase": null,
        "passive": false,
        "interactiveAuth": false,
        "remotePath": "/home/david",
        "uploadOnSave": true,
        "syncMode": "update",
        "watcher": {
            "files": false,
            "autoUpload": false,
            "autoDelete": false
        },
        "ignore": [
            "**/.vscode/**",
            "**/.git/**",
            "**/.DS_Store"
        ]
    },
    {
        "context": "/Users/david/Documents/local_ubuntu/",
        "host": "192.168.2.201",
        "port": 22,
        "username": "root",
        "password": null,
        "protocol": "sftp",
        "agent": null,
        "privateKeyPath": "/Users/david/.ssh/id_rsa",
        "passphrase": null,
        "passive": false,
        "interactiveAuth": false,
        "remotePath": "/etc/freeswitch",
        "uploadOnSave": true,
        "syncMode": "update",
        "watcher": {
            "files": false,
            "autoUpload": false,
            "autoDelete": false
        },
        "ignore": [
            "**/.vscode/**",
            "**/.git/**",
            "**/.DS_Store"
        ]
    }
]

```

Still failing with:

```
[info] connected
[error]: Error: No such file
	at SFTPStream._transform (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/node_modules/ssh2-streams/lib/sftp.js:410:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/david/.vscode/extensions/liximomo.sftp-1.1.6/node_modules/ssh2-streams/lib/sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
```

**Comment by liximomo** [comment]
Why same context with two different remotePath? Tell me these:

1. Absolute path of your workspace folder.
2. You want to put what file to where. ( /local/a/b/c to /remote/d/e/f )

**Comment by davidcsi** [comment]
ok, my local working path is:
`/Users/david/Documents/local_ubuntu/`

And I want the remote paths om the same server:
```
/etc/freeswitch/
/home/admin
```

to be mapped locally to:
```
/Users/david/Documents/local_ubuntu/freeswitch
/Users/david/Documents/local_ubuntu/admin
```

so:

```
remote /etc/freeswitch/ -> local /Users/david/Documents/local_ubuntu/freeswitch
remote /home/admin -> local /Users/david/Documents/local_ubuntu/admin

```

**Comment by liximomo** [comment]
OK. Your first config is correct. But your command target is wrong. 

```
[
    {
        "context": "admin",
        "remotePath": "/home/admin",
         ...
    }
    ,
    {
        "context": "freeswitch",
        "remotePath": "/etc/freeswitch",
        ...
    }
]
```
You can only run command at file under these `context`.  Try right click `/Users/david/Documents/local_ubuntu/admin` -> 'sftp: upload'

**Comment by davidcsi** [comment]
Ok this worked!
But, i had to CREATE the directories locally before, and as you pointed out, i first had to do "sftp: upload" and then "sftp:download" on each of the directories.

```
[
    {
        "context": "freeswitch",
        "host": "192.168.2.201",
        "port": 22,
        "username": "root",
        "password": null,
        "protocol": "sftp",
        "agent": null,
        "privateKeyPath": "/Users/david/.ssh/id_rsa",
        "passphrase": null,
        "passive": false,
        "interactiveAuth": false,
        "remotePath": "/opt/freeswitch/etc/freeswitch/",
        "uploadOnSave": true,
        "syncMode": "update",
        "watcher": {
            "files": false,
            "autoUpload": false,
            "autoDelete": false
        },
        "ignore": [
            "**/.vscode/**",
            "**/.git/**",
            "**/.DS_Store"
        ]
    }
    ,
    {
        "context": "root",
        "host": "192.168.2.201",
        "port": 22,
        "username": "root",
        "password": null,
        "protocol": "sftp",
        "agent": null,
        "privateKeyPath": "/Users/david/.ssh/id_rsa",
        "passphrase": null,
        "passive": false,
        "interactiveAuth": false,
        "remotePath": "/root",
        "uploadOnSave": true,
        "syncMode": "update",
        "watcher": {
            "files": false,
            "autoUpload": false,
            "autoDelete": false
        },
        "ignore": [
            "**/.vscode/**",
            "**/.git/**",
            "**/.DS_Store"
        ]
    }
]
```

Maybe that should go in the documentation :)

thanks!

**Comment by liximomo** [comment]
>  I first had to do "sftp: upload" and then "sftp:download" on each of the directories.
No, you needn't.  You can invoke `sftp:download` from the Command Palette(ctrl/cmd + shift + p).

**Comment by 14714** [comment]
Greetings. I had the same problem, but i fixed with a specified **context**, example: 
`"context": "/laragon/www/project/"`
