### ISSUE TITLE
[error]: Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by spward** [liximomo/vscode-sftp#159]
## Expected Behavior
upload files to server

## Actual Behavior
[error]: Error: All configured authentication methods failed

## Steps to Reproduce the Problem

  1. Load up VS Code
  2.  try to upload files

### Extension Logs

[error]: Error: All configured authentication methods failed
    at tryNextAuth (C:\Users\sward7\.vscode\extensions\liximomo.sftp-1.1.7\node_modules\ssh2\lib\client.js:380:17)
    at SSH2Stream.onUSERAUTH_FAILURE (C:\Users\sward7\.vscode\extensions\liximomo.sftp-1.1.7\node_modules\ssh2\lib\client.js:591:5)
    at emitTwo (events.js:106:13)
    at SSH2Stream.emit (events.js:194:7)
    at parsePacket (C:\Users\sward7\.vscode\extensions\liximomo.sftp-1.1.7\node_modules\ssh2-streams\lib\ssh.js:3929:10)
    at SSH2Stream._transform (C:\Users\sward7\.vscode\extensions\liximomo.sftp-1.1.7\node_modules\ssh2-streams\lib\ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\sward7\.vscode\extensions\liximomo.sftp-1.1.7\node_modules\ssh2-streams\lib\ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SSH2Stream.Writable.write (_stream_writable.js:241:11)
    at Socket.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
 

## Specifications

  - Version:
  - Platform:

**Comment by liximomo** [comment]
I think the message is clear.

**Comment by spward** [comment]
Im not sure what it means though

**Comment by liximomo** [comment]
Your authentication is fail. If you use password then it means you have a wrong password with the usename.

**Comment by spward** [comment]
Ok sorry. That was a dumb moment of mine.
