### ISSUE TITLE
intermittent Error: read ECONNRESET

### ISSUE THREAD

**Issue by johannes-see** [liximomo/vscode-sftp#164]
I'm on Win 10 with todays version of VS Code and most recent version of sftp. It's a great extension. Recently (since some weeks ago) I keep getting `Error: read ECONNRESET` sometimes, like every fifth time I `CTRL + S` and sftp tries to upload automatically. Eventually, I can upload the file but it takes some minutes.

Log of a succesful upload:
```
[info] upload <file>
[debug] > PASV
[debug] < 227 Entering Passive Mode (93,189,28,17,175,163).
[debug] > LIST <remote-dir>
[debug] < 150 Opening BINARY mode data connection for file list
[debug] < 226 Transfer complete
[debug] > PASV
[debug] < 227 Entering Passive Mode (93,189,28,17,149,50).
[debug] > STOR <file in remote-dir>
[info] upload <file>
[debug] < 150 Opening BINARY mode data connection for <file under remote-dir>
[debug] < 226 Transfer complete
[debug] > PASV
[info] [file-save] upload <file>
[debug] < 227 Entering Passive Mode (93,189,28,17,135,102).
[debug] > LIST <remote-dir>
[debug] < 150 Opening BINARY mode data connection for file list
[debug] < 226 Transfer complete
[debug] > PASV
[debug] < 227 Entering Passive Mode (93,189,28,17,180,102).
[debug] > STOR <file under remote-dir>
[debug] < 150 Opening BINARY mode data connection for <file under remote-dir>
[debug] < 226 Transfer complete
[info] [watcher] upload <file>
```

and here is the log of a failed attempt:
```
[info] upload <file>
[debug] > PASV
[debug] < 227 Entering Passive Mode (93,189,28,17,140,197).
[debug] > LIST <remote-dir>
[debug] < 150 Opening BINARY mode data connection for file list
[debug] < 226 Transfer complete
[debug] > PASV
[debug] < 227 Entering Passive Mode (93,189,28,17,148,3).
[info] upload <file under remote-dir>
[debug] > PASV
[debug] < 227 Entering Passive Mode (93,189,28,17,138,222).
[debug] > LIST <remote-dir>
[debug] < 150 Opening BINARY mode data connection for file list
[debug] < 226 Transfer complete
[debug] > STOR <file under remote-dir>
[debug] < 425 Unable to build data connection: Connection timed out
[debug] > PASV
[error]: Error: read ECONNRESET
	at exports._errnoException (util.js:1050:11)
	at TCP.onread (net.js:581:26)
[debug] < 227 Entering Passive Mode (93,189,28,17,163,225).
[info] [file-save] upload <file>
[debug] > STOR <file under remote-dir>
[debug] < 150 Opening BINARY mode data connection for <file under remote-dir>
[debug] < 226 Transfer complete
[info] [watcher] upload <file>
[debug] < 200 NOOP command successful
```

thank you for any help.

**Comment by liximomo** [comment]
You have `autoSave` and `watcher` conflicted. Don't set `autoSave` to true if the file has been watched and vice versa.

**Comment by johannes-see** [comment]
this is my config:
```
{
    "host": "***",
    "port": 21,
    "context": "***",
    "username": "***",
    "password": "***",
    "protocol": "ftp",
    "passive": false,
    "remotePath": "***",
    "uploadOnSave": true,
    "syncMode": "full",
    "watcher": {
        "files": "**/**",
        "autoUpload": true,
        "autoDelete": true
    },
    "concurrency": 512
}
```

**Comment by liximomo** [comment]
It's my fault. Not `autoSave` but `uploadOnSave `.

```
    "uploadOnSave": false,
```

**Comment by johannes-see** [comment]
so i set autoUpload to false because i actually want uploadOnSave instead. It's clockwork now, works perfectly. thank you very much
