### ISSUE TITLE
Device or resource busy

### ISSUE THREAD

**Issue by g5wx** [liximomo/vscode-sftp#183]
Never mind, server misconfiguration. Please close this issue and thanks for a great extension :)

**Comment by sleepless-se** [comment]
I got same issue. this is the error code.

`[error] Error: .: Device or resource busy
	at v (/Users/main/.vscode/extensions/liximomo.sftp-1.9.5/dist/extension.js:70:110272)
	at d.<anonymous> (/Users/main/.vscode/extensions/liximomo.sftp-1.9.5/dist/extension.js:70:110995)
	at d.emit (events.js:182:13)
	at d.module.exports.d._write (/Users/main/.vscode/extensions/liximomo.sftp-1.9.5/dist/extension.js:70:123817)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at d.Writable.write (_stream_writable.js:294:11)
	at Socket.p (/Users/main/.vscode/extensions/liximomo.sftp-1.9.5/dist/extension.js:70:113366)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onread (net.js:636:20) download`
