### ISSUE TITLE
Cannot read property 'fsPath' of null

### ISSUE THREAD

**Issue by andremacola** [liximomo/vscode-sftp#200]
Created a shortcut but an error occurs: "I created a shortcut but an error occurs"
```	{
		"key": "cmd+d",
		"command": "sftp.trans.remote",
		"when": "editorTextFocus"
	}
```

OSX High Sierra
VSCode 1.24.0-insider 

![captura de tela 2018-05-25 as 01 28 42](https://user-images.githubusercontent.com/3408809/40526177-0cdbd2b8-5fbb-11e8-9ae0-f706e27b85e6.png)

**Comment by liximomo** [comment]
You can't run this shortcut without focusing on a document.

**Comment by andremacola** [comment]
@liximomo I am focusing a document

**Comment by wilsonchow** [comment]
Same here!  "Cannot read property 'fsPath' of null" pops up when try to use the keyboard shortcut.  However, sftp.trans.remote still works by default right mouse button and click, but shortcut keys doesn't after upgraded to VSCode 1.24 few hours ago!!  Help!

**Comment by gergokoos** [comment]
Same appears here, I'm trying to use the keyboard shortcut when I get the notification. And as for @wilsonchow happened after the VS Code 1.24 update. sftp version is 1.1.11,

here is the stacktrace:
`[error] TypeError: Cannot read property 'fsPath' of null
	at FileCommand.selectFileFallbackToConfigContext [as getFileTarget] (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\modules\targetSelectStrategy.js:80:14)
	at FileCommand.<anonymous> (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:47:40)
	at Generator.next (<anonymous>)
	at C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:3:12)
	at FileCommand.handler (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:46:16)
	at FileCommand.<anonymous> (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:29:25)
	at Generator.next (<anonymous>)
	at C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:3:12)
	at FileCommand.run (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:28:16)
	at FileCommand.<anonymous> (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\BaseCommand.js:39:28)
	at Generator.next (<anonymous>)
	at C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\BaseCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\BaseCommand.js:3:12)
	at FileCommand._commandHandler (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\BaseCommand.js:37:16)
	at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:613)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:675:6)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
[error] TypeError: Cannot read property 'fsPath' of null
	at FileCommand.selectFileFallbackToConfigContext [as getFileTarget] (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\modules\targetSelectStrategy.js:80:14)
	at FileCommand.<anonymous> (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:47:40)
	at Generator.next (<anonymous>)
	at C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:3:12)
	at FileCommand.handler (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:46:16)
	at FileCommand.<anonymous> (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:29:25)
	at Generator.next (<anonymous>)
	at C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:3:12)
	at FileCommand.run (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:28:16)
	at FileCommand.<anonymous> (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\BaseCommand.js:39:28)
	at Generator.next (<anonymous>)
	at C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\BaseCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\BaseCommand.js:3:12)
	at FileCommand._commandHandler (C:\Users\username\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\BaseCommand.js:37:16)
	at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:613)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:675:6)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)`

**Comment by palanza** [comment]
when update packages?

**Comment by caneco** [comment]
Got this error when I've updated VSCODE to the new version `Version 1.24.0 (1.24.0)`

**Comment by kumorig** [comment]
I tried this extension for the first time in 1.24.0 and I get this error constantly.

**Comment by gergokoos** [comment]
@kumorig until it get's fixed you can use the contextual menus.
Or in the meantime you can just fix it for yourself, look at my pull request.

**Comment by liximomo** [comment]
This is because the vscode change its behaviour in 1.24.0. More detail in [here](https://github.com/liximomo/vscode-sftp/pull/209).

**Comment by liximomo** [comment]
The v1.1.2 has fixed it and been published.

**Comment by caneco** [comment]
@liximomo it's fixed! Thanks!
