### ISSUE TITLE
Unexpected packet before version

### ISSUE THREAD

**Issue by clayms** [liximomo/vscode-sftp#202]
## Expected Behavior
syncing to local or uploading

## Actual Behavior
get error `Unexpected packet before version`

## Steps to Reproduce the Problem

SFTP: upload  or download

### Extension Logs

```
[error] Error: Unexpected packet before version
	at SFTPStream._transform (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.11\node_modules\ssh2-streams\lib\sftp.js:306:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.11\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.11\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.11\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.11\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.11\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
```
 

## Specifications

  - Version: 1.1.11 - 2018-05-21
  - Platform: Windows 10 x64
  - VS Code: 1.23.1

**Comment by liximomo** [comment]
>  Log in to your box via regular ssh first. 
If you're seeing random text coming into your terminal, that is most likely your problem.
Figure out what's causing it and stop it (checking for rogue echo statements in the .bash* files is a good start)

**Comment by clayms** [comment]
thanks, it was a rogue echo statement.

**Comment by chenwei182729** [comment]
## CentOS7 配置SFTP用于支持root用户登录
1. 修改配置文件`/etc/ssh/sshd_config`

```bash
##释掉以下语句
#Subsystem    sftp /usr/libexec/openssh/sftp-server
##后面加入
Subsystem sftp internal-sftp
```
2. 重启sshd服务

`systemctl restart sshd`
