### ISSUE TITLE
mac os 10.13.4 cannot use while windows 7 / 10 is okay

### ISSUE THREAD

**Issue by lunkaleung** [liximomo/vscode-sftp#206]
## Expected Behavior
SFTP: List All can show remove directories and files at opened workspace folder.

## Actual Behavior
Prompt Failure

### Extension Logs

```
[error] Error: Failure
	at SFTPStream._transform (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.1.11/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.1.11/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.1.11/node_modules/ssh2/lib/Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.1.11/node_modules/ssh2-streams/lib/ssh.js:3445:10)
	at SSH2Stream._transform (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.1.11/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.1.11/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
 
```

## Specifications

  - Version: sftp 1.1.11
  - Platform: macOS High Sierra 10.13.4 (17E202)

**Comment by liximomo** [comment]
Full logs please.

**Comment by lunkaleung** [comment]
[error] Error: All configured authentication methods failed
	at tryNextAuth (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2/lib/client.js:392:17)
	at SSH2Stream.onUSERAUTH_FAILURE (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2/lib/client.js:599:5)
	at emitTwo (events.js:106:13)
	at SSH2Stream.emit (events.js:194:7)
	at parsePacket (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/ssh.js:3930:10)
	at SSH2Stream._transform (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
[info] config at /Users/lunkaleung/Desktop/untitled folder {"remotePath":"/","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":[],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":4,"protocol":"sftp","host":"*****","port":22,"username":"******","password":"******","connectTimeout":10000,"interactiveAuth":false,"sshConfigPath":"~/.ssh/config","secure":false,"passive":false,"context":"/Users/lunkaleung/Desktop/untitled folder"}
[trace] execute (list) download for /Users/lunkaleung/Desktop/untitled folder/home/ubuntu/vue.js
[error] Error: Failure
	at SFTPStream._transform (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2/lib/Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/ssh.js:3445:10)
	at SSH2Stream._transform (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
[trace] execute (list) download for /Users/lunkaleung/Desktop/untitled folder/home/ubuntu/vue.js
[error] Error: Failure
	at SFTPStream._transform (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2/lib/Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/ssh.js:3445:10)
	at SSH2Stream._transform (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.3/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)

**Comment by liximomo** [comment]
I think you should check your authentication config.

lunkaleung <notifications@github.com> 于 2018年8月7日周二 20:06写道：

**Comment by liximomo** [comment]
Try v1.3.6.

**Comment by lunkaleung** [comment]
I've tried v1.3.8. But it seems that the problem is still exist.
Could you help have a look?

```
[trace] execute (list) download for /Users/XXX
[debug] transfer /home/XXX /Users/XXX
[error] Error: Failure
	at SFTPStream._transform (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.8/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.8/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.8/node_modules/ssh2/lib/Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.8/node_modules/ssh2-streams/lib/ssh.js:3445:10)
	at SSH2Stream._transform (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.8/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (/Users/lunkaleung/.vscode/extensions/liximomo.sftp-1.3.8/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
```

**Comment by liximomo** [comment]
It's hard to say. The error message comes directly from the sftp server. I can see the remote path is '/', maybe you don't have enough permissions for root dir.

**Comment by dave0j** [comment]
I have the exact same problem on macOS 10.13.6 with sftp 1.5.12, only when uploading a file to the root of the remote location. Items in sub-directories upload as expected. Validated that there are no permissions issues, and command line 'scp' and 'sftp' works as expected to transfer files.

**Comment by liximomo** [comment]
@dave0j  Please try the [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).
