### ISSUE TITLE
Config File Not Found

### ISSUE THREAD

**Issue by JohnJosy** [liximomo/vscode-sftp#212]
## Expected Behavior
Hi, 
until yesterday it worked correctly, I saved and the file was loaded

## Actual Behavior
Today it does not load files on the remote server, from this **error config file not found**,
but as I said the configuration file and in the same folder

## Steps to Reproduce the Problem

  1. Edit file.
  1. Save File (ctrl + s).
  1. Error.
![image](https://user-images.githubusercontent.com/19427698/41585431-56e620e0-73aa-11e8-852a-e8db3c36a678.png)

## Requisites (**important to diagnose the problem!**)

 Error: (\\internal\_produzione\garganomizarhotel.com.dev\online\test.php) config file not found
    at Object.getConfig (C:\Users\john\.vscode\extensions\liximomo.sftp-1.2.0\out\src\modules\config.js:215:15)
    at FileCommand.<anonymous> (C:\Users\john\.vscode\extensions\liximomo.sftp-1.2.0\out\src\commands\FileCommand.js:37:41)
    at Generator.next (<anonymous>)
    at C:\Users\john\.vscode\extensions\liximomo.sftp-1.2.0\out\src\commands\FileCommand.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\john\.vscode\extensions\liximomo.sftp-1.2.0\out\src\commands\FileCommand.js:3:12)
    at FileCommand.handleFile (C:\Users\john\.vscode\extensions\liximomo.sftp-1.2.0\out\src\commands\FileCommand.js:33:16)
    at pendingTasks.concat.map.target (C:\Users\john\.vscode\extensions\liximomo.sftp-1.2.0\out\src\commands\FileCommand.js:54:72)
    at Array.map (native)
    at FileCommand.<anonymous> (C:\Users\john\.vscode\extensions\liximomo.sftp-1.2.0\out\src\commands\FileCommand.js:54:53)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\john\.vscode\extensions\liximomo.sftp-1.2.0\out\src\commands\FileCommand.js:4:58)
    at <anonymous>

## Specifications

  - 1.2.0 :
  - Windows 10  Pro:

**Comment by liximomo** [comment]
Fix in v1.2.2.

**Comment by JohnJosy** [comment]
Tooop...you're the Best.
Thanks a lot
