### ISSUE TITLE
Incomplete file uploads

### ISSUE THREAD

**Issue by Sammons** [liximomo/vscode-sftp#217]
## Expected Behavior
[Description of the expected behavior]

Upload uploads the entire file

## Actual Behavior
[Description of the actual behavior]

When I right click and select upload, I get a generic Failed error, and the file on the remote is half-written. It is not a big file at about ~240 lines.

## Steps to Reproduce the Problem

I'm not sure, some files succeed and some fail, but it seems like the ones that fail, are failing consistently. I tried deleting the remote file but it does not resolve the issue.

EDIT: it only succeeds for files containing <= 4092 characters.

### Extension Logs
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.printDebugLog` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
 ```
[error] Error: Failure
	at SFTPStream._transform (C:\Users\me\.vscode\extensions\liximomo.sftp-1.1.9\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\me\.vscode\extensions\liximomo.sftp-1.1.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (C:\Users\me\.vscode\extensions\liximomo.sftp-1.1.9\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (C:\Users\me\.vscode\extensions\liximomo.sftp-1.1.9\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\me\.vscode\extensions\liximomo.sftp-1.1.9\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (C:\Users\me\.vscode\extensions\liximomo.sftp-1.1.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
```
## Specifications

  - Version:  1.1.9
  - Platform: Windows 7

**Comment by Sammons** [comment]
resolved. the remote machine was out of disk space :100:
