### ISSUE TITLE
config file not found

### ISSUE THREAD

**Issue by riandgit** [liximomo/vscode-sftp#218]
[error] Error: (e:\CCPL\CCPL_PROJECT\CCPL_API_POOL\Root_Folder_SFTP_Test) config file not found
	at Object.getConfig (C:\Users\FREI\.vscode\extensions\liximomo.sftp-1.2.3\out\src\modules\config.js:207:15)
	at FileCommand.<anonymous> (C:\Users\FREI\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:37:41)
	at Generator.next (<anonymous>)
	at C:\Users\FREI\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\FREI\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:3:12)
	at FileCommand.handleFile (C:\Users\FREI\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:33:16)
	at pendingTasks.concat.map.target (C:\Users\FREI\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:54:72)
	at Array.map (native)
	at FileCommand.<anonymous> (C:\Users\FREI\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:54:53)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\FREI\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:4:58)
	at <anonymous>

**Comment by liximomo** [comment]
Full logs. Please.
