### ISSUE TITLE
VSCode bug: "window.titleBarStyle": "custom" cause sftp stop working.

### ISSUE THREAD

**Issue by chrom007** [liximomo/vscode-sftp#220]
With new VS feature `"window.titleBarStyle": "custom"` don't work `Upload File` function!

Error log:

`[error] TypeError: Cannot read property 'substr' of undefined
    at normalizeTriePath (C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\modules\config.js:99:32)`

OS: Windows

**Comment by liximomo** [comment]
Can you provide the full log with `sftp.printDebugLog` setting to `true` ?

**Comment by chrom007** [comment]
@liximomo its too in Output: sftp ? If so then here: 

```
[info] config at c:\Web\domains\sportbets {"protocol":"ftp","host":"185.***.***.**","port":21,"username":"******","password":"******","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"sshConfigPath":"~/.ssh/config","secure":false,"passive":false,"remotePath":"/var/www/sport","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store",".vscode",".sass-cache","config.rb","*.sql",".git",".git*","/node_modules/","/node_modules","/node_modules/","*/node_modules/","*/node_modules"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":4,"context":"c:\\Web\\domains\\sport"}
[error] TypeError: Cannot read property 'toString' of undefined
    at args.map.arg (C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\ui\output.js:32:22)
    at Array.map (native)
    at Object.print (C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\ui\output.js:28:10)
    at VSCodeLogger.trace (C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\logger.js:10:20)
    at FileCommand.<anonymous> (C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:35:30)
    at Generator.next (<anonymous>)
    at C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:3:12)
    at FileCommand.handleFile (C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:33:16)
    at pendingTasks.concat.map.target (C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:54:72)
    at Array.map (native)
    at FileCommand.<anonymous> (C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:54:53)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\CHROM\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:4:58)
    at <anonymous>
```

And this is end 🔚

**Comment by liximomo** [comment]
What did you do?

**Comment by chrom007** [comment]
@liximomo i update VS to 1.25, and enable new feature in settings: `"window.titleBarStyle": "custom"`, after this open my project and wanted to upload file to FTP server...
This feature changes the top bar to non-standard, and with it all drop-down lists. I think it's because of non-standard lists 😡

**Comment by liximomo** [comment]
So can you confirm that it can work without `"window.titleBarStyle": "custom"`.

**Comment by chrom007** [comment]
@liximomo yes, of course! It's just because of this

**Comment by liximomo** [comment]
Unfortunately,  it's fine on my MacBook Pro.  I think it's more likely a bug of vscode. I will find the answer. Give me some time.

**Comment by chrom007** [comment]
Okay, thanks. I think its Windows only problem... 
If you have the opportunity, test it on Windows 💻

**Comment by jaycenet** [comment]
This bug is resolved in the latest version of vscode (1.26.0)

**Comment by liximomo** [comment]
I can close it now.

**Comment by EveRainbow** [comment]
I had the same problem and have solve it by writing the password in config file.
