### ISSUE TITLE
Failure to save files in top level if top leve is a link

### ISSUE THREAD

**Issue by masics** [liximomo/vscode-sftp#231]
## Expected Behavior
If last name in the "remotePath" is a link, the files in the top level cannot be saved.

## Actual Behavior
Error is reported:
[error] Error: Failure
    at SFTPStream._transform (C:\Users\masics\.vscode\extensions\liximomo.sftp-1.2.3\node_modules\ssh2-streams\lib\sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\masics\.vscode\extensions\liximomo.sftp-1.2.3\node_modules\ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SFTPStream.Writable.write (_stream_writable.js:241:11)
    at Channel.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Channel.Readable.push (_stream_readable.js:136:10)
    at SSH2Stream.<anonymous> (C:\Users\masics\.vscode\extensions\liximomo.sftp-1.2.3\node_modules\ssh2\lib\Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (C:\Users\masics\.vscode\extensions\liximomo.sftp-1.2.3\node_modules\ssh2-streams\lib\ssh.js:3445:10)
    at SSH2Stream._transform (C:\Users\masics\.vscode\extensions\liximomo.sftp-1.2.3\node_modules\ssh2-streams\lib\ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\masics\.vscode\extensions\liximomo.sftp-1.2.3\node_modules\ssh2-streams\lib\ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SSH2Stream.Writable.write (_stream_writable.js:241:11)
    at Socket.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)

## Steps to Reproduce the Problem
On a remote machine:
mkdir /home/$USER/dir1
mkdir /home/$USER/dir2
ln -s /home/$USER/dir2 /home/$USER/dir1
echo "Test" > /home/$USER/dir1/dir2/test.txt

On local machine:
{
  "protocol": "sftp",
  "host": "192.168.0.2",
  "remotePath": "/home/masics/dir1/dir2",
  "username": "masics",
  "uploadOnSave": true,
  "privateKeyPath": "c:/Users/masics/.ssh/id_dsa"
}

Then try to modify and write "test.txt" file.

## Specifications

  - Version: 1.2.3
  - Platform: 
        Remote: Linux
        Local: Windows 7

**Comment by liximomo** [comment]
Try this.

```bash
mkdir /home/$USER/dir1
mkdir /home/$USER/dir2
ln -s /home/$USER/dir2 /home/$USER/dir1
cd dir1
cd dir2 // oops
```
