### ISSUE TITLE
error

### ISSUE THREAD

**Issue by baturorkun** [liximomo/vscode-sftp#248]
i created .vscode/sftp.json

{
    context: "/Users/batur/Projects/fastlane",
    host: "192.168.1.22",
    port: 22,
    username: "batur",
    password: "******",
    protocol: "sftp", // current only support sftp
    privateKeyPath: null, // absolute path to user private key
    passphrase: null,
    remotePath: "/Users/batur/ci/fastlane", 
    uploadOnSave: true
}
But i have an error:

[error] Error: (/Users/batur/Projects/fastlane/tests.sh) config file not found
	at Object.getConfig (/Users/batur/.vscode/extensions/liximomo.sftp-1.2.5/out/src/modules/config.js:241:15)
	at FileCommand.<anonymous> (/Users/batur/.vscode/extensions/liximomo.sftp-1.2.5/out/src/commands/FileCommand.js:37:41)
	at Generator.next (<anonymous>)
	at /Users/batur/.vscode/extensions/liximomo.sftp-1.2.5/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/batur/.vscode/extensions/liximomo.sftp-1.2.5/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/batur/.vscode/extensions/liximomo.sftp-1.2.5/out/src/commands/FileCommand.js:33:16)
	at pendingTasks.concat.map.target (/Users/batur/.vscode/extensions/liximomo.sftp-1.2.5/out/src/commands/FileCommand.js:55:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/batur/.vscode/extensions/liximomo.sftp-1.2.5/out/src/commands/FileCommand.js:55:53)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/batur/.vscode/extensions/liximomo.sftp-1.2.5/out/src/commands/FileCommand.js:4:58)
	at <anonymous>

**Comment by liximomo** [comment]
Where does the file `.vscode/sftp.json` locate in?

**Comment by baturorkun** [comment]
hi QingCT
are you sure? this is full path.
when i saved the Appfile, i have an error: (/Users/batur/Projects/fastlane/Appfile) config file not found

**Comment by codesboy** [comment]
The same problem.


![1](https://user-images.githubusercontent.com/9047357/43495417-925912cc-956a-11e8-91d1-70e651c4e034.png)
![2](https://user-images.githubusercontent.com/9047357/43495419-93ce8a42-956a-11e8-9273-d43118135356.png)

**Comment by QingCT** [comment]
hi codesboy
    这是我的目录，我猜测这个插件的配置文件需要放到项目的根目录下。或者你可以仅仅打开`bcwc`目录试试看。
This is my directory, I guess the configuration file for this plugin needs to be placed in the root of the project. Or you can just try to open the `bcwc` directory.
![image](https://user-images.githubusercontent.com/24603805/43499460-258e58e6-957e-11e8-8415-e72dca8a5c53.png)

**Comment by codesboy** [comment]
@QingCT 只能放到根目录下吗？context这个配置项是做什么的？

**Comment by QingCT** [comment]
@codesboy 配置文件应该只能放根目录吧，`context`我也不太确定。我前两天才用这个插件，只是用来上传单个文件。可能设置了context，你的项目目录就不用完全跟服务器一样了。我觉得这个插件非常好用，为作者点赞，感谢！ @liximomo

**Comment by QingCT** [comment]
@baturorkun 
When I start vscode, I can see my configuration file here. I think you can check it out.
![image](https://user-images.githubusercontent.com/24603805/43503052-3128051e-9590-11e8-810e-63bb329c7e78.png)

**Comment by baturorkun** [comment]
@liximomo my sftp.json in.vscode directory in project dir.

**Comment by baturorkun** [comment]
there is an error:
error] SyntaxError: /Users/batur/Projects/fastlane/.vscode/sftp.json: Unexpected token c in JSON at position 6
	at JSON.parse (<anonymous>)
	at /Users/batur/.vscode/extensions/liximomo.sftp-1.2.8/node_modules/jsonfile/index.js:36:18
	at /Users/batur/.vscode/extensions/liximomo.sftp-1.2.8/node_modules/graceful-fs/graceful-fs.js:78:16
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)

**Comment by QingCT** [comment]
@baturorkun 
Json files cannot have comments.Maybe this is the reason?
![image](https://user-images.githubusercontent.com/24603805/43503920-e817a1aa-9593-11e8-8d5a-019effffa6bc.png)

**Comment by baturorkun** [comment]
yes i know. i tried like this but error again :.(

{
    context: "/Users/batur/Projects/fastlane",
    host: "192.168.1.111",
    port: 22,
    username: "batur",
    password: "******",
    protocol: "sftp"
}

**Comment by baturorkun** [comment]
hahaha
i solved it. :)
json parse error is simple and interesting. 
it is just that double quotes are must for key names

{
    "context": "/Users/batur/Projects/fastlane",
    "host": "192.168.2.112",
    "port": 22,
    "username": "batur",
    "password": "0000000",
    "protocol": "sftp", 
    "remotePath": "/Users/batur/ci/fastlane",
    "uploadOnSave": true
}
