### ISSUE TITLE
sftp使用公钥登录服务器,怎样设置才能提示输入passphrase,不是把passphrase写在sftp.json

### ISSUE THREAD

**Issue by RockYuan** [liximomo/vscode-sftp#251]
## Expected Behavior
提示输入passphrase

## Actual Behavior
不出现提示框

## Steps to Reproduce the Problem

sftp.json
{
    "name"           : "test",
    "protocol"       : "sftp",
    "host"           : "sshname",
    "username"       : "root",
    "remotePath"     : "/data/php/",
    "interactiveAuth": true,
    "ignore"         : [".vscode", "/vendor"]
}

## Requisites (**important to diagnose the problem!**)

[error] Error: All configured authentication methods failed
	at tryNextAuth (/Users/a/.vscode/extensions/liximomo.sftp-1.2.5/node_modules/ssh2/lib/client.js:392:17)
	at SSH2Stream.onUSERAUTH_FAILURE (/Users/a/.vscode/extensions/liximomo.sftp-1.2.5/node_modules/ssh2/lib/client.js:599:5)
	at emitTwo (events.js:106:13)
	at SSH2Stream.emit (events.js:194:7)
	at parsePacket (/Users/a/.vscode/extensions/liximomo.sftp-1.2.5/node_modules/ssh2-streams/lib/ssh.js:3930:10)
	at SSH2Stream._transform (/Users/a/.vscode/extensions/liximomo.sftp-1.2.5/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (/Users/a/.vscode/extensions/liximomo.sftp-1.2.5/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
 

## Specifications

  - Version:1.25.1
  - Platform:osx 10.12

**Comment by liximomo** [comment]
```
"passphrase": true
```
