### ISSUE TITLE
Download is not working on large projects

### ISSUE THREAD

**Issue by eredhyl** [liximomo/vscode-sftp#253]
## Expected Behavior
I want to download a project that is ~200MB between a Linux host and a Windows client.

## Actual Behavior
I get the following error when executing the Download option:

[error] Error: Failure
	at SFTPStream._transform (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)

and nothing gets sync or downloaded.

## Steps to Reproduce the Problem

  1. Configure the SFTP on VSCode to work on a large project (about ~200MB, but I have seen the error on projects about ~150MB as well) 
  2. Perform the sftp:Download command on the root directory for the project
  3. Gets an error pop up window with a message that says only "Failure".

### Extension Logs
  1.  Open User Settings.
      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.printDebugLog` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

[trace] execute download for c:\Users\acsalaza\project
[error] Error: Failure
	at SFTPStream._transform (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (C:\Users\acsalaza\.vscode\extensions\liximomo.sftp-1.2.5\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)

## Specifications

  - Version:
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

  - Platform: Windows 10

**Comment by liximomo** [comment]
[This](https://github.com/mscdex/ssh2/issues/300) may help.

**Comment by eredhyl** [comment]
Thanks! That solved the issue. 

For anyone else encountering this error, I had to increase the limit of open files available in the system, if you are using a systemd system I had to modify the system file "/etc/systemd/system.conf" and set the variable:

DefaultLimitNOFILE=500000
