### ISSUE TITLE
Config File Not Found When Uploading Files In Tree

### ISSUE THREAD

**Issue by skjbulcher** [liximomo/vscode-sftp#26]
SFTP was working (and continues to work in the root folder), but no longer uploads files further down the tree. In the example below, I right-clicked on `migrate.sh` and clicked on upload. sftp always complains `config file not found`, even though (as you can see) the config file is present. Furthermore, I can upload files in the root folder without issue - e.g. `Dockerfile`.

A picture is worth a thousand words:
![image](https://user-images.githubusercontent.com/16672299/30234778-9054b118-94b5-11e7-9389-32ed0dcaddf8.png)

## Steps to Reproduce the Problem

I'm not sure how things got into this state, so I don't know how to reproduce. I did add a second, different config further down the tree, but that one seems to work, and deleting the folder has no effect on the above behavior.

### Extension Logs 
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
```
[error]: context: undefined reason: Error: (c:\Users\JohnBulcher_gb\Documents\Workspace\Docker-Apps\deals-and-conversations\app\migrate.sh) config file not found
	at runTask (C:\Users\JohnBulcher_gb\.vscode\extensions\liximomo.sftp-0.7.9\out\src\helper\createCommand.js:17:19)
	at Array.forEach (native)
	at runTasks (C:\Users\JohnBulcher_gb\.vscode\extensions\liximomo.sftp-0.7.9\out\src\helper\createCommand.js:20:52)
	at getTarget.then.target (C:\Users\JohnBulcher_gb\.vscode\extensions\liximomo.sftp-0.7.9\out\src\helper\createCommand.js:26:9)
	at <anonymous>
```
 

## Specifications

  - Version: sftp 0.7.9
  - Platform: Windows 10

**Comment by liximomo** [comment]
I need the full `sftp` logs.

**Comment by skjbulcher** [comment]
I gave you all of the output from one failed transaction above; are there logs anywhere else?

**Comment by liximomo** [comment]
The initial log of the config info. I need know the real path that the extension find the config file in.

**Comment by skjbulcher** [comment]
```
[info]: config at @workroot {
    "host": "XXX",
    "port": 22,
    "username": "XXX",
    "password": null,
    "protocol": "sftp",
    "agent": null,
    "privateKeyPath": "C:\\Users\\XXX\\.ssh\\id_rsa",
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/home/XXX",
    "uploadOnSave": true,
    "syncMode": "full",
    "watcher": {
        "files": "*",
        "autoUpload": false,
        "autoDelete": true
    },
    "ignore": [
        "c:/Users/XXX/**/.vscode",
        "c:/Users/XXX/**/.git",
        "c:/Users/XXX/**/.DS_Store",
        "c:/Users/XXX/sftp-config/.json",
        "c:/Users/XXX/Thumbs/.db",
        "c:/Users/XXX/desktop/.ini",
        "c:/Users/XXX/**/.gitkeep",
        "c:/Users/XXX/**/.eslintrc.js",
        "/home/XXX/**/.vscode",
        "/home/XXX/**/.git",
        "/home/XXX/**/.DS_Store",
        "/home/XXX/sftp-config/.json",
        "/home/XXX/Thumbs/.db",
        "/home/XXX/desktop/.ini",
        "/home/XXX/**/.gitkeep",
        "/home/XXX/**/.eslintrc.js"
    ],
    "configRoot": "c:/Users/XXX"
}
[info]: config at @workroot/app/src/www {
    "host": "YYY",
    "port": 22,
    "username": "XXX",
    "password": null,
    "protocol": "sftp",
    "agent": null,
    "privateKeyPath": "C:\\Users\\XXX\\.ssh\\id_rsa",
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/XXX",
    "uploadOnSave": true,
    "syncMode": "full",
    "watcher": {
        "files": "*",
        "autoUpload": false,
        "autoDelete": true
    },
    "ignore": [
        "c:/Users/XXX/app/src/www/**/.vscode",
        "c:/Users/XXX/app/src/www/**/.git",
        "c:/Users/XXX/app/src/www/**/.DS_Store",
        "c:/Users/XXX/app/src/www/sftp-config/.json",
        "c:/Users/XXX/app/src/www/Thumbs/.db",
        "c:/Users/XXX/app/src/www/desktop/.ini",
        "c:/Users/XXX/app/src/www/**/.gitkeep",
        "c:/Users/XXX/app/src/www/**/.eslintrc.js",
        "/XXX/_data/**/.vscode",
        "/XXX/_data/**/.git",
        "/XXX/_data/**/.DS_Store",
        "/XXX/_data/sftp-config/.json",
        "/XXX/_data/Thumbs/.db",
        "/XXX/_data/desktop/.ini",
        "/XXX/_data/**/.gitkeep",
        "/XXX/_data/**/.eslintrc.js"
    ],
    "configRoot": "c:/Users/XXX/app/src/www"
}
```
