### ISSUE TITLE
No Such File error on trying sftp:download

### ISSUE THREAD

**Issue by CHShah** [liximomo/vscode-sftp#266]
## Expected Behavior
When right click on a folder/file and click SFTP Download, should download the folder/file

## Actual Behavior
Getting Error "No such File"
Log:
```
[info] config at d:\code\ems {"remotePath":"/home/frappe/frappe-bench/apps/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":4,"protocol":"sftp","host":"127.0.0.1","port":3021,"username":"******","password":"******","connectTimeout":10000,"interactiveAuth":false,"sshConfigPath":"~/.ssh/config","secure":false,"passive":false,"context":"d:\\code\\ems"}
[trace] execute download for d:\code\ems
[error] Error: No such file
	at SFTPStream._transform (C:\Users\chirag\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\chirag\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (C:\Users\chirag\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (C:\Users\chirag\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\chirag\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (C:\Users\chirag\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
```

## Steps to Reproduce the Problem
This happened after I updated VS Code today.
  1. Right click any file / folder in Explorer 
  2. Click SFTP: download

## Specifications

  - Version:
![image](https://user-images.githubusercontent.com/36955513/43584961-808e2df8-9681-11e8-842b-4561e7155c1a.png)
sftp version: 1.3.0
  - Platform: Windows 10 64 bit

**Comment by omgdracula** [comment]
I am also getting this error as well in 1.3.0 on upload of files. Plugin worked perfectly yesterday before update. 

```
[error] Error: No such file
	at SFTPStream._transform (C:\Users\clifm\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\clifm\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (C:\Users\clifm\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (C:\Users\clifm\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\clifm\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (C:\Users\clifm\.vscode\extensions\liximomo.sftp-1.3.0\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20) transfer d:\cei-site-theme\sass\site\primary\_posts-and-pages.scss
```

**Comment by omgdracula** [comment]
Could you provide the 1.2.7.vsix file so we can at least rollback in the meantime?

**Comment by ragokin** [comment]
@omgdracula look in #265  for rollback instructions

**Comment by liximomo** [comment]
Does this still happen in  v1.3.1?

**Comment by Demon-DK** [comment]
Nope, in my case update to 1.3.1 has resolved the issue.

**Comment by CHShah** [comment]
Same, it is now working in 1.3.1.

**Comment by jgoux** [comment]
Hello, I have the exact same issue using the brand new 1.4.0 version.

```
[error] Error: No such file
	at SFTPStream._transform (/home/jgoux/.vscode-insiders/extensions/liximomo.sftp-1.4.0/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (/home/jgoux/.vscode-insiders/extensions/liximomo.sftp-1.4.0/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (/home/jgoux/.vscode-insiders/extensions/liximomo.sftp-1.4.0/node_modules/ssh2/lib/Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (/home/jgoux/.vscode-insiders/extensions/liximomo.sftp-1.4.0/node_modules/ssh2-streams/lib/ssh.js:3445:10)
	at SSH2Stream._transform (/home/jgoux/.vscode-insiders/extensions/liximomo.sftp-1.4.0/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (/home/jgoux/.vscode-insiders/extensions/liximomo.sftp-1.4.0/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20)
```

**Comment by JamzumSum** [comment]
I've got a similar issue of **"No such file"** when uploading files. But the file is **successfully synced in fact**.

vscode version: 1.56.0
sftp plugin version: 1.12.9

No such issue when using previous vscode version(1.55.*)

The exception logs are quite similar as those above:
~~~
[05-07 10:49:32] [error] Error: No such file
	at SFTPStream._transform (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
	at SFTPStream._read (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
	at Channel.ondata (internal/streams/readable.js:719:22)
	at Channel.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Channel.Readable.push (internal/streams/readable.js:223:10)
	at SSH2Stream.<anonymous> (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\Channel.js:167:15)
	at SSH2Stream.emit (events.js:315:20)
	at parsePacket (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:3288:10)
	at SSH2Stream._transform (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:694:13)
	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
	at SSH2Stream._read (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
	at Socket.ondata (internal/streams/readable.js:719:22)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote e:\Desktop\PROJNAME\src\test.py
~~~

**Comment by initv0** [comment]
Any solution yet?

**Comment by dotgreg** [comment]
> I've got a similar issue of **"No such file"** when uploading files. But the file is **successfully synced in fact**.
> 
> vscode version: 1.56.0
> sftp plugin version: 1.12.9
> 
> No such issue when using previous vscode version(1.55.*)
> 
> The exception logs are quite similar as those above:
> 
> ```
> [05-07 10:49:32] [error] Error: No such file
> 	at SFTPStream._transform (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:412:27)
> 	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
> 	at SFTPStream._read (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
> 	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
> 	at writeOrBuffer (internal/streams/writable.js:358:12)
> 	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
> 	at Channel.ondata (internal/streams/readable.js:719:22)
> 	at Channel.emit (events.js:315:20)
> 	at addChunk (internal/streams/readable.js:309:12)
> 	at readableAddChunk (internal/streams/readable.js:284:9)
> 	at Channel.Readable.push (internal/streams/readable.js:223:10)
> 	at SSH2Stream.<anonymous> (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\Channel.js:167:15)
> 	at SSH2Stream.emit (events.js:315:20)
> 	at parsePacket (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:3288:10)
> 	at SSH2Stream._transform (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:694:13)
> 	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
> 	at SSH2Stream._read (c:\Users\Johnson\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
> 	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
> 	at writeOrBuffer (internal/streams/writable.js:358:12)
> 	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
> 	at Socket.ondata (internal/streams/readable.js:719:22)
> 	at Socket.emit (events.js:315:20)
> 	at addChunk (internal/streams/readable.js:309:12)
> 	at readableAddChunk (internal/streams/readable.js:284:9)
> 	at Socket.Readable.push (internal/streams/readable.js:223:10)
> 	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote e:\Desktop\PROJNAME\src\test.py
> ```

Same error here, the upload is proceeded but in my case, the upload is corrupted. List works fine as well.

[05-07 10:52:12] [error] Error: No such file
	at SFTPStream._transform (c:\Users\grego\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
	at SFTPStream._read (c:\Users\grego\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
	at Channel.ondata (internal/streams/readable.js:719:22)
	at Channel.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Channel.Readable.push (internal/streams/readable.js:223:10)
	at SSH2Stream.<anonymous> (c:\Users\grego\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\Channel.js:167:15)
	at SSH2Stream.emit (events.js:315:20)
	at parsePacket (c:\Users\grego\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:3288:10)
	at SSH2Stream._transform (c:\Users\grego\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:694:13)
	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
	at SSH2Stream._read (c:\Users\grego\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
	at Socket.ondata (internal/streams/readable.js:719:22)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote c:\Users\grego\XX\XX\XX\index.js

**Comment by linobino1** [comment]
I'm having the exact same issue as @dotgreg here on Mac OS 11.3 - thanks for mentioning that the upload still works;)

**Comment by nelsonfernandes-kk** [comment]
Same issue here but as you say the sync is working just fine.

SFTP Extension:v 1.12.9 

VS Code:
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by jfpaulin** [comment]
Same issue here but even the uploads are not working on my end.

**Comment by alimify** [comment]
same issue here..

**Comment by Tvs-Frank** [comment]
VS Code:
-----------------------------------
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-72-generic

Output:
-----------------------------------
[05-07 09:07:40] [error] Error: No such file
    at SFTPStream._transform (/home/chupa/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
    at SFTPStream._read (/home/chupa/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
    at Channel.ondata (internal/streams/readable.js:719:22)
    at Channel.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Channel.Readable.push (internal/streams/readable.js:223:10)
    at SSH2Stream.<anonymous> (/home/chupa/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:315:20)
    at parsePacket (/home/chupa/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:3288:10)
    at SSH2Stream._transform (/home/chupa/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:694:13)
    at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
    at SSH2Stream._read (/home/chupa/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote /media/[..omitted...]/customize.html

The local/remote save is successful in my case.

**Comment by ggbouz** [comment]
Same issue, "No such file"

**Comment by maorodribu** [comment]
Same issue, "No such file"

Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.11.1-amd64-desktop

**Comment by ariannelafraise** [comment]
I believe this comes from the 1.56.0 version of VS code. I downgraded to 1.55.2 and it now works. 
https://code.visualstudio.com/updates/v1_55

EDIT: And disable auto-updates on VS code so that it won't go back to 1.56.0 by itself :)

**Comment by techlegends** [comment]
Same issue as above commenters. Downgrading to VS code v1.55.2 as above commenter to get working for now.

**Comment by mpinto1991** [comment]
same thing here... .downgrading was the only solution that works for me right now.

**Comment by flashzxi** [comment]
> I believe this comes from the 1.56.0 version of VS code. I downgraded to 1.55.2 and it now works.
> https://code.visualstudio.com/updates/v1_55

In fact， I tried your solution and resolved the question. But then I installed an extension called "Latex Workshop" and compiled my document, then the same question show up again! There must be something wrong with "Latex Workshop"

**Comment by Coding-Kiwi** [comment]
Same issue here

**Comment by ariannelafraise** [comment]
> 
> 
> Same issue here



> 
> 
> I believe this comes from the 1.56.0 version of VS code. I downgraded to 1.55.2 and it now works.
> https://code.visualstudio.com/updates/v1_55

**Comment by jan-klima** [comment]
Same happening here. Win 10 x64, started on 1.56.0. Downgrade to 1.55.2 works OK.

**Comment by max-rosenfors** [comment]
Same issue, the file is saved but a notification that it failed pops up. On Ubuntu and running snap "latest/stable: cfa2e218 2021-05-05", i.e:

Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-50-generic snap

**Comment by kobebeef** [comment]
Same here. Running 
VS Code 1.56.0 on macOS
liximomo.sftp v1.12.9

**Comment by matusko89** [comment]
Same here, downgrate worked

**Comment by zeqjone** [comment]
me too. go files upload success，but can't be compiled.

Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by rob-watts** [comment]
Same here, downgrade worked.

**Comment by Coding-Kiwi** [comment]
Guys lets stop adding more "same here, downgrade worked" comments..

The new actually relevant issue is #919

Also: lets face it, this project seems abandoned, the last commit is 2 years old.
The actual problem / bug is in the **ssh2-streams** library, which I think also won't get any updates, like the author mentioned:

> The upcoming release doesn't use ssh2-streams anymore so it won't be an issue.

> The choices at the moment are: try the current master branch as that is where development is focused or use a fork of ssh2 v0.8.x with the changes you need.

**Comment by JamzumSum** [comment]
Seems a solution without downgrading [here](https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635).

**Comment by dekura** [comment]
> > I believe this comes from the 1.56.0 version of VS code. I downgraded to 1.55.2 and it now works.
> > https://code.visualstudio.com/updates/v1_55
> 
> In fact， I tried your solution and resolved the question. But then I installed an extension called "Latex Workshop" and compiled my document, then the same question show up again! There must be something wrong with "Latex Workshop"

same issue here.

**Comment by MarkJiYuan** [comment]
I'm intresting about why new version of VScode can cause this problem. Definetely, vscode-sftp plugin are not to blame. Does same problem will happen to other plugins? Or will it repeat in the future?

**Comment by stanfieldr** [comment]
should this issue be opened back up? Or should a new issue be opened since this goes all the way back to 2018?

**Comment by Natizyskunk** [comment]
I've made a pull request on ssh2-streams repo to (temporary) fix this error : https://github.com/mscdex/ssh2-streams/pull/174

**Comment by yuanAIhan** [comment]
> Any solution yet?

You can try to install the previous version of vs code, the latest version 1.56.0 does not work, and fall back to 1.55.2 to solve the problem

**Comment by locvfx** [comment]
Hell no ..
This issue happens again today May 16 2021 after updated VS Code!

**Comment by reidsneo** [comment]
The issue occurred in current latest vscode
![image](https://user-images.githubusercontent.com/12298979/118385472-aefedd80-b641-11eb-978a-dcf67c233179.png)

Also when doing sync folder up / down, it will cause the destination files corrupted!!

**Comment by seddik** [comment]
This worked for me without downgrading 

https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635

Nice - thanks @sdir. Guess I could have figured that if I thought about it.

So to sum up all the above as TLDR for others skimming this thread:

Do a search inside `~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js`
for options.emitClose = false;

Add `options.autoDestroy = false;` after both instances.

**Comment by vithd** [comment]
> This worked for me without downgrading
> 
> [#919 (comment)](https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635)
> 
> Nice - thanks @sdir. Guess I could have figured that if I thought about it.
> 
> So to sum up all the above as TLDR for others skimming this thread:
> 
> Do a search inside `~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js`
> for options.emitClose = false;
> 
> Add `options.autoDestroy = false;` after both instances.

It worked! Thank you so much!!!

**Comment by Jackettt** [comment]
Editing the file:
~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js
change the line 388:
if (code === STATUS_CODE.OK) {
to:
if (code === STATUS_CODE.OK || code === STATUS_CODE.NO_SUCH_FILE) {
Reload vscode
It is not the most correct option but it works.

**Comment by gstvux** [comment]
> This worked for me without downgrading
> 
> [#919 (comment)](https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635)
> 
> Nice - thanks @sdir. Guess I could have figured that if I thought about it.
> 
> So to sum up all the above as TLDR for others skimming this thread:
> 
> Do a search inside `~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js`
> for options.emitClose = false;
> 
> Add `options.autoDestroy = false;` after both instances.

IT WORK MODERFOKER!!!! THANKYOU!!!!

**Comment by infernusec** [comment]
> This worked for me without downgrading
> 
> [#919 (comment)](https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635)
> 
> Nice - thanks @sdir. Guess I could have figured that if I thought about it.
> 
> So to sum up all the above as TLDR for others skimming this thread:
> 
> Do a search inside `~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js`
> for options.emitClose = false;
> 
> Add `options.autoDestroy = false;` after both instances.

ITS WORKING ! Thank you So much!

**Comment by vikicoder007** [comment]
> > This worked for me without downgrading
> > [#919 (comment)](https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635)
> > Nice - thanks @sdir. Guess I could have figured that if I thought about it.
> > So to sum up all the above as TLDR for others skimming this thread:
> > Do a search inside `~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js`
> > for options.emitClose = false;
> > Add `options.autoDestroy = false;` after both instances.
> 
> ITS WORKING ! Thank you So much!

Solution works for me

**Comment by Natizyskunk** [comment]
Just use my version that implement the new ssh2 v1.1.0 version that fix every problem 🙂 https://github.com/Natizyskunk/vscode-sftp/releases

**Comment by seifer7** [comment]
This works for me also! Thank you.

https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635
> **So to sum up all the above as TLDR for others skimming this thread:**
> 
> 1. Do a search inside `~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js`
>    for  `options.emitClose = false;`
> 2. Add `options.autoDestroy = false;` after both instances.

**Comment by realasmo** [comment]
> Just use my version that implement the new ssh2 v1.1.0 version that fix every problem 🙂 https://github.com/Natizyskunk/vscode-sftp/releases

Thank you for your fork, this resolved the issue and I can see your fork is actively maintained, I'm using it from now on!
