### ISSUE TITLE
Windows -> Unix uploads to fail

### ISSUE THREAD

**Issue by tmcdonnell87** [liximomo/vscode-sftp#273]
## Expected Behavior
File transfer from Windows to Unix-based system places files into expected relative directories. For example, if the remote is `dir`, a file `foo.txt` in `dir` would be uploaded to the remote server as `dir/foo.txt`

This appears to be a regression with version 1.3.3.
## Actual Behavior
File transfer from Windows to Unix creates files with the string path `\dir\foo`. Note this is NOT a sub-directory, it is a file path. 

Alternatively, it returns a permission denied error. 
## Steps to Reproduce the Problem
Create workspace on Windows computer. Configure remote that uses unix-based paths. 

### Extension Logs
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.printDebugLog` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
 
[trace] execute sync to remote for c:\Users\terry\Agathos\db-manager
[error] Error: Permission denied
	at SFTPStream._transform (C:\Users\terry\.vscode\extensions\liximomo.sftp-1.3.3\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\terry\.vscode\extensions\liximomo.sftp-1.3.3\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (C:\Users\terry\.vscode\extensions\liximomo.sftp-1.3.3\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (C:\Users\terry\.vscode\extensions\liximomo.sftp-1.3.3\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\terry\.vscode\extensions\liximomo.sftp-1.3.3\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (C:\Users\terry\.vscode\extensions\liximomo.sftp-1.3.3\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)

## Specifications

  - Version: 1.3.3
  - Platform: Windows 10 (uploading to Ubuntu 16.4)

**Comment by liximomo** [comment]
Sorry about that. Try v1.3.4

**Comment by bryjch** [comment]
I'm experiencing the same problem still with v1.3.5.

Same specs as tmcdonnell87, running Windows 10 and uploading to Ubuntu 16.4; tried running VSCode as admin to no avail either.

**Comment by liximomo** [comment]
@bryjch  How can I reproduce the problem? I need more specific info. (platform, directory structure, file path)

**Comment by st3ph** [comment]
Got the same issue after upgrading the plugin, going back to v1.3.1 and it works

To reproduce the issue:
- Connect to remote sftp and browse to a file you want to edit
- Right click => Edit in local
- Got an error "No Such File"

**Comment by liximomo** [comment]
@st3ph Does it fix in v1.3.6

**Comment by st3ph** [comment]
Seems good, thank you !
