### ISSUE TITLE
SFTP : Sync To Local Not working

### ISSUE THREAD

**Issue by pogus55** [liximomo/vscode-sftp#275]
[error] TypeError: Cannot read property 'resourceUri' of undefined
	at FileCommand.selectFolderFallbackToConfigContext [as getFileTarget] (C:\Users\PC\.vscode\extensions\liximomo.sftp-1.3.4\out\src\modules\targetSelectStrategy.js:130:18)
	at FileCommand.<anonymous> (C:\Users\PC\.vscode\extensions\liximomo.sftp-1.3.4\out\src\commands\FileCommand.js:30:39)
	at Generator.next (<anonymous>)
	at C:\Users\PC\.vscode\extensions\liximomo.sftp-1.3.4\out\src\commands\FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\PC\.vscode\extensions\liximomo.sftp-1.3.4\out\src\commands\FileCommand.js:3:12)
	at FileCommand.run (C:\Users\PC\.vscode\extensions\liximomo.sftp-1.3.4\out\src\commands\FileCommand.js:29:16)
	at FileCommand.<anonymous> (C:\Users\PC\.vscode\extensions\liximomo.sftp-1.3.4\out\src\commands\BaseCommand.js:39:28)
	at Generator.next (<anonymous>)
	at C:\Users\PC\.vscode\extensions\liximomo.sftp-1.3.4\out\src\commands\BaseCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\PC\.vscode\extensions\liximomo.sftp-1.3.4\out\src\commands\BaseCommand.js:3:12)
	at FileCommand._commandHandler (C:\Users\PC\.vscode\extensions\liximomo.sftp-1.3.4\out\src\commands\BaseCommand.js:37:16)
	at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:697:706)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:698:212)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:87)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:779)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:851)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:620)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
	at u (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)

**Comment by liximomo** [comment]
What have you done?

**Comment by pogus55** [comment]
1. SFTP : Config
2. SFTP : DownLoad
3. create new file...
4. SFTP : Sync To Local

not working Sync to Local.

It's all.

**Comment by liximomo** [comment]
Fix in v1.3.5.

**Comment by pogus55** [comment]
thank you!!
