### ISSUE TITLE
Permission denied when uploading and downloading files

### ISSUE THREAD

**Issue by mattb-af** [liximomo/vscode-sftp#279]
## Expected Behavior
File to be uploaded to remote server

## Actual Behavior
Permission denied error when uploading file

## Steps to Reproduce the Problem

  1. Set up config file with sftp details
  2. Run SFTP: Upload on a file

### Extension Logs
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.printDebugLog` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

[error] Error: Permission denied
	at SFTPStream._transform (/home/***/.vscode/extensions/liximomo.sftp-1.3.5/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (/home/***/.vscode/extensions/liximomo.sftp-1.3.5/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (/home/***/.vscode/extensions/liximomo.sftp-1.3.5/node_modules/ssh2/lib/Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (/home/***/.vscode/extensions/liximomo.sftp-1.3.5/node_modules/ssh2-streams/lib/ssh.js:3445:10)
	at SSH2Stream._transform (/home/***/.vscode/extensions/liximomo.sftp-1.3.5/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (/home/***/.vscode/extensions/liximomo.sftp-1.3.5/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)

 

## Specifications

  - Version: 1.3.5
  - Platform: Ubuntu 18.04 bionic x86_64 Linux 4.15.0-29-generic

**Comment by apointeau** [comment]
Hi, I have the same issue on my laptop since few minutes

**Comment by mattb-af** [comment]
Temporary solution has worked for me

**Comment by liximomo** [comment]
@mattb-af How can I reproduce the problem? I need more specific info. (platform, directory structure, file path)

**Comment by tanzhihang** [comment]
I seem to have found the reason. I changed the remote path to an absolute path, and it works

**Comment by mattb-af** [comment]
@liximomo I put the platform and version in the issue description and a log off all the output i got of the failure. I can give you the config info:

[info] config at /home/***/Documents/work/sites/***.org {"remotePath":"./","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":[],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":4,"protocol":"sftp","host":"***.com","port":22,"username":"******","password":"******","connectTimeout":10000,"interactiveAuth":false,"sshConfigPath":"~/.ssh/config","secure":false,"passive":false,"context":"/home/***/Documents/work/sites/***.org"}

**Comment by boeningc** [comment]
Update to 1.3.6 seems to correct the issue.  I removed my absolute path and it's working again.  :)

**Comment by apointeau** [comment]
Thanks @liximomo  for the quick fix, v1.3.6 & v1.3.7 work well !

**Comment by lou1swu** [comment]
I have the same issue and resolve at the end.
Caused by the user your set in sftp.json has no enough permission to **mkdir**.
You could use **chown -R \<username\>:\<group\> \<remotePath\>** on the remote server. It wil work.

**Comment by fahadjabbar8** [comment]
@Lighting-Jack Thanks worked for me
