### ISSUE TITLE
425 Unable to build data connection: Operation not permitted

### ISSUE THREAD

**Issue by tobiasnehfischer** [liximomo/vscode-sftp#302]
## Expected Behavior
I want to upload a single file to my remote server.

## Actual Behavior
Upload doesn't work. Error: [error] Error: Unable to build data connection: Operation not permitted.
Upload with Filezilla or WinSCP works. So server side is ok, I think.
Server uses proFtp.
TLSOptions NoSessionReuseRequired is set

### Extension Logs
[trace] execute upload for z:\vindur cms\xxxxx.com\htdocs\testtest
[debug] > PASV
[debug] < 227 Entering Passive Mode (78,46,252,5,231,12).
[debug] > LIST /xxxxx.com
[debug] < 150 Opening BINARY mode data connection for file list
[debug] < 226 Transfer complete
[debug] > PASV
[debug] < 227 Entering Passive Mode (78,46,252,5,166,10).
[debug] > STOR /xxxxx.com/htdocs/testtest
[debug] < 150 Opening BINARY mode data connection for /xxxxx.com/htdocs/testtest
[debug] < 425 Unable to build data connection: Operation not permitted
[error] Error: Unable to build data connection: Operation not permitted
	at makeError (C:\Users\Tobias\.vscode\extensions\liximomo.sftp-1.2.7\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> (C:\Users\Tobias\.vscode\extensions\liximomo.sftp-1.2.7\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:126:13)
	at Parser.emit (events.js:214:7)
	at Parser._write (C:\Users\Tobias\.vscode\extensions\liximomo.sftp-1.2.7\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at Parser.Writable.write (_stream_writable.js:290:11)
	at TLSSocket.ondata (C:\Users\Tobias\.vscode\extensions\liximomo.sftp-1.2.7\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:116:13)
	at TLSSocket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:246:13)
	at TLSSocket.Readable.push (_stream_readable.js:208:10)
	at TLSWrap.onread (net.js:594:20) transfer z:\vindur cms\xxxxx.com\htdocs\testtest
[info] transfer z:\vindur cms\xxxxx.com\htdocs\testtest

  ### sftp.jpson
{
    "protocol": "ftp",
    "host": "xxx.xxx.xxx.xxx",
    "port": 21,
    "username": "myusername",
    "password": "password",
    "remotePath": "/xxxxxx.com/htdocs",
    "secure": true,
    "secureOptions": {
        "rejectUnauthorized": false
    },
    "passive": true,
    "ignore": [
        ".vscode",
        ".git",
        ".DS_Store",
        ".ftpconfig",
        "sftp-config.json"
      ]
}

## Specifications

  - Version: 1.4.0. Also tried 1.2.7
  - Platform: Windows 10 Enterprise 64bit

**Comment by Ray-works** [comment]
It's been a while and problem still exists. I figured it out:
Upload fails, when file content is empty. Having at least a single char fixes the issue. Will it ever get fixed?

**Comment by ghost** [comment]
@Ray-works I hope so.  I'm adding this to the [backlog](https://github.com/thompsbrian/vscode-sftp-revived/projects/1).

**Comment by danielsawan** [comment]
Hello,

I’d like to report that this bug is still present in the current version. Despite applying the recommended settings, I continue to encounter the following errors when creating or uploading files:

```
SYST DEBUG touch::backend 'unexpected response: 425-Unable to build data connection: Operation not permitted'
HTTP 500 POST 1762.5ms /api/files/touch?path=%2Frgrgr
```

The behavior remains the same as previously described, and the issue hasn’t been resolved with the proposed solutions. If needed, I can provide a testing environment to help investigate and fix this bug.

Thank you for your attention and assistance.  

Best regards,
