### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by huawei-cpts** [liximomo/vscode-sftp#305]
## Expected Behavior
try to download some file.  It was working well before. It was OK  with version 1.3.9.

## Actual Behavior
Now I have got an error: All configured authentication methods failed

## Steps to Reproduce the Problem

1.When  the extension update to 1.4.0 automatically.
2.reload the window.
3.try download a file.

### Extension Logs
[info] config at d:\workspace\project_src\CPTS\staas_workspace\staas {"remotePath":"/home/lyra/workspace/staas","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store",".gitignore","**/third_part/**","**/bin/**","**/obj/**","**/pbobj/**","**/*.o","staas.cbp","staas.depend","staas.layout","staas.sln","staas.user","staas.vcxproj","build.sh","staas.vcxproj.filters"],"watcher":{"files":"src/**/*.cpp","autoUpload":false,"autoDelete":false},"concurrency":4,"protocol":"sftp","host":"100.106.236.100","port":22,"username":"******","password":"******","connectTimeout":10000,"privateKeyPath":"C:\\Users\\wWX444951\\.ssh\\id_rsa","interactiveAuth":false,"sshConfigPath":"~/.ssh/config","secure":false,"passive":false,"context":"d:\\workspace\\project_src\\CPTS\\staas_workspace\\staas"}
[trace] execute download for d:\workspace\project_src\CPTS\staas_workspace\staas\pbsrc
[error] Error: [100.106.236.100]: All configured authentication methods failed
	at Client.client.on.on.err (C:\Users\wWX444951\.vscode\extensions\liximomo.sftp-1.4.0\out\src\core\Client\SFTPClient.js:133:28)
	at emitOne (events.js:121:20)
	at Client.emit (events.js:211:7)
	at tryNextAuth (C:\Users\wWX444951\.vscode\extensions\liximomo.sftp-1.4.0\node_modules\ssh2\lib\client.js:394:12)
	at SSH2Stream.onUSERAUTH_FAILURE (C:\Users\wWX444951\.vscode\extensions\liximomo.sftp-1.4.0\node_modules\ssh2\lib\client.js:599:5)
	at emitTwo (events.js:126:13)
	at SSH2Stream.emit (events.js:214:7)
	at parsePacket (C:\Users\wWX444951\.vscode\extensions\liximomo.sftp-1.4.0\node_modules\ssh2-streams\lib\ssh.js:3930:10)
	at SSH2Stream._transform (C:\Users\wWX444951\.vscode\extensions\liximomo.sftp-1.4.0\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (C:\Users\wWX444951\.vscode\extensions\liximomo.sftp-1.4.0\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20)
 

## Specifications

  - Version:  1.4.0
  - Platform: Windows 7

**Comment by liximomo** [comment]
Please try [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by huawei-cpts** [comment]
Fine, it works.

**Comment by liximomo** [comment]
v1.4.1 has been published.
