### ISSUE TITLE
File upload from local is failing with empty message

### ISSUE THREAD

**Issue by jonbrew1** [liximomo/vscode-sftp#319]
## Expected Behavior
Error message presented on failure for upload

## Actual Behavior
<img width="491" alt="screenshot 2018-09-17 21 53 49" src="https://user-images.githubusercontent.com/10734193/45659874-72f7d100-bac4-11e8-81a2-cfc6b5fbce84.png">

## Steps to Reproduce the Problem
1. Connect to local
2. Click "edit on local"
3. edit the file
4. Click upload
5. unable to upload

config:

```
{
    "protocol": "sftp",
    "name": "name",
    "host": "host",
    "context": "/local/workspace",
    "port": 22,
    "username": "username",
    "privateKeyPath": "---",
    "remotePath": "/remove/workspace",
    "watcher": {
        "files": "*",
        "autoUpload": true,
        "autoDelete": false
    }
}
```

## Requisites (**important to diagnose the problem!**)
[trace] run command 'Upload File'
[trace] handle upload file for /local/file
[trace] transfer from /local/file to /remote/file
[error] Error: Failure
	at SFTPStream._transform (/Users/.vscode/extensions/liximomo.sftp-1.5.5/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (/Users/.vscode/extensions/liximomo.sftp-1.5.5/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (/Users/.vscode/extensions/liximomo.sftp-1.5.5/node_modules/ssh2/lib/Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (/Users/.vscode/extensions/liximomo.sftp-1.5.5/node_modules/ssh2-streams/lib/ssh.js:3445:10)
	at SSH2Stream._transform (/Users/.vscode/extensions/liximomo.sftp-1.5.5/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (/Users/.vscode/extensions/liximomo.sftp-1.5.5/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20)

 

## Specifications

  - Version: 1.5.5
  - Platform: macOS

**Comment by jonbrew1** [comment]
Thank you for the quick reply. I really appreciate it. I will give this a try when I get a chance. Thank you!
