### ISSUE TITLE
how to upload one file use hot key ?

### ISSUE THREAD

**Issue by wicowen** [liximomo/vscode-sftp#323]
## Expected Behavior
Hi , after update my vscode and sftp plugin, 
the 'sftp.trans.remote' cant find on 'keyboard shortcuts', 
so i change bind key to 'sftp.upload.file', 
but get a error 'Cannot read property 'resource' of undefined'.
how can i get this usually function back ?
Thanks

here is some log file for debug
sftp.json

```
{
    "protocol": "sftp",
    "host": "11.22.33.44",
    "username": "username",
    "privateKeyPath": "~/somewhere/key.pem",
    "remotePath": "/home/somewhere"
}
```

Error log
```
[trace] run command 'Upload File'
[error] TypeError: Cannot read property 'resource' of undefined
    at Object.uriFromExplorerContextOrEditorContext [as getFileTarget] (/Users/user/.vscode/extensions/liximomo.sftp-1.5.7/out/src/commands/shared.js:93:19)
    at FileCommand.<anonymous> (/Users/user/.vscode/extensions/liximomo.sftp-1.5.7/out/src/commands/abstract/createCommand.js:46:52)
    at Generator.next (<anonymous>)
    at /Users/user/.vscode/extensions/liximomo.sftp-1.5.7/out/src/commands/abstract/createCommand.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user/.vscode/extensions/liximomo.sftp-1.5.7/out/src/commands/abstract/createCommand.js:3:12)
    at FileCommand.doCommandRun (/Users/user/.vscode/extensions/liximomo.sftp-1.5.7/out/src/commands/abstract/createCommand.js:45:20)
    at FileCommand.<anonymous> (/Users/user/.vscode/extensions/liximomo.sftp-1.5.7/out/src/commands/abstract/command.js:29:28)
    at Generator.next (<anonymous>)
    at /Users/user/.vscode/extensions/liximomo.sftp-1.5.7/out/src/commands/abstract/command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user/.vscode/extensions/liximomo.sftp-1.5.7/out/src/commands/abstract/command.js:3:12)
    at FileCommand.run (/Users/user/.vscode/extensions/liximomo.sftp-1.5.7/out/src/commands/abstract/command.js:26:16)
    at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:726:706)
    at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:727:212)
    at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
    at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
    at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
    at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
    at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
    at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

```

## Actual Behavior
upload one file that editing

## Specifications

  - Version: vscode 1.27.2, plugin 1.5.7
  - Platform: mac 10.13.6

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp/blob/master/CHANGELOG.md#breaking-changes

**Comment by wicowen** [comment]
hi liximomo, thanks for reply, 
and sorry for i'm not notice the #breaking-changes

**Comment by ikheu** [comment]
> https://github.com/liximomo/vscode-sftp/blob/master/CHANGELOG.md#breaking-changes

哈喽，那有没有办法设置【上传当前文件】的快捷键呢，试了半天没有成功。

**Comment by liximomo** [comment]
@ikheu  
```
{
    "key": "ctrl+shift+u",
    "command": "sftp.upload.activeFile"
}
```
