### ISSUE TITLE
如何使用FTP协议连接？

### ISSUE THREAD

**Issue by cooper1x** [liximomo/vscode-sftp#329]
我这边用默认的SFTP协议无法连接到远程服务器，只有FTP可以，请问怎么操作呢？

## Specifications

  - Version:1.5.8
  - Platform:Windows 10 1803 X64

**Comment by liximomo** [comment]
```
{
    "protocol": "ftp"
}
```

**Comment by cooper1x** [comment]
```
[info] config at c:\phpStudy\PHPTutorial\WWW\shuxindemo {"remotePath":"/q1/2018/demos/shuxindemo","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store","**/.psd","**/.rar"],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":true,"secure":false,"passive":false,"port":22,"host":"106.14.194.253","username":"******","password":"******","agent":null,"privateKeyPath":null,"passphrase":null,"watcher":{"files":"glob","autoUpload":true,"autoDelete":true}}
[trace] run command 'Upload File'
[trace] handle upload file for c:\phpStudy\PHPTutorial\WWW\shuxindemo\index.html
[error] Error: connect ECONNREFUSED xxx.xxx.xxx.xxx:22
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```
以上是报错信息，不知道什么情况

**Comment by cooper1x** [comment]
上面我改成21端口的，这个错误解决了。但有一个新的问题，我打开debug后发现，有两行是这样的，写的PASV，也就是被动模式，请问怎么开启主动模式呢？
```
[debug] > PASV
[debug] < 227 Entering Passive Mode (172,19,90,88,242,174)
```

**Comment by liximomo** [comment]
目前还不支持主动模式.

**Comment by cooper1x** [comment]
好吧，后续大概什么时候会添加呢，我watch一下你的项目

**Comment by liximomo** [comment]
不确定呢. 需要下游库的支持.

**Comment by cooper1x** [comment]
@liximomo 请问现在支持主动模式了吗？

**Comment by ifmein** [comment]
主动模式需求+1

**Comment by MarsCube** [comment]
主动模式需求+1
