### ISSUE TITLE
List All dialog no longer works after 1.5.8 update.

### ISSUE THREAD

**Issue by WraithKenny** [liximomo/vscode-sftp#330]
## Expected Behavior
List All dialog, which used to be able to download selected file, would still download selected file.

## Actual Behavior
Selecting a file from List All dialog no longer downloads selected file.

## Steps to Reproduce the Problem

  1. Shift + Command + P
  1. "SFTP: List All"
  1. Select target
  1. Select File
  1. Get error "No such file"

### Extension Logs
[error] Error: No such file
    at SFTPStream._transform (/Users/ken/.vscode/extensions/liximomo.sftp-1.5.8/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/Users/ken/.vscode/extensions/liximomo.sftp-1.5.8/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at SSH2Stream.<anonymous> (/Users/ken/.vscode/extensions/liximomo.sftp-1.5.8/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/Users/ken/.vscode/extensions/liximomo.sftp-1.5.8/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/Users/ken/.vscode/extensions/liximomo.sftp-1.5.8/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/Users/ken/.vscode/extensions/liximomo.sftp-1.5.8/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
 

## Specifications

  - Version: 1.5.8
  - Platform: Mac

**Comment by liximomo** [comment]
Fixed in v1.5.9.
