### ISSUE TITLE
connect EPERM 192.168.100.204:222

### ISSUE THREAD

**Issue by maxxer** [liximomo/vscode-sftp#331]
### Extension Logs

```
[info] config at /Users/maxxer/work/server-v2 {"remotePath":"/dati","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"port":222,"host":"192.168.100.204","username":"******","privateKeyPath":"/Users/maxxer/_support/ssh/id_rsa"}
[error] Error: [192.168.100.204]: connect EPERM 192.168.100.204:222 - Local (0.0.0.0:0)
	at Client.client.on.on.err (/Users/maxxer/.vscode/extensions/liximomo.sftp-1.5.9/out/src/core/remote-client/sshClient.js:163:28)
	at emitOne (events.js:121:20)
	at Client.emit (events.js:211:7)
	at Socket.<anonymous> (/Users/maxxer/.vscode/extensions/liximomo.sftp-1.5.9/node_modules/ssh2/lib/client.js:300:10)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at emitErrorNT (internal/streams/destroy.js:64:8)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
```

## Specifications

  - Version: 1.5.9
  - Platform: macOS 10.14

**Comment by liximomo** [comment]
Check your firewall.
