### ISSUE TITLE
Ampersand character "&" in path not handled correctly

### ISSUE THREAD

**Issue by AndisGrossteins** [liximomo/vscode-sftp#332]
## Expected Behavior
All characters that are legal in path/filenames should be handled correctly. Ampersand "&" is a completely legal character on all modern file systems and OSes. There is a [comprehensive table of allowed characters in filenames on different fie systems on Wikipedia](https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations).

## Actual Behavior
Remote paths containing ampersand character "&" are truncated at the character and results in `Error: No such file`.
For example, a remote path `/home/public_html/q&a/index.php` gets truncated to `/home/public_html/q`.
Uploading the file result in file being uploaded to `/home/public_html/q` which could lead to loss of data in some cases.

## Steps to Reproduce the Problem

  1. Connect to a server containing path with "&" via SFTP;
  1. Try to download a file from path containing "&" (e.g: `/some&file/test`);
  1. Observe error notification `Error: No such file`;

### Extension Logs
```
[trace] run command 'Diff'
[trace] handle diff for C:\Projects\projecty-project\q&a\index.php
[trace] transfer from /home/public_html/q to C:\Users\Andis\AppData\Local\Temp\sftp-13108UAQaelfkSIc1.php
[error] Error: No such file
	at SFTPStream._transform (C:\Users\Andis\.vscode\extensions\liximomo.sftp-1.5.8\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (C:\Users\Andis\.vscode\extensions\liximomo.sftp-1.5.8\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (C:\Users\Andis\.vscode\extensions\liximomo.sftp-1.5.8\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (C:\Users\Andis\.vscode\extensions\liximomo.sftp-1.5.8\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\Andis\.vscode\extensions\liximomo.sftp-1.5.8\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (C:\Users\Andis\.vscode\extensions\liximomo.sftp-1.5.8\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20)
```
 

## Specifications

  - Version: 1.5.8
  - Platform: Windows 10

I'd like to do some more testing with other special characters and different protocols but I don't have time for that right now.

**Comment by liximomo** [comment]
Fixed in v1.5.10.
