### ISSUE TITLE
Sync to Remote: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by samuelT2** [liximomo/vscode-sftp#333]
## Expected Behavior
Sync to remote

## Actual Behavior
Error as soon as I start to sync: Cannot read property 'length' of undefined

Sync to remote has worked for me until yesterday or today-morning. No changes in my sftp.json done. Though, uploadOnSave=true works fine. For testing purposes I cleared my directory and only had one txt-file to upload, same error. Extension uninstalled and re-installed, restarted computer - problem persists.

### sftp.json
`{
    "name": "Deployment",
    "protocol": "ftp",
    "host": "xxx",
    "port": 21,
    "username": "xxx",
    "password": "xxx",
    "ignore": [
        ".vscode",
        "photos",
        ".htaccess",
        "ToDo.txt"
            ],
    "remotePath": "/",
    "syncMode": "full",
    "uploadOnSave": true
}`

  ### Extension Logs
[trace] run command 'Sync To Remote'
[error] TypeError: Cannot read property 'length' of undefined
	at Object.uriFromfspath (C:\Users\samto\.vscode\extensions\liximomo.sftp-1.5.10\out\src\commands\shared.js:87:18)
	at Object.combinedSelector [as getFileTarget] (C:\Users\samto\.vscode\extensions\liximomo.sftp-1.5.10\out\src\commands\shared.js:77:31)
	at FileCommand.<anonymous> (C:\Users\samto\.vscode\extensions\liximomo.sftp-1.5.10\out\src\commands\abstract\createCommand.js:46:52)
	at Generator.next (<anonymous>)
	at C:\Users\samto\.vscode\extensions\liximomo.sftp-1.5.10\out\src\commands\abstract\createCommand.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\samto\.vscode\extensions\liximomo.sftp-1.5.10\out\src\commands\abstract\createCommand.js:3:12)
	at FileCommand.doCommandRun (C:\Users\samto\.vscode\extensions\liximomo.sftp-1.5.10\out\src\commands\abstract\createCommand.js:45:20)
	at FileCommand.<anonymous> (C:\Users\samto\.vscode\extensions\liximomo.sftp-1.5.10\out\src\commands\abstract\command.js:29:28)
	at Generator.next (<anonymous>)
	at C:\Users\samto\.vscode\extensions\liximomo.sftp-1.5.10\out\src\commands\abstract\command.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\samto\.vscode\extensions\liximomo.sftp-1.5.10\out\src\commands\abstract\command.js:3:12)
	at FileCommand.run (C:\Users\samto\.vscode\extensions\liximomo.sftp-1.5.10\out\src\commands\abstract\command.js:26:16)
	at e._executeContributedCommand (c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:726:706)
	at e.$executeContributedCommand (c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:727:212)
	at e._doInvokeHandler (c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
	at e._invokeHandler (c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
	at e._receiveRequest (c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
	at e._receiveOneMessage (c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
	at c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
	at c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
	at e.fire (c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at a (c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
	at Socket._socketDataListener (c:\Dev\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
 

## Specifications

  - Version: Visual Code: 1.27.2, SFTP: 1.5.10
  - Platform: Win10 x64

**Comment by samuelT2** [comment]
Perhaps related to [issue 331](https://github.com/liximomo/vscode-sftp/issues/332) fix?

**Comment by leondmello** [comment]
@samuelT2 If you mean it might have been fixed in that, it hasn't
Facing the same issue myself as well.
Where can I see the plugin logs?

**Comment by samuelT2** [comment]
Nah, not fixed - I meant "bug implemented" :D I can confirm that it worked fine until version 1.5.8, not sure if release 1.5.9 or 1.5.10 broke the extension.

**Comment by medifle** [comment]
Not fixed. I delete a file in remote, and "Sync To Local" or "Sync To Remote" raised this error

**Comment by FinnickWang** [comment]
Same here. When sync to local and sync to remote

**Comment by kapitanluffy** [comment]
same issue here 👍

**Comment by jimlinntu** [comment]
Same issue too. When I use sync to remote

**Comment by duongtx90** [comment]
Same issue. I cannot sync project
`[error] TypeError: Cannot read property 'length' of undefined
	at Object.uriFromfspath (/Users/duongtx/.vscode/extensions/liximomo.sftp-1.5.10/out/src/commands/shared.js:88:18)
	at Object.combinedSelector [as getFileTarget] (/Users/duongtx/.vscode/extensions/liximomo.sftp-1.5.10/out/src/commands/shared.js:77:31)
	at FileCommand.<anonymous> (/Users/duongtx/.vscode/extensions/liximomo.sftp-1.5.10/out/src/commands/abstract/createCommand.js:46:52)
	at Generator.next (<anonymous>)
	at /Users/duongtx/.vscode/extensions/liximomo.sftp-1.5.10/out/src/commands/abstract/createCommand.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/duongtx/.vscode/extensions/liximomo.sftp-1.5.10/out/src/commands/abstract/createCommand.js:3:12)
	at FileCommand.doCommandRun (/Users/duongtx/.vscode/extensions/liximomo.sftp-1.5.10/out/src/commands/abstract/createCommand.js:45:20)
	at FileCommand.<anonymous> (/Users/duongtx/.vscode/extensions/liximomo.sftp-1.5.10/out/src/commands/abstract/command.js:29:28)
	at Generator.next (<anonymous>)
	at /Users/duongtx/.vscode/extensions/liximomo.sftp-1.5.10/out/src/commands/abstract/command.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/duongtx/.vscode/extensions/liximomo.sftp-1.5.10/out/src/commands/abstract/command.js:3:12)
	at FileCommand.run (/Users/duongtx/.vscode/extensions/liximomo.sftp-1.5.10/out/src/commands/abstract/command.js:26:16)
	at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:726:706)
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:727:212)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
`

**Comment by ali-han** [comment]
> Same here. When sync to local and sync to remote

I use "Download Project" instead of "Sync to local". @liximomo please fix it. Your extension is **great**!

**Comment by samuelT2** [comment]
Well, as long as this is not fixed, here's a workaround:
1. Download last version here: https://liximomo.gallery.vsassets.io/_apis/public/gallery/publisher/liximomo/extension/sftp/1.5.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
2. Change the extension from the package from .VSIXPackage to .VSIX
3. Open Visual Code, uninstall SFTP, reload Visual Code
4. Disable auto-update with` "extensions.autoUpdate": false`
5. Press F1 and type VSIX --> "Extension: Install from VSIX..."
6. Reload visual code
7. Voilà, it works again (at least for me)

**Comment by liximomo** [comment]
Fixed in v1.5.11.
