### ISSUE TITLE
sftp Download interrupted

### ISSUE THREAD

**Issue by rolfs42** [liximomo/vscode-sftp#347]
## Expected Behavior
Context menu -> Download: vscode-sftp downloads all files in the configured remote path

## Actual Behavior
Download is interrupted at random time intervals.

## Steps to Reproduce the Problem

  1. Have source on remote host
  1. config sftp.json
  1. Click "Download" in Context-menu

## Requisites (**important to diagnose the problem!**)
Since the problem appears to be network related, it is important to mention that I'm doing this with a remote host that is running Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-92-generic x86_64) on Oracle VirtualBox 5.2.18 on a windows 10 host.

### Extension Logs
[info] config at c:\Users\rolfs\PhpstormProjects\sw18 {"remotePath":"/home/vagrant/www/shopware","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"port":22,"name":"shopware-vagrant","host":"192.168.33.10","username":"******","password":"******"}
[trace] run command 'Download Folder'
[trace] handle download folder for c:\Users\rolfs\PhpstormProjects\sw18
[trace] transfer from /home/vagrant/www/shopware to c:\Users\rolfs\PhpstormProjects\sw18
[error] Error: Failure
	at SFTPStream._transform (C:\Users\rolfs\.vscode\extensions\liximomo.sftp-1.5.13\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (C:\Users\rolfs\.vscode\extensions\liximomo.sftp-1.5.13\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (C:\Users\rolfs\.vscode\extensions\liximomo.sftp-1.5.13\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (C:\Users\rolfs\.vscode\extensions\liximomo.sftp-1.5.13\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\rolfs\.vscode\extensions\liximomo.sftp-1.5.13\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (C:\Users\rolfs\.vscode\extensions\liximomo.sftp-1.5.13\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20)

 

## Specifications

  - Version: vscode-sftp 1.5.13, vscode 1.28.0
  - Platform: windows 10, latest patches

**Comment by liximomo** [comment]
The failure error message comes from the remote side and is more or less the default/generic error message that SSH' sftp server sends when a syscall fails or similar.

To know what exactly is going wrong you could try to enable debug output for the sftp server and then execute your transfers again and see what (if anything) shows up in the logs there.

**Comment by rolfs42** [comment]
Thank you for the quick reply. I upped debugging to debug3 and had a close look but didn't see any errors on the remote side. But maybe I'm using the plugin in the wrong manner? 
The remotePath is the root of a rather large webapplication comprised of 42k files in 20k directories. So in vsc's (initially empty) explorer, I click on "Download Folder" and it actually starts to recreate the directory structure before interrupting with above error. It creates about 14k directories, all of which are empty.
If I hit "Download Folder" on a top-level directory within this root, it reliably downloads all files and subdirectories starting from there.

**Comment by liximomo** [comment]
Maybe your server is run out of file descriptors. Try to increase the file descriptor limit.

**Comment by Cirrith** [comment]
I'm running into this issue too. How do you increase the file descriptor limit?

**Comment by Cirrith** [comment]
Is there a way to fix this on the extension end? I don't have permission to modify the server I'm syncing with

**Comment by liximomo** [comment]
@Cirrith See [limitopenfilesonserver](https://github.com/liximomo/vscode-sftp/wiki/Config#limitopenfilesonserver). This option is available after 1.7.3.
