### ISSUE TITLE
Cannot read property 'delete' of undefined

### ISSUE THREAD

**Issue by kataklys** [liximomo/vscode-sftp#349]
## Expected Behavior

Sync Remote->Local should start syncing

## Actual Behavior

I get the error in the title (Cannot read property 'delete' of undefined)

## Steps to Reproduce the Problem

After the extension upgrade to 1.6, just tried to right click on a directory and use the 'Sync Remote->Local' operation, and I got the error.

### Extension Logs

[error] TypeError: Cannot read property 'delete' of undefined
	at Object.transformOption (/DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/fileHandlers/transfer/index.js:107:39)
	at Object.<anonymous> (/DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/fileHandlers/createFileHandler.js:44:49)
	at Generator.next (<anonymous>)
	at /DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/fileHandlers/createFileHandler.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (/DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/fileHandlers/createFileHandler.js:3:12)
	at Object.fileHandle [as handleFile] (/DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/fileHandlers/createFileHandler.js:40:16)
	at FileCommand.<anonymous> (/DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/commands/abstract/createCommand.js:50:45)
	at Generator.next (<anonymous>)
	at /DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/commands/abstract/createCommand.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (/DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/commands/abstract/createCommand.js:3:12)
	at targetList.map (/DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/commands/abstract/createCommand.js:48:62)
	at Array.map (<anonymous>)
	at FileCommand.<anonymous> (/DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/commands/abstract/createCommand.js:48:49)
	at Generator.next (<anonymous>)
	at fulfilled (/DATE/HD1/D/homedir/.vscode/extensions/liximomo.sftp-1.6.0/out/src/commands/abstract/createCommand.js:4:58)
	at <anonymous>
## Specifications

  - Version: 1.6
  - Platform: Ubuntu 16.04.5 LTS

**Comment by liximomo** [comment]
Fixed in v1.6.1.
