### ISSUE TITLE
Permission denied when local

### ISSUE THREAD

**Issue by YNCBearz** [liximomo/vscode-sftp#350]
## Expected Behavior
Permission denied when local -> remote d:\BEAR\app\Http\Controllers\Discussion\DiscussionController.php

## Actual Behavior
會有錯誤訊息，但仍有作用

## Steps to Reproduce the Problem

  1. 修改檔案.
  2. 存檔

### Extension Logs
[error] Error: Permission denied
	at SFTPStream._transform (C:\Users\bear\.vscode\extensions\liximomo.sftp-1.6.0\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (C:\Users\bear\.vscode\extensions\liximomo.sftp-1.6.0\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (C:\Users\bear\.vscode\extensions\liximomo.sftp-1.6.0\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (C:\Users\bear\.vscode\extensions\liximomo.sftp-1.6.0\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\bear\.vscode\extensions\liximomo.sftp-1.6.0\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (C:\Users\bear\.vscode\extensions\liximomo.sftp-1.6.0\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) Permission denied when local -> remote d:\BEAR\app\Http\Controllers\Discussion\DiscussionController.php
 

## Specifications

  - Version: 1.6.0
  - Platform: Window7

**Comment by liximomo** [comment]
Check your Permission in the server.

**Comment by zenturacp** [comment]
Exact same issue here with my setup - just got this error 1.6.1

The file is uploaded but i get the error

[info] [file-save] XXXX
[error] Error: Permission denied
	at SFTPStream._transform (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) Permission denied when local -> remote XXXXX


File is synced and everything seems to be working just get the error on all saves

Havnt changed any permissions and actually all files are saved on the Server and loaded when i open them

**Comment by liximomo** [comment]
@zenturacp @YNCBearz Please try the [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by zenturacp** [comment]
How do i use the debug packgage? I removed the old and did the code --install-extenstion and i have 1.6.1 installed but i get the same output?

Is there something i should do different?

**Comment by liximomo** [comment]
@zenturacp It looks like you didn't get the debug package installed. I re-published a new  [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge). The version is v1.6.1-debug.

**Comment by zenturacp** [comment]
[info] config at XXXXX {"remotePath":"XX","uploadOnSave":true,"downloadOnOpen":true,"ignore":[".vscode",".git",".DS_Store","composer.*",".composer"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"port":22,"name":"XXX","host":"XXXX","username":"******","password":"******"}
[info] [file-open] XXXXX
[info] remote -> local XXXXX
[info] [file-save] XXXXX
[error] Error: Permission denied
	at SFTPStream._transform (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) Permission denied when local -> remote XXXXX

Now its DEBUG - is it just the Output? or is it a different log?

**Comment by zenturacp** [comment]
By the way - a truely awsome extension 👍 use it every day...

**Comment by zenturacp** [comment]
[info] config at [PATH] {"remotePath":"XXX","uploadOnSave":true,"downloadOnOpen":true,"ignore":[".vscode",".git",".DS_Store","composer.*",".composer"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"port":22,"name":"profile","host":"SERVER","username":"******","password":"******"}
[info] [file-save] [PATH]
[trace] handle upload file for [PATH]
[debug] Local ident: 'SSH-2.0-ssh2js0.2.1'
[debug] Client: Trying SERVER on port 22 ...
[debug] Client: Connected
[debug] Remote ident: 'SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u4'
[debug] Outgoing: Writing KEXINIT
[debug] DEBUG: Comparing KEXINITs ...
[debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[debug] (remote) KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
[debug] KEX algorithm: ecdh-sha2-nistp256
[debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[debug] (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[debug] Host key format: ssh-rsa
[debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[debug] Client->Server Cipher: aes128-ctr
[debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[debug] Server->Client Cipher: aes128-ctr
[debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Client->Server HMAC algorithm: hmac-sha2-256
[debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Server->Client HMAC algorithm: hmac-sha2-256
[debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[debug] Client->Server compression algorithm: none
[debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[debug] Server->Client compression algorithm: none
[debug] Outgoing: Writing KEXECDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing USERAUTH_REQUEST (none)
[debug] Client: none auth failed
[debug] Outgoing: Writing USERAUTH_REQUEST (password)
[debug] Outgoing: Writing CHANNEL_OPEN (0, session)
[debug] Outgoing: Writing CHANNEL_REQUEST (0, subsystem: sftp)
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing MKDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] process transfer task
[debug] Outgoing: Writing WRITE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] process transfer task success
[debug] update modified time
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[error] Error: Permission denied
	at SFTPStream._transform (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (C:\Users\cp\.vscode\extensions\liximomo.sftp-1.6.1-debug\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) Permission denied when local -> remote [PATH]
[trace] run command 'Toggle Output Panel'

**Comment by liximomo** [comment]
It doesn't have enough permission to exec `utime` on the server. From v1.6.0 sftp will set modified time after transfer.

**Comment by zenturacp** [comment]
Okay thats really wierd - yes the USER is NOT owner on the file but i have g+rw and is member of the group - we have like 10 users uploaded on same project.. :(

**Comment by liximomo** [comment]
@zenturacp 

1. ssh to your server. Try `utime` command to the file.
2. Check your server whether it black list `fsetstat` request.

```
Subsystem sftp internal-sftp -P fsetstat
```

**Comment by stefanue** [comment]
Hey @liximomo i have the same issue, but on Mac

**Comment by stefanue** [comment]
@liximomo 

here's the output:

`[info] config at /Users/stefan/SAJTOVI/RTM Dev {"remotePath":"/wp-content/themes/RTM","uploadOnSave":true,"downloadOnOpen":false,"ignore":["**/.vscode/**","**/.git/**","**/.DS_Store","**/.gitignore","**/bower.json","**/composer.json","**/gulpfile.js","**/package-lock.json","**/package.json","**/node_modules/**","**/bower_components/**"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"port":2222,"host":"*******","username":"******","password":"******","syncMode":"update","watcher":{"files":"dist/**","autoUpload":true,"autoDelete":false}}
[info] [file-save] /Users/stefan/SAJTOVI/RTM Dev/assets/css/pages/_custom-development.scss
[trace] handle upload file for /Users/stefan/SAJTOVI/RTM Dev/assets/css/pages/_custom-development.scss
[error] Error: Permission denied
	at SFTPStream._transform (/Users/stefan/.vscode/extensions/liximomo.sftp-1.6.1/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (/Users/stefan/.vscode/extensions/liximomo.sftp-1.6.1/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (/Users/stefan/.vscode/extensions/liximomo.sftp-1.6.1/node_modules/ssh2/lib/Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (/Users/stefan/.vscode/extensions/liximomo.sftp-1.6.1/node_modules/ssh2-streams/lib/ssh.js:3445:10)
	at SSH2Stream._transform (/Users/stefan/.vscode/extensions/liximomo.sftp-1.6.1/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (/Users/stefan/.vscode/extensions/liximomo.sftp-1.6.1/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) Permission denied when local -> remote /Users/stefan/SAJTOVI/RTM Dev/assets/css/pages/_custom-development.scss`

**Comment by stefanue** [comment]
I reverted back to 1.6.0, everything works

to revert back:

disable auto update of extensions
[download the extension](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/liximomo/vsextensions/sftp/1.6.0/vspackage)
install from vsix
reload VS
