### ISSUE TITLE
Error: FileService Not Found.

### ISSUE THREAD

**Issue by F5F5** [liximomo/vscode-sftp#355]
```
[error] Error: FileService Not Found. (file:///e:/work/h/projects/detailShare/fissionRedPkt.html) 
	at C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.6.3\out\src\modules\fileActivityMonitor.js:44:36
	at Generator.next (<anonymous>)
	at C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.6.3\out\src\modules\fileActivityMonitor.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.6.3\out\src\modules\fileActivityMonitor.js:3:12)
	at handleFileSave (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.6.3\out\src\modules\fileActivityMonitor.js:41:12)
	at host_1.onDidSaveTextDocument (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.6.3\out\src\modules\fileActivityMonitor.js:104:9)
	at e.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.$acceptModelSaved (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:586)
	at t._doInvokeHandler (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
	at t._receiveOneMessage (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by F5F5** [comment]
## In the right bar, the connect is success. 
![image](https://user-images.githubusercontent.com/15978277/47083884-938e8480-d244-11e8-8946-b9a82a37fb4d.png)

**Comment by liximomo** [comment]
```
"context": 'h/projects'
```

**Comment by F5F5** [comment]
@liximomo it works on windows.But on mac has same error now without ```context```,i don't konw how to config it. 
QAQ

**Comment by F5F5** [comment]
> @liximomo it works on windows.But on mac has same error now without `context`,i don't konw how to config it.
> QAQ

Mac worked when i restart Vs Code...
