### ISSUE TITLE
Error: failure

### ISSUE THREAD

**Issue by szymoneko** [liximomo/vscode-sftp#356]
Hi,

It's work excellente but after update i've problem:

[error] Error: Failure
	at SFTPStream._transform (***.vscode\extensions\liximomo.sftp-1.6.3\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (***.vscode\extensions\liximomo.sftp-1.6.3\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (***.vscode\extensions\liximomo.sftp-1.6.3\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (***.vscode\extensions\liximomo.sftp-1.6.3\node_modules\ssh2-streams\lib\ssh.js:3445:10)
	at SSH2Stream._transform (***.vscode\extensions\liximomo.sftp-1.6.3\node_modules\ssh2-streams\lib\ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (***.vscode\extensions\liximomo.sftp-1.6.3\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20)

**Comment by szymoneko** [comment]
{
    "protocol": "sftp",
    "host": "127.0.0.1",
    "port": 2222,
    "username": "...",
    "password": "...",
    "remotePath": "...",
    "watcher": {
      "files": "**/*",
      "autoUpload": false,
      "autoDelete": false
    },
    "uploadOnSave": true,
    "syncMode": "full",
    "ignore": [
        "**/.vscode",
        "**/.git",
        "**/.DS_Store"
    ]
}

**Comment by szymoneko** [comment]
It doesn't work. Still the sam error.

> Does this error always happen?
Always, after update.

> Which version? Does it work now? Downgrading Visual Studio Code extension.
Example link:
https://liximomo.gallery.vsassets.io/_apis/public/gallery/publisher/liximomo/extension/sftp/1.5.13/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
Is it ok?

**Comment by szymoneko** [comment]
Ok, I've disabled extension autoupdate options and it's work on 1.5.13 version.
There is a problem o 1.6 version.

**Comment by szymoneko** [comment]
https://pastebin.com/fjtZHq2m

**Comment by liximomo** [comment]
Sorry, can't see any errors.

**Comment by bscript** [comment]
I have the same issues ! it's was workign fine before ! any news ?

**Comment by liximomo** [comment]
@szymoneko @bscript @philipaarseth https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md#error-failure

**Comment by szymoneko** [comment]
But I've go Windows 10

**Comment by philipaarseth** [comment]
@szymoneko ENFILE is a different problem. Look at the one above.

@liximomo I tried setting "limitOpenFilesOnServer" to true, 222, 2, 1, 10, no change.
Error failure still happens on uploadOnSave and upload

https://pastebin.com/mntKqr21
note: one of the failures are because I changed the sftp config to see if I got a different error when my config was wrong, I did, so it's not incorrect host, user & pass.

**Comment by philipaarseth** [comment]
I got it to work. It's part of my hosting file structure, I needed to put the full path, not just "remote-path": "/", but **"remotePath": "/customers/c/4/d/domain.com/httpd.www/",**

@liximomo maybe you could add it as a suggestion in the FAQ 👍

**Comment by aanjaneyam** [comment]
I just installed version I can't get it to work with full remote path too. Always get error failure. It just downloads the folder and not any files.

**Comment by aanjaneyam** [comment]
Ok now it seems to work. After I added syncmode:full, rewrote the remotepath and saved the sftp.json file. I then click Sync remote->local to download all the remote files to local environment. It gets stuck with long sync as nedds password all the time. Is it possible to cache or store the password in the simple config (not profiles).

**Comment by aanjaneyam** [comment]
Ok now it seems to work.  After I added syncmode:full, rewrote the remotepath and saved the sftp.json file. I then click Sync remote->local to download all the remote files to local environment. However, it still gave random error:failure couple of times after the password timed out and I pressed Sync remote->local again to continue the download. And then it started downloading again. It gets stuck with long sync as needs password all the time. Is it possible to cache or store the password in the simple config (not profiles).

**Comment by Eddy805** [comment]
Possible solution:

I had the same issue. As it seemed, my problem was my remotePath `/home/edwin/projects/website` contained a symlink, that was not handled well, resulting in `[error] Error: Failure`. 

Changing the remote path to the actual path the symlink was linking to, `/usr/share/nginx/website` solved this.

**Comment by sebastianjung** [comment]
Yeah we are having the same problem with symlinks here. Strangely using the symlink works for me but not for my colleague. Both same setup:

_Vscode Version
_SFTP Extension Version
_sftp.json file

**Comment by sdir** [comment]
symbolic Link directory ?

**Comment by sebastianjung** [comment]
@sdir Yeah, like so:

"/project-a/public"

where public is the symlink

**Comment by qhsong** [comment]
> Possible solution:
> 
> I had the same issue. As it seemed, my problem was my remotePath `/home/edwin/projects/website` contained a symlink, that was not handled well, resulting in `[error] Error: Failure`.
> 
> Changing the remote path to the actual path the symlink was linking to, `/usr/share/nginx/website` solved this.

I have same issues and change symlink to hard link solve this problem.
But I use symlink directory before, It works. And suddenly, it failed.
Wired.

**Comment by Shaffron** [comment]
In my case

**use symlink path**: some file upload fail
**use absolute path**: everything is all right (until now)

**Comment by srshue** [comment]
I face the same issue. List directory works fine but file upload wont work.

Error: Failure
sftp.js:412
    at SFTPStream._transform (c:\SURESH\vsoncode\NodeCode\algorithmserviceGL\node_modules\ssh2-streams\lib\sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (c:\SURESH\vsoncode\NodeCode\algorithmserviceGL\node_modules\ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)

**Comment by esemlabel** [comment]
I have the same "Error: Failure" issue.
- OS: Mac
- VSCode Version 1.39.2
- Extension Version 1.12.9

config
```
{
	"name": "project",
	"host": "192.168.10.10",
	"protocol": "sftp",
	"port": 22,
	"username": "*****",
	"password": "*****",
	"remotePath": "/opt/applications/project",
	"ignore": [".vscode", ".git", "node_modules", ".DS_Store"],
	"uploadOnSave": false,
	"watcher": {
		"files": "**/*",
		"autoUpload": true,
		"autoDelete": true
	}
}
```

[sftp.log](https://github.com/liximomo/vscode-sftp/files/3739364/sftp.log) (look to the end of file)

**Comment by joaovitordpf** [comment]
Thanks Man! It worked perfectly!

**Comment by clayperez** [comment]
**Possible Culprit: No More Drive Space.**
I found that I was getting this nondescript error because I was out of drive space. I cleared out the runaway logs folder and freed up 40GB of uselessness and power-cycled the server. Problem solved. That is to say that **the issue was not vscode-sftp**, but rather my own carelessness in monitoring my server log consumption.

**Proposal: Enhance error messaging in sftp.js**
Is there a way to capture disc space and report it to the user when there is an error like this?

**Comment by osumko** [comment]
200Gigs free space. So that is not a reason in my case.

**Comment by cloudqubes** [comment]
Had a similar issue. Found the problem to be the "remotePath" was pointing to a symlink on Linux server. When changed to the actual path, problem solved.

**Comment by osumko** [comment]
@cloudqubes, that is not my case. "remotePath" is set to absolute.

**Comment by sergei-beloglazov** [comment]
I have the same issue with symlink in "remotePath". It works only with real path.
Additionally SFTP browser doesn't show symlink directories on server in list.

**Comment by egoan82** [comment]
Good day to all

I had the same problem, but I fixed it with the absolute path.

I also want to indicate that this problem does not occur in subdomains only in the main domain.

Greetings from Colombia co

**Comment by justinvoelker** [comment]
Same `Error: Failure` issue here. This is failing for a brand new React project. Simply create a directory, create a new React app in that directory with `npx create-react-app .` and then try to download that directory into VSCode. The "Error: Failure" appears and only the directory structure is downloaded.

The problem appears to be within the node_modules directory as I am able to download the public and src directories without problem.

I am not out of drive space remotely or locally, my remotePath is absolute, the directory itself is not a symbolic link.

**Comment by mabho** [comment]
I have experienced a similar issue and was pulling my hair out. It turns out the issue was related to the path. At first, I thought I needed to setup an absolute path relative to server root, but that didn't work. Then I realized I needed to setup the path relative to default location my server user was logging in. Example: instead of `/var/www/html/my-app`, let's say my user logs in by default at `/var/www`. The path I needed to set on sftp.json for key `remotePath` was `/html/my-app`.

**Comment by justinchou** [comment]
i got the same issue, and i figured that my server disk space is full.

after clean up some free space, it succeed.

**Comment by osumko** [comment]
> i got the same issue, and i figured that my server disk space is full.

Mine is not.

**Comment by esemlabel** [comment]
> i got the same issue, and i figured that my server disk space is full.
mine is not.

**Comment by C0ldstudy** [comment]
> i got the same issue, and i figured that my server disk space is full.
> 
> after clean up some free space, it succeed.

Thanks! Same Problem Here!

**Comment by DennisTap** [comment]
My bottleneck was a cache directory. I put it as ignore ("ignore": [".vscode", ".git", "node_modules", ".DS_Store", "cache"],) and that solve my problem. 

I think what could be the problem is the length of the path + filename

**Comment by osumko** [comment]
@DennisTap, yeah, could be the case.
My sync in most cases fails at the same point, for instance
`Git/project/php-library/tools/vendors/simplesamlphp/simplesamlphp/locales/no`

**Comment by osumko** [comment]
One of the file that failed to sync is a shortcut to folder
![image](https://user-images.githubusercontent.com/17903845/99547979-d5a8c800-29c0-11eb-912a-ddd894a08da1.png)

```
Error: Failure
	at SFTPStream._transform (/Users/usr/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:189:10)
	at SFTPStream._read (/Users/usr/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:177:12)
	at doWrite (_stream_writable.js:435:12)
	at writeOrBuffer (_stream_writable.js:419:5)
	at SFTPStream.Writable.write (_stream_writable.js:309:11)
	at Channel.ondata (_stream_readable.js:728:22)
	at Channel.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Channel.Readable.push (_stream_readable.js:224:10)
	at SSH2Stream.<anonymous> (/Users/usr/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2/lib/Channel.js:167:15)
	at SSH2Stream.emit (events.js:223:5)
	at parsePacket (/Users/usr/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:3288:10)
	at SSH2Stream._transform (/Users/usr/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:694:13)
	at SSH2Stream.Transform._read (_stream_transform.js:189:10)
	at SSH2Stream._read (/Users/usr/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:177:12)
	at doWrite (_stream_writable.js:435:12)
	at writeOrBuffer (_stream_writable.js:419:5)
	at SSH2Stream.Writable.write (_stream_writable.js:309:11)
	at Socket.ondata (_stream_readable.js:728:22)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23) when local ➞ remote /Users/usr/Documents/pr/php-lib/tools/vendor/simplesamlphp/simplesamlphp/locales/no
```

**Comment by kl990899** [comment]
In my case, I fixed this similar problem by clear my rails tmp/cache file.
I was lucky to solve this problem but I don’t know why.
Is there possible a file size too big to Sync remote to local?

**Comment by osumko** [comment]
I don't think it has something to do with file size.
In my case I noticed that sync just stucks during these cases:
– When switching branches.
– When pulling stash into the working tree.
– When working tree contain shortcut (link) file.
I tried few time on fresh Mac OS setup and it didn't help though.
Mac OS, vagrant through sftp with watcher setting enabled.

**Comment by kl990899** [comment]
@esemlabel, yes, I think you are correct.
I think it was because I just deleted the data that caused the error.
That’s why I ignored these issues.

**Comment by puazgit** [comment]
> My bottleneck was a cache directory. I put it as ignore ("ignore": [".vscode", ".git", "node_modules", ".DS_Store", "cache"],) and that solve my problem.
> 
> I think what could be the problem is the length of the path + filename

Thanks Bro this work for me

**Comment by Venegrad** [comment]
Same issue

**Comment by Kevinwuu** [comment]
Same issue.
Finally I solved this by downgrade vscode to v1.55
 [https://code.visualstudio.com/updates/v1_55](https://code.visualstudio.com/updates/v1_55)

**Comment by omicr0n** [comment]
Thanks to some of the suggestions in here I encountered this same issue and the fix turned out to be not using a symlinked directory as the `remotePath`.  I had it set to `/var/www/html/` but that folder is a symlink to `/storage/server/var/www/html/` on the server I was connecting too, changing `remotePath` to `/storage/server/var/www/html/` fixed the issue.
