### ISSUE TITLE
Error: Unknown command (fail to set modified time to?)

### ISSUE THREAD

**Issue by andremacola** [liximomo/vscode-sftp#359]
Using FTP protocol. The file upload fine but vscode return this error.

version: 1.6.3
VSCode Insiders: 1.29.0-insider
OSX Mojave

```
[error] Error: Unknown command.
	at makeError (/Users/andremacola/.vscode-insiders/extensions/liximomo.sftp-1.6.3/node_modules/ftp/lib/connection.js:1067:13)
	at Parser.<anonymous> (/Users/andremacola/.vscode-insiders/extensions/liximomo.sftp-1.6.3/node_modules/ftp/lib/connection.js:113:25)
	at emitTwo (events.js:126:13)
	at Parser.emit (events.js:214:7)
	at Parser._write (/Users/andremacola/.vscode-insiders/extensions/liximomo.sftp-1.6.3/node_modules/ftp/lib/parser.js:59:10)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at Parser.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (/Users/andremacola/.vscode-insiders/extensions/liximomo.sftp-1.6.3/node_modules/ftp/lib/connection.js:273:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) fail to set modified time to /htdocs/app/themes/impar/functions.php
[info] local -> remote /Users/andremacola/Dropbox/Dev/imparlab/themes/oimparcial/functions.php
```

**Comment by liximomo** [comment]
Just ignore this.
