### ISSUE TITLE
Only directory structure downloaded, no files

### ISSUE THREAD

**Issue by janvdm** [liximomo/vscode-sftp#368]
## Expected Behavior
Application should download full file tree.

## Actual Behavior
Application only downloads the directory structure but creates no files.
The Remote Explorer does work 

## Steps to Reproduce the Problem

  1. SFTP: Download Project

### Config

{
    "protocol": "sftp",
    "host": "...",
    "port": 22,
    "username": "...",
    "password": "...",
    "uploadOnSave": true,
    "remotePath": "/home/.../"
}

  ### Log

[error] Error: Failure
	at SFTPStream._transform (/Users/jan/.vscode/extensions/liximomo.sftp-1.7.0/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (/Users/jan/.vscode/extensions/liximomo.sftp-1.7.0/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (/Users/jan/.vscode/extensions/liximomo.sftp-1.7.0/node_modules/ssh2/lib/Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (/Users/jan/.vscode/extensions/liximomo.sftp-1.7.0/node_modules/ssh2-streams/lib/ssh.js:3445:10)
	at SSH2Stream._transform (/Users/jan/.vscode/extensions/liximomo.sftp-1.7.0/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (/Users/jan/.vscode/extensions/liximomo.sftp-1.7.0/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) 

## Specifications

- Extension Name: sftp
- Extension Version: 1.7.0
- OS Version: Darwin x64 18.0.0
- VSCode version: 1.28.2

**Comment by liximomo** [comment]
It's likely that your server runs out of file descriptors. Try to increase the file descriptor limit.

**Comment by janvdm** [comment]
Yes that fixed it. Thank you sir.
