### ISSUE TITLE
[error] Error: FileService Not Found.

### ISSUE THREAD

**Issue by sktzofrenic** [liximomo/vscode-sftp#373]
## Expected Behavior
File should upload on save

## Actual Behavior
Error is thrown in console

```
[error] Error: FileService Not Found. (file:///users/dan/documents/SolarMonitor/solarmonitor/admin/views.py) 
	at C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.0\out\src\modules\fileActivityMonitor.js:44:36
	at Generator.next (<anonymous>)
	at C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.0\out\src\modules\fileActivityMonitor.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.0\out\src\modules\fileActivityMonitor.js:3:12)
	at handleFileSave (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.0\out\src\modules\fileActivityMonitor.js:41:12)
	at host_1.onDidSaveTextDocument (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.0\out\src\modules\fileActivityMonitor.js:104:9)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.$acceptModelSaved (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:586)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

## Steps to Reproduce the Problem

  1. Change a file
  2. Save the file.
  3. Error is thrown

### Extension Logs
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
 

## Specifications

  - Version: 1.28.2 VS Code and 1.7.0 for sftp
  - Platform: Windows

I've uninstalled and reinstalled SFTP extension. I've rebooted my computer. I've disabled and re-enabled SFTP extension. Nothing has workd.

**Comment by sktzofrenic** [comment]
Why was this closed? Can someone at least explain what the error means? What exactly is missing? What is this mysterious `FileService`? I don't understand...

**Comment by liximomo** [comment]
Can you provide the full logs?

**Comment by sktzofrenic** [comment]
```
[info] config at \users\dan\documents\SolarMonitor {"remotePath":"/_solarmonitor/SolarMonitor","uploadOnSave":true,"downloadOnOpen":false,"ignore":[".git/**"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"host":"server.myground.org","username":"******","password":"******"}
[trace] run command 'Upload File'
[error] Error: FileService Not Found. (file:///users/dan/documents/SolarMonitor/solarmonitor/static/build/main.js) 
	at Object.handleCtxFromUri (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.2\out\src\fileHandlers\createFileHandler.js:19:15)
	at FileCommand.<anonymous> (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.2\out\src\commands\abstract\createCommand.js:50:71)
	at Generator.next (<anonymous>)
	at C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.2\out\src\commands\abstract\createCommand.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.2\out\src\commands\abstract\createCommand.js:3:12)
	at targetList.map (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.2\out\src\commands\abstract\createCommand.js:48:62)
	at Array.map (<anonymous>)
	at FileCommand.<anonymous> (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.2\out\src\commands\abstract\createCommand.js:48:49)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.2\out\src\commands\abstract\createCommand.js:4:58)
	at <anonymous> 
```

**Comment by sktzofrenic** [comment]
Thank you for being willing to try to help. This extension has made a big difference in my workflow and I want to help get it working again if possible.

**Comment by sktzofrenic** [comment]
So my best guess, looking at the source is that the issue lies here:
```
function getFileService(uri) {
    let fileService;
    if (core_1.UResource.isRemote(uri)) {
        const remoteRoot = app_1.default.remoteExplorer.findRoot(uri);
        if (remoteRoot) {
            fileService = remoteRoot.explorerContext.fileService;
        }
    }
    else {
        fileService = serviceManager.findPrefix(normalizePathForTrie(uri.fsPath)); <------
    }
    return fileService;
```

and here:

```
function normalizePathForTrie(pathname) {
    const isWindows = process.platform === 'win32';
    if (isWindows) {
        const device = pathname.substr(0, 2);
        if (device.charAt(1) === ':') {
            // lowercase drive letter
            return pathname[0].toLowerCase() + pathname.substr(1);
        }
    }
    return path.normalize(pathname);
```
The file that this plugin is trying to find isn't found because the path isn't being formed correctly. Maybe I'm totally wrong but wanted to try to help you save some time.

**Comment by sktzofrenic** [comment]
I am on a windows platform BTW

**Comment by sktzofrenic** [comment]
Another clue in the logs is that this string:

`(file:///users/dan/documents/SolarMonitor/solarmonitor/static/build/main.js)`

If you put it into the chrome address results in file not found.

However id you replace it with:

`(file://C:/users/dan/documents/SolarMonitor/solarmonitor/static/build/main.js) `

it works fine.

**Comment by liximomo** [comment]
Try the [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by Asitis** [comment]
Fun fact, I had this error too on Ubuntu.
Was writing about it here, until I realized I was missing the SFTP configuration in sftp.json for this specific host I was trying to upload to.

Suggestion: Maybe catch this fact ("No SFTP configuration found for host" or something) to make a clearer error? :)

**Comment by sktzofrenic** [comment]
@Asitis Can you let me know which configuration variables were either missing or incorrect? My config used to work, then stopped and I didn't make any changes to it. I'm just curious what you had to do to correct it.

**Comment by Asitis** [comment]
I'm not sure if your situation is comparable; when I opened the file:// url from the logs it did point to the correct file. That got me thinking something must be wrong with the config.

I have a multi-root setup, [like this](https://github.com/liximomo/vscode-sftp#multiple-context) 
and to be more precise with these variables.

```
    {
        "name": "MyHost",
        "context": "myhostfolder",
        "host": "xx.xx.xx",
        "username": "myuser",
        "remotePath": "/usr/share/nginx/html/",
        "privateKeyPath": "/home/user/.ssh/id_rsa",
        "uploadOnSave": true,
        "downloadOnOpen": true
    },
```

**Comment by sktzofrenic** [comment]
Still can't get this to work...
