### ISSUE TITLE
Hostname from .ssh/config results in ENOTFOUND

### ISSUE THREAD

**Issue by b00tsy** [liximomo/vscode-sftp#385]
**Do you read the FAQ?**
- [x] Yes.

**Describe the bug**

Using a hostname from .ssh/config results in ENOTFOUND: `getaddrinfo ENOTFOUND my-host my-host:22`

**To Reproduce**

.ssh/config:
```
Host my-host
        HostName 1.2.3.4
        Port 22
        User username
```

sftp.json:

I assume defining `sshConfigPath` is not required, as config wiki indicates that the default value is `~/.ssh/config`. Defining `sshConfigPath` in sftp.json does not fix the problem.

```
{  
  "name": "my host environment",  
  "protocol": "sftp",
  "host": "my-host",
  "username": "username",
  "privateKeyPath": "~/.ssh/id_rsa",
  "passphrase": true,
  "port": 22,
  "remotePath": "/",
  "ignore": [
    "**/.vscode/**",
    "**/.git/**",
    "**/.DS_Store"
  ]
}
```

**Expected behavior**
Should connect without issues.

I would also expect not having to redefine the username and the port (as required by validation) and privateKeyPath if defined in ~/.ssh/config.

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCode Version 1.28.2
 - Extension Version 1.7.2

**Extension Logs** - *required*

```
[info] config at xxx {"remotePath":"/","uploadOnSave":false,"downloadOnOpen":false,"ignore":["**/.vscode/**","**/.git/**","**/.DS_Store"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"name":"my-host","host":"my-host","username":"******","privateKeyPath":"~/.ssh/id_rsa","passphrase":"******","profiles":{"Watch and uploadOnSave":{"uploadOnSave":true},"Do nothing":{"uploadOnSave":false}},"defaultProfile":"Do nothing","user":"username"}

[trace] handle upload file for asd.js
[debug] Local ident: 'SSH-2.0-ssh2js0.2.1'
[debug] Client: Trying my-host on port 22 ...
[error] Error: [my-host]: getaddrinfo ENOTFOUND my-host my-host:22
	at Client.client.on.on.err (~/.vscode/extensions/liximomo.sftp-1.7.2/out/src/core/remote-client/sshClient.js:165:28)
	at emitOne (events.js:121:20)
	at Client.emit (events.js:211:7)
	at Socket.<anonymous> (~/.vscode/extensions/liximomo.sftp-1.7.2/node_modules/ssh2/lib/client.js:300:10)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at emitErrorNT (internal/streams/destroy.js:64:8)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickDomainCallback (internal/process/next_tick.js:218:9) download asd.js

```

**Comment by liximomo** [comment]
@b00tsy Does this work in terminal. Try ssh my-host.

**Comment by b00tsy** [comment]
that works!

**Comment by liximomo** [comment]
Try the  [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by kehw** [comment]
@b00tsy Is your problem solved? I have the same problem. I defined my hosts in ~/.ssh/config. To use them in a terminal with ssh/sftp command does not have any problem. But cannot make it work with the vscode-sftp.

**Comment by dambrogia** [comment]
@liximomo 

I have installed the debug package. Not sure what i'm supposed to do once it's installed the readme was just instructing how to install not what to do once it was installed, but I'm getting the same ENOTFOUND error in my console output. 

Here is my stack trace and my ssh config

    [info] [file-save] /$USER/Code/$REPOSITORY/index.php
    [error] Error: [ip-10-210-25-26.ec2.internal]: getaddrinfo ENOTFOUND $DESIRED_HOST $DESIRED_HOST:22
        at Client.module.exports._connectSSHClient.e.on.on.e (/$USER/.vscode/extensions/liximomo.sftp-1.12.2/dist/extension.js:70:106943)
        at Client.emit (events.js:187:15)
        at Socket.<anonymous> (/$USER/.vscode/extensions/liximomo.sftp-1.12.2/node_modules/ssh2/lib/client.js:305:10)
        at Socket.emit (events.js:182:13)
        at emitErrorNT (internal/streams/destroy.js:82:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
        at process._tickCallback (internal/process/next_tick.js:63:19) download /$USER/Code/$REPOSITORY/index.php

My ssh config for this might be a little more complicated than the average, but I can run a `ssh $DESIRED_HOST` and connect just fine.

I have a bastion I proxy through when attempting to SSH to specific private dns (which is $DESIRED_HOST)

    Host $DESIRED_HOST
        ProxyCommand ssh $BASTION -W %h:%p
        User $USER
        ServerAliveInterval 300
        ServerAliveCountMax 2
        ForwardAgent yes
        UserKnownHostsFile /dev/null
        StrictHostKeyChecking no
        IdentityFile ~/.ssh/id_rsa

    Host $BASTION
        HostName $BASTION_HOSTNAME
        User $USER
        ForwardAgent yes
        IdentityFile ~/.ssh/id_rsa

**Comment by mrsndmn** [comment]
The same issue with ProxyCommand

**Comment by cliff-in-auld-reekie** [comment]
I had this same issue on MacOS Sequoia and it has been doing my head in..  I don't know why SFTP extension ain't using DNS as configured in my Mac Network settings.

I resolved it (well a Heath Robinson lash-up really, but it now works):

"sudo nano /etc/hosts" and added my targets in there.
