### ISSUE TITLE
Diacritical signs in file names cause error 

### ISSUE THREAD

**Issue by Nagell** [liximomo/vscode-sftp#389]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Downloading files with diacritical signs in names cause error and ends with empty files with incorrect names. 

**To Reproduce**
1. Upload a file with at least one german diacritical sign in name to FTP server with other FTP program (for example Filezilla). Example diacritical signs: ä ü ö ß
2. Try to download remote directory.
3. See error:

`[error] Error: Can't open /dardania-bamberg.de/wp-content/uploads/2018/05/FuÃÂball.jpg: No such file or directory
    at makeError (/Users/dawidnitka/.vscode/extensions/liximomo.sftp-1.7.2/node_modules/ftp/lib/connection.js:1067:13)
    at Parser.<anonymous> (/Users/dawidnitka/.vscode/extensions/liximomo.sftp-1.7.2/node_modules/ftp/lib/connection.js:113:25)
    at emitTwo (events.js:126:13)
    at Parser.emit (events.js:214:7)
    at Parser._write (/Users/dawidnitka/.vscode/extensions/liximomo.sftp-1.7.2/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Parser.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (/Users/dawidnitka/.vscode/extensions/liximomo.sftp-1.7.2/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20) when remote -> local /Volumes/Internet/Webseiten/Live/dardania-bamberg.de/dardania-bamberg.de/wp-content/uploads/2018/05/FuÃball.jpg`

**Expected behavior**
All files shout be correct downloaded with proper names containing diacritical signs.

**Screenshots**
![Screenshot 2018-10-30](https://user-images.githubusercontent.com/4633237/48061404-1d37cf00-e1bf-11e8-8f40-657d6b71dbcd.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCode Version: 1.28.2
 - Extension Version: 1.7.3

**Extension Logs** - *required*
[log.txt](https://github.com/liximomo/vscode-sftp/files/2552935/log.txt)

**Comment by liximomo** [comment]
Does `/dardania-bamberg.de/wp-content/uploads/2018/05/FuÃÂball-150x150.jpg` exist in your server?

**Comment by Nagell** [comment]
Yes, all "missing" files are existing and working files. More specifically there's a file with correct name which is `Fußball-150x150.jpg`

**Comment by afelro97** [comment]
Did you manage to fix it? I get the same error

**Comment by Nagell** [comment]
No, I didn't. The only possibility was to use another Software (FileZilla for example) for downloading those files or just ignore them and do not use vscode-sftp for this directory.

**Comment by afelro97** [comment]
Ok, thanks

**Comment by afelro97** [comment]
If I sync again but the extension was unable to download these files, at the time that I sync with the server again, these files are not deleted right?

**Comment by Nagell** [comment]
It should't but I'm not sure. Use some mentioned another software (FileZilla, Cyber Duck or WinSCP), connect to the server with the same data you are using for vsc-sftp plugin an simply check it.

**Comment by afelro97** [comment]
Ok, thanks
