### ISSUE TITLE
[sftp] Permission denied

### ISSUE THREAD

**Issue by advokatb** [liximomo/vscode-sftp#39]
This is my config

>{
    "host": "server.hosting.server.com",
    "port": 22,
    "username": "111",
    "password": "222",
    "protocol": "sftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/www/example.com/wp-content/themes/theme_name/",
    "uploadOnSave": false,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "**/.vscode/**",
        "**/.git/**",
        "**/.DS_Store"
    ]
}

When trying to upload current selected file I got this **[sftp] Permission denied** 
Console output:

>[error]: context: undefined reason: Error: Permission denied
	at SFTPStream._transform (C:\Users\myusername\.vscode\extensions\liximomo.sftp-0.8.3\node_modules\ssh2-streams\lib\sftp.js:405:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\myusername\.vscode\extensions\liximomo.sftp-0.8.3\node_modules\ssh2-streams\lib\sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Channel.Readable.push (_stream_readable.js:136:10)
	at SSH2Stream.<anonymous> (C:\Users\myusername\.vscode\extensions\liximomo.sftp-0.8.3\node_modules\ssh2\lib\Channel.js:166:15)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (C:\Users\myusername\.vscode\extensions\liximomo.sftp-0.8.3\node_modules\ssh2-streams\lib\ssh.js:3439:10)
	at SSH2Stream._transform (C:\Users\myusername\.vscode\extensions\liximomo.sftp-0.8.3\node_modules\ssh2-streams\lib\ssh.js:667:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (C:\Users\myusername\.vscode\extensions\liximomo.sftp-0.8.3\node_modules\ssh2-streams\lib\ssh.js:251:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread 

How can it be fixed? Thanks.

**Comment by liximomo** [comment]
You don't have enough permission on remove files
.

**Comment by advokatb** [comment]
But similar plugin FTP-Simple works fine with this credentials. 
I think it's not server's problem .

**Comment by liximomo** [comment]
The required permission is 666. That error message comes directly/as-is from the server, so there isn't any more I can add to help determine the cause.

**Comment by maryxis** [comment]
I have also the same problem.

Did you find any solution on this issue?

**Comment by liximomo** [comment]
You don't have enough permission to remote files.  If you do have, check your config carefully.

**Comment by SteveLogan206** [comment]
I just ran into a similar problem where I started getting an Access Denied when trying to upload a file to the root of my FTP, but any subfolder off of the root worked fine.  I switched to CoreFTP to test it out and that worked fine so it doesn't appear to be a server permissions issue.

**Comment by tanzhihang** [comment]
@SteveLogan206  The same problem width me after update the sftp plugins. Did you find any solution on this issue?

**Comment by SteveLogan206** [comment]
@tanzhihang  - no, never found a solution other than to switch FTP plugins to one that works (ftp-kr).

**Comment by liximomo** [comment]
@tanzhihang  It's not the same problem. Try v1.3.4

**Comment by davecoffin** [comment]
I am having this problem as well, @liximomo are you suggesting to downgrade the version to 1.3.4?

**Comment by liximomo** [comment]
@davecoffin #279
