### ISSUE TITLE
Sudden [error] Error: Failure after updating to VSCode 1.29.1

### ISSUE THREAD

**Issue by bhancock8** [liximomo/vscode-sftp#399]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
I get the generic "[error] Error: Failure" message today after updating VSCode to 1.29.1 (from 1.29.0), but downgrading it back to 1.29.0 or 1.28 doesn't fix it. (I also tried downloading the latest debug version of the extension and adding "limitOpenFilesOnServer: true" to the config json).

**Expected behavior**
I expected the file to upload to the server like it has in the past.

**Desktop (please complete the following information):**
 - OS: Mac Mojave (syncing to linux)
 - VSCode Version [e.g. 1.27.0]: 1.29.1
 - Extension Version [e.g. 1.7.0]: 1.7.6-debug.1

**Extension Logs** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

[info] [file-save] /Users/bhancock/ParlAI/parlai_internal/projects/metadialog/metadialog_agent.py
[trace] handle upload file for /Users/bhancock/ParlAI/parlai_internal/projects/metadialog/metadialog_agent.py
[debug] Outgoing: Writing MKDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[error] Error: Failure
	at S._transform (/Users/bhancock/.vscode/extensions/liximomo.sftp-1.7.6-debug.1/dist/extension.js:70:135636)
	at S.Transform._read (_stream_transform.js:186:10)
	at S._read (/Users/bhancock/.vscode/extensions/liximomo.sftp-1.7.6-debug.1/dist/extension.js:70:131643)
	at S.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at S.Writable.write (_stream_writable.js:290:11)
	at h.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at h.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at h.Readable.push (_stream_readable.js:208:10)
	at Ee.<anonymous> (/Users/bhancock/.vscode/extensions/liximomo.sftp-1.7.6-debug.1/dist/extension.js:1:103674)
	at emitOne (events.js:116:13)
	at Ee.emit (events.js:211:7)
	at ge (/Users/bhancock/.vscode/extensions/liximomo.sftp-1.7.6-debug.1/dist/extension.js:70:216725)
	at Ee._transform (/Users/bhancock/.vscode/extensions/liximomo.sftp-1.7.6-debug.1/dist/extension.js:70:239716)
	at Ee.Transform._read (_stream_transform.js:186:10)
	at Ee._read (/Users/bhancock/.vscode/extensions/liximomo.sftp-1.7.6-debug.1/dist/extension.js:70:233841)
	at Ee.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at Ee.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) when local -> remote /Users/bhancock/ParlAI/parlai_internal/projects/metadialog/metadialog_agent.py

**Comment by bhancock8** [comment]
This appears to be an issue with my server entirely. The whole file system is suddenly claiming to be read-only. I'm almost certain this has nothing to do with VSCode or your extension. Thanks so much, by the way, for creating and maintaining it! It's a life saver!
