### ISSUE TITLE
spawn C:\util\pagent.exe ENOENT

### ISSUE THREAD

**Issue by navossoc** [liximomo/vscode-sftp#404]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Can't use pageant anymore on Windows.

**To Reproduce**
1. Setup a basic sftp.json with "agent": "pageant"
2. Run pageant and load keys.
3. sftp extension can't find pageant.

**Expected behavior**
Should work as before, use the keys loaded from memory.

**Screenshots**
![image](https://user-images.githubusercontent.com/2457338/48884344-3f5e5d80-ee0b-11e8-9376-17be432c1890.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 1803
 - VSCode Version 1.29.1
 - Extension Version 1.7.6

**Extension Logs** - *required*
```
[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload Changed File" from "./fileCommandUploadChangedFile.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at d:\Projects\vultr\ {"remotePath":"/","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"name":"vultr test","context":"./","host":"208.167.242.166","username":"******","syncOption":{"delete":true,"skipCreate":false,"ignoreExisting":false,"update":false},"agent":"pageant"}
[trace] run command 'Upload File'
[trace] handle upload file for d:\Projects\vultr\root\Dockerfile
[debug] Local ident: 'SSH-2.0-ssh2js0.2.1'
[debug] Client: Trying 208.167.242.166 on port 22 ...
[debug] Client: Connected
[debug] Remote ident: 'SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u4'
[debug] Outgoing: Writing KEXINIT
[debug] DEBUG: Comparing KEXINITs ...
[debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[debug] (remote) KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
[debug] KEX algorithm: ecdh-sha2-nistp256
[debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[debug] (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[debug] Host key format: ssh-rsa
[debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[debug] Client->Server Cipher: aes128-ctr
[debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[debug] Server->Client Cipher: aes128-ctr
[debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Client->Server HMAC algorithm: hmac-sha2-256
[debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Server->Client HMAC algorithm: hmac-sha2-256
[debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[debug] Client->Server compression algorithm: none
[debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[debug] Server->Client compression algorithm: none
[debug] Outgoing: Writing KEXECDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing USERAUTH_REQUEST (none)
[debug] Client: none auth failed
[debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[error] Error: [208.167.242.166]: spawn C:\util\pagent.exe ENOENT
	at B.e.on.on.e (C:\Users\Rafael\.vscode\extensions\liximomo.sftp-1.7.6\dist\extension.js:70:102276)
	at emitOne (events.js:121:20)
	at B.emit (events.js:211:7)
	at C:\Users\Rafael\.vscode\extensions\liximomo.sftp-1.7.6\dist\extension.js:70:113913
	at v.I (C:\Users\Rafael\.vscode\extensions\liximomo.sftp-1.7.6\dist\extension.js:70:266245)
	at Object.onceWrapper (events.js:315:30)
	at emitOne (events.js:116:13)
	at v.emit (events.js:211:7)
	at ChildProcess.<anonymous> (C:\Users\Rafael\.vscode\extensions\liximomo.sftp-1.7.6\dist\extension.js:70:268980)
	at Object.onceWrapper (events.js:317:30)
	at emitTwo (events.js:126:13)
	at ChildProcess.emit (events.js:214:7)
	at maybeClose (internal/child_process.js:925:16)
	at Socket.stream.socket.on (internal/child_process.js:346:11)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at Pipe._handle.close [as _onclose] (net.js:554:12) 
```

If I place a file `C:\util\pagent.exe`, vscode tries to spawn it with the following command line:
`C:\util\pagent.exe 5`

![image](https://user-images.githubusercontent.com/2457338/48884606-53568f00-ee0c-11e8-8120-949c1591ef09.png)

If I set a `privateKeyPath` on `sftp.json` it tries to spawn pageant again, this time loading that file and not the number 5.

This time I got this error:
![image](https://user-images.githubusercontent.com/2457338/48884695-b9431680-ee0c-11e8-9cc1-8213eaf2b97a.png)

Anyway, not sure what is happening, but it get broken on this last update.

PS: It is `pageant.exe` not `pagent.exe`.
PS2: I like the idea of spawning pageant.exe, but I think the path should be customized, maybe a user setting.

[]'s

**Comment by liximomo** [comment]
Please try [1.7.67-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by liximomo** [comment]
Great.
