### ISSUE TITLE
command sftp:config not found version 1.7.7

### ISSUE THREAD

**Issue by banner01** [liximomo/vscode-sftp#409]
**Do you read the FAQ?**
- [x ] Yes.
- [x] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
I have a new install of VS code and a new install of sftpftp sync 1.7.7.  Do 'ctrl+shift+p' to get to sftp:config command.  I select the command and get sftp:config not found.  In the past this created a .vscode folder and a file called sftp.json.  We would add our sftp data to this generic file.  I have set this up on on 15 windows PC's with no issues.  For some reason, on this one PC the sftp:config is not found.  

**To Reproduce**
1. ctrl+shift+p
2. In search box type 'sftp' 
3. When sftp:config appears in the list, select it.

**Expected behavior**
Create the default directory and sftp.json file

**Screenshots**
![sftp](https://user-images.githubusercontent.com/45401245/49102121-93b77200-f23d-11e8-8b20-a254a5b91b3b.png)

**Desktop (please complete the following information):**
 - OS: Win 10 64
 - VSCode Version 1.25.1
 - Extension Version 1.7.7

**Extension Logs** - *required*
Followed the debug instructions.  No logs created.  No attempt to connect as this is the initial setup.

**Comment by johngoerl** [comment]
I am having the same issue on Mac OS 12.12.6 -- cannot use the extension at all. 

I've also tried reinstalling, manually deleting directories, etc.

**Comment by CherryCHan** [comment]
INFO no standard startup: not a new window
console.ts:136 [Extension Host] 激活扩展“liximomo.sftp”失败: Unexpected token (。
t.log @ console.ts:136
console.ts:136 [Extension Host] Activating extension `liximomo.sftp` failed:  Unexpected token (
t.log @ console.ts:136
console.ts:136 [Extension Host] Here is the error stack:  /Users/rachelchen/.vscode/extensions/liximomo.sftp-1.7.7/dist/extension.js:61
function(e){"use strict";!function(e,t){for(var n in t)t.hasOwnProperty(n)&&(e[n]=t[n])}(e.prototype,{apply:function(e,t){return this.test(t[0])},call:function(e,t){return this.test(t)},forEach:function(t,n,r){return e.forEach(t,this,n,r)},globalize:function(){return e.globalize(this)},xexec:function(t,n,r){return e.exec(t,this,n,r)},xtest:function(t,n,r){return e.test(t,this,n,r)}})}(r)},function(e,t,n){"use strict";var r=this&&this.__awaiter||function(e,t,n,r){return new(n||(n=Promise))(function(i,o){function s(e){try{c(r.next(e))}catch(e){o(e)}}function a(e){try{c(r.throw(e))}catch(e){o(e)}}function c(e){e.done?i(e.value):new n(function(t){t(e.value)}).then(s,a)}c((r=r.apply(e,t||[])).next())})};Object.defineProperty(t,"__esModule",{value:!0});const i=n(44),o=n(23),s=n(11);var a;!function(e){e.LOCAL_TO_REMOTE="local -> remote",e.REMOTE_TO_LOCAL="remote -> local"}(a=t.TransferDirection||(t.TransferDirection={}));t.default=class{
SyntaxError: Unexpected token (
	at createScript (vm.js:53:10)
	at Object.runInThisContext (vm.js:95:10)
	at Module._compile (module.js:543:28)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:30:770)
	at /private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:790:186
	at t._doActivateExtension (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:790:298)
	at t._activateExtension (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:789:187)
	at Object.actualActivateExtension (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:787:48)
	at e._activateExtension (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:452:188)
	at /private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:451:757
	at Array.map (native)
	at e._activateExtensions (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:451:732)
	at e.activateById (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:450:247)
	at t.activateById (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:787:610)
	at t.<anonymous> (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:812:334)
	at /private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:88:680
	at Object.next (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:88:785)
	at s (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:87:782)
	at Object.g [as _notify] (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:729)
	at Object.enter (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:61)
	at n.Class.derive._oncancel._run (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:866)
	at n.Class.derive._oncancel._completed (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:307)
	at Object.g [as _notify] (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:729)
	at Object.enter (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:61)
	at n.Class.derive._oncancel._run (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:866)
	at n.Class.derive._oncancel._completed (/private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:307)
	at FSReqWrap.cb [as oncomplete] (fs.js:260:19)
extensionService.ts:892 激活扩展“liximomo.sftp”失败: Unexpected token (。
w._logMessageInConsole @ extensionService.ts:892
notificationsAlerts.ts:40 Error: command 'sftp.config' not found
    at t._tryExecuteCommand (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2915:36)
    at file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2914:846
    at Object.g [as _notify] (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:155:337)
    at l (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:158:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:159:45)
    at Object.g [as _notify] (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:155:337)
    at l (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:158:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:159:45)
    at Object.g [as _notify] (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._creator._run (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._completed (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:155:337)
    at Object.g [as _notify] (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:155:337)
    at e.resolveOk (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3060:806)
    at e._receiveReply (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3126:708)
    at e._receiveOneMessage (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3126:6)
    at file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3124:863
    at file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3127:942
    at e.fire (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:171:344)
    at c (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:302:1008)
    at Socket.<anonymous> (file:///private/var/folders/rk/pryycktj0x91gn99_9h437y92_v3vs/T/AppTranslocation/0D7F4588-9F3E-472C-8997-8FE8BFEBA212/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:303:171)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
e.onDidNotificationChange @ notificationsAlerts.ts:40
log.ts:159  INFO No grammar found for scope source.smarty
notificationsAlerts.ts:40 Error: command 'sftp.config' not found
    at t._tryExecuteCommand (commandService.ts:57)
    at commandService.ts:50
    at n.Class.derive._oncancel.then (winjs.base.js:1581)
    at t.executeCommand (commandService.ts:50)
    at t.run (actions.ts:204)
    at t.run (actions.ts:252)
    at commandsHandler.ts:306
    at n.Class.derive._oncancel.done (winjs.base.js:1539)
    at Object.g [as _notify] (winjs.base.js:1195)
    at Object.enter (winjs.base.js:867)
    at n.Class.derive._oncancel._run (winjs.base.js:1083)
    at n.Class.derive._oncancel._completed (winjs.base.js:1051)
e.onDidNotificationChange @ notificationsAlerts.ts:40
console.ts:136 [Extension Host] ApplicationInsights:Sender Array(1)
t.log @ console.ts:136
log.ts:159  INFO No grammar found for scope source.dosbatch
log.ts:159  INFO No grammar found for scope source.scala
log.ts:159  INFO No grammar found for scope source.dart
log.ts:159  INFO No grammar found for scope text.html.javadoc
log.ts:159  INFO No grammar found for scope source.postscript
log.ts:159  INFO No grammar found for scope source.c++
log.ts:159  INFO No grammar found for scope source.js.jquery
log.ts:159  INFO No grammar found for scope source.sass
log.ts:159  INFO No grammar found for scope source.less
log.ts:159  INFO No grammar found for scope source.stylus
log.ts:159  INFO No grammar found for scope source.applescript
log.ts:159  INFO No grammar found for scope text.html.textile
log.ts:159  INFO Requested uninstalling the extension josa.markdown-table-formatter from window 4
log.ts:159  INFO Uninstalling the extension josa.markdown-table-formatter-0.2.3 from window 4

**Comment by liximomo** [comment]
@CherryCHan Please upgrade your vscode.

**Comment by johngoerl** [comment]
Updating to VSCode 1.29.1 (from 1.29.0) fixed this issue for me as well. Had to manually update.

**Comment by banner01** [comment]
That worked.  I had not realized the SFTP version had updated.  Thank you for your quick response.

Daniel W. Clements
Senior Network Support
AT&T Technology Operations – TP&E Global Infrastructure Provisioning
Work:    205.725.7810
Cell:    972.814.9107
E-mail: dc2139@att.com<mailto:dc2139@att.com>
TEXTING and DRIVING... It Can Wait. Take the pledge<http://www.itcanwait.com/> today and pass it on
“This e-mail and any files transmitted with it are the property of AT&T, are confidential, and are  intended solely for the use of the individual or entity to whom this e-mail is addressed. If you are not one of the named recipients or otherwise have reason to believe that you have received this message in error, please notify the sender at 817-850-2840 and delete this message immediately from your computer. Any other use, retention, dissemination, forwarding, printing, or copying of this e-mail is strictly prohibited."

**Comment by liximomo** [comment]
I will update the vscode engine version in the next release to prevent this problem.
