### ISSUE TITLE
Config File not found, uploadOnSave does not work

### ISSUE THREAD

**Issue by mrspades** [liximomo/vscode-sftp#413]
vscode 1.29.1
sftp v1.7.7
OS: Windows 10

Since I upgraded sftp extension, whenever I save a file, sftp doesn't do anything even if uploadOnSave = true and Debug is ticked. If I try to right-click and "Upload" manually I get the "Config File not found" error.
My workspace root is \Work\vsCode folder, and the sftp.json is in \Work\vsCode\\.vsCode

Here is what comes in the OUTPUT window
`
[info] remote -> local \Work\vsCode\folder-092\var\docker\dasis\dasisSync\sync.pl
[trace] run command 'Reveal In Explorer'
[trace] run command 'Upload File'
[error] Error: Config Not Found. (file:///c:/Work/vsCode/folder-092/var/docker/dasis/dasisSync/sync.pl) 
	at Object.u [as handleCtxFromUri] (C:\Users\pfel\.vscode\extensions\liximomo.sftp-1.7.7\dist\extension.js:6:8170)
	at Object.<anonymous> (C:\Users\pfel\.vscode\extensions\liximomo.sftp-1.7.7\dist\extension.js:1:4043)
	at Generator.next (<anonymous>)
	at C:\Users\pfel\.vscode\extensions\liximomo.sftp-1.7.7\dist\extension.js:1:3323
	at new Promise (<anonymous>)
	at r (C:\Users\pfel\.vscode\extensions\liximomo.sftp-1.7.7\dist\extension.js:1:3100)
	at a.map.t (C:\Users\pfel\.vscode\extensions\liximomo.sftp-1.7.7\dist\extension.js:1:3985)
	at Array.map (<anonymous>)
	at Object.<anonymous> (C:\Users\pfel\.vscode\extensions\liximomo.sftp-1.7.7\dist\extension.js:1:3978)
	at Generator.next (<anonymous>)
	at s (C:\Users\pfel\.vscode\extensions\liximomo.sftp-1.7.7\dist\extension.js:1:3156)`

**Comment by liximomo** [comment]
What is your config?

**Comment by mrspades** [comment]
You're right, I found the answer in #408 
The "c:" was missing in context
changing from 
```
{
  ...
  "context":"/workspace"
}
```
to 
```
{
  ...
  "context":"c:/workspace"
}
```
and everything started working.
Maybe would be good to point this out in the README, I feel more people (like me :/ ) will fall into this 

PS: great, great extension!
