### ISSUE TITLE
"[error] TypeError: Cannot read property 'substr' of undefined" occurs again

### ISSUE THREAD

**Issue by yingHH** [liximomo/vscode-sftp#419]
Hi, I update my sftp to version 1.8.0 in my vscode (v1.29.1 in windows), but I got an error:
```
[error] TypeError: Cannot read property 'substr' of undefined
	at d (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.8.0\dist\extension.js:1:24488)
	at F (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.8.0\dist\extension.js:1:24740)
	at Object.t.createFileService (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.8.0\dist\extension.js:1:24915)
	at forEach.t (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.8.0\dist\extension.js:61:36254)
	at Array.forEach (<anonymous>)
	at C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.8.0\dist\extension.js:61:36240
	at Generator.next (<anonymous>)
	at s (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.8.0\dist\extension.js:61:35814)
	at <anonymous> 
```
I have saw the issue #220, but the bug seems occurs agian.
So, is there any idea to solve it ?
Thanks.

**Comment by liximomo** [comment]
Upgrade to v1.8.1
