### ISSUE TITLE
Error: Config Not Found

### ISSUE THREAD

**Issue by MAGICYMZ** [liximomo/vscode-sftp#424]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**

当运营`Upload Active File`命令上传当前文件的时候，出现**Error: Config Not Found**错误

**To Reproduce**
1. 在VScode中安装sftp插件，并重新加载使之可用
2. 鼠标右键点击「Upload」选项或者执行`Upload Active File`命令
3. 出现**Error: Config Not Found**错误
4. 在参考[Error: Config Not Found](https://github.com/liximomo/vscode-sftp/issues/394)的issue之后，卸载当前插件版本，并尝试了[debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge)和[1.7.5-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge)，依然存在同样的问题

**Expected behavior**
能够正常的上传当前的文件到服务器上
**Screenshots**
![image](https://user-images.githubusercontent.com/45745897/49796002-7672bf80-fd76-11e8-8742-56ad25925020.png)

**Desktop (please complete the following information):**
 - OS: Win10（×64）1083
 - VSCode Version 1.29.1
 - Extension Version 1.8.0

**Extension Logs from Startup** - *required*
```
[trace] run command 'Upload Active File'
[error] Error: Config Not Found. (file:///c:/Users/Y/Documents/我的坚果云/写作分享/ceshi.md) 
	at Object.u [as handleCtxFromUri] (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:41656)
	at Object.<anonymous> (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:4045)
	at Generator.next (<anonymous>)
	at C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3325
	at new Promise (<anonymous>)
	at r (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3102)
	at a.map.t (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3987)
	at Array.map (<anonymous>)
	at Object.<anonymous> (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3980)
	at Generator.next (<anonymous>)
	at s (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3158)
	at <anonymous> 
[trace] run command 'Upload File'
[error] Error: Config Not Found. (file:///c:/Users/Y/Documents/我的坚果云/写作分享/ceshi.md) 
	at Object.u [as handleCtxFromUri] (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:41656)
	at Object.<anonymous> (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:4045)
	at Generator.next (<anonymous>)
	at C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3325
	at new Promise (<anonymous>)
	at r (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3102)
	at a.map.t (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3987)
	at Array.map (<anonymous>)
	at Object.<anonymous> (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3980)
	at Generator.next (<anonymous>)
	at s (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3158)
	at <anonymous> 
```

**Comment by liximomo** [comment]
请提供从扩展启动开始全部的 log. 我需要看你的配置.

**Comment by MAGICYMZ** [comment]
> 请提供从扩展启动开始全部的 log. 我需要看你的配置.
```
[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[warn] ENOENT: no such file or directory, open 'C:\Users\Y\.ssh\config' load C:\Users\Y\.ssh\config failed
[info] config at c:\Users\Y\Documents\我的坚果云\vscode {"remotePath":"/var/www/blog/source/_posts/","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"host":"39.105.202.171","username":"******","password":"******"}
[trace] run command 'Upload Active File'
[error] Error: Config Not Found. (file:///c:/Users/Y/Documents/我的坚果云/写作分享/ceshi.md) 
	at Object.u [as handleCtxFromUri] (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:41656)
	at Object.<anonymous> (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:4045)
	at Generator.next (<anonymous>)
	at C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3325
	at new Promise (<anonymous>)
	at r (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3102)
	at a.map.t (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3987)
	at Array.map (<anonymous>)
	at Object.<anonymous> (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3980)
	at Generator.next (<anonymous>)
	at s (C:\Users\Y\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:1:3158)
	at <anonymous> 
```

**Comment by liximomo** [comment]
你是手动创建的配置吧, 配置目录错了. 应该是在 `.vscode` 目录下而不是 `vscode`. 建议使用命令 SFTP: config 创建一个默认的配置模板.

**Comment by MAGICYMZ** [comment]
非常感谢，太棒了，我把「sftp.json」文件放在了默认的`.vscode`目录中，并修改了对应的配置，可以成功运行了！

但还有一个问题，就是我运行`Upload Active File`命令的时候，也把该文件所属的文件夹一并上传到服务器了，例如我想上传「ceshi.md」文件，其中「ceshi.md」文件在Windows上所属的目录为「Document/mynuts/协作分享/」，我在服务器指定的上传目录为「/var/www/blog/source/」，我只想把「ceshi.md」文件上传到「/var/www/blog/source/」中，即得到的文件为「/var/www/blog/source/ceshi.md」但实际上，结果却是「/var/www/blog/source/Document/mynuts/写作分享/ceshi.md」

所以我该如何做，才能解决我这个问题呢？

**Comment by liximomo** [comment]
请提供一下信息:

1. 你的工作空间路径
2. 你的 sftp.json 配置完整路径.

**Comment by MAGICYMZ** [comment]
settings.json的完整路径：「C:\Users\Y\.vscode」
sftp.json的配置完整路径：「C:\Users\Y\.vscode」
vscode的安装路径：「C:\Program Files\Microsoft VS Code」

**Comment by liximomo** [comment]
你的工作路径呢

**Comment by MAGICYMZ** [comment]
太棒了，十分感谢您的耐心指导，终于成功了，太感谢了！

**Comment by 14714** [comment]
Greetings. I had the same problem, but i fixed with a specified **context**, example: 
`"context": "/laragon/www/project/"`
