### ISSUE TITLE
Error with sftp v1.8.2 and vscode v1.29.0

### ISSUE THREAD

**Issue by davebit15** [liximomo/vscode-sftp#425]
When trying to refresh the SFTP remote explorer view, I get this error:
command 'sftp.remoteExplorer.refresh' not found

This is the sftp log:
[error] Error: [liximomo.sftp]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api liximomo.sftp
	at r (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:437:7)
	at Object.t.checkProposedApiEnabled (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:437:647)
	at e.createTreeView (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:439:206)
	at Object.createTreeView (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:689:767)
	at new t.default (C:\Users\dave\.vscode\extensions\liximomo.sftp-1.8.2\dist\extension.js:78:82600)
	at C:\Users\dave\.vscode\extensions\liximomo.sftp-1.8.2\dist\extension.js:61:36755
	at Generator.next (<anonymous>)
	at s (C:\Users\dave\.vscode\extensions\liximomo.sftp-1.8.2\dist\extension.js:61:35814)
	at <anonymous>

Previously it was working flawlessly.

Thanks!

**Comment by AskMP** [comment]
Absolutely identical to the above for me. It was working this afternoon up to about 3 hours ago. I've not performed any updates to my knowledge to vscode unless something autoupdated in the background?

**Comment by 7Hd** [comment]
I encountered the same error in vscode 1.29, but there was no error after updating to 1.30.

**Comment by AskMP** [comment]
@7Hd You're absolutely right. Updating to the 1.30 clears this right up! Thanks.

**Comment by davebit15** [comment]
> 
> 
> I encountered the same error in vscode 1.29, but there was no error after updating to 1.30.

It works! Thanks!

**Comment by biolxy** [comment]
command 'sftp.remoteExplorer.refresh' not found
VSC 1.36.1

**Comment by JuanIrache** [comment]
This seems to be back in VSCode insiders 1.50

**Comment by rowild** [comment]
Error back in VScode 1.52.1 - confirmed.
Bu I use to projects at the same time, who both connect to the same remote server, but to different folders. I think I need to setup what is called "profiles" in this case.

**Comment by webdev0727** [comment]
This seems to be back in VSCode insiders 1.53

**Comment by webdev0727** [comment]
![image](https://user-images.githubusercontent.com/48287086/107693068-adc6b900-6cbe-11eb-8802-f75d4bcc0a89.png)
