### ISSUE TITLE
Failure when I try to sync local to remote

### ISSUE THREAD

**Issue by RoberDev** [liximomo/vscode-sftp#435]
When I try to sync local to remote I get this error, however I can upload to server without problem.
Here is the error:

```
[error] Error: Failure
	at SFTPStream._transform (/home/roberto/.vscode/extensions/liximomo.sftp-1.8.4/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (/home/roberto/.vscode/extensions/liximomo.sftp-1.8.4/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (/home/roberto/.vscode/extensions/liximomo.sftp-1.8.4/node_modules/ssh2/lib/Channel.js:166:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (/home/roberto/.vscode/extensions/liximomo.sftp-1.8.4/node_modules/ssh2-streams/lib/ssh.js:3445:10)
	at SSH2Stream._transform (/home/roberto/.vscode/extensions/liximomo.sftp-1.8.4/node_modules/ssh2-streams/lib/ssh.js:671:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (/home/roberto/.vscode/extensions/liximomo.sftp-1.8.4/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) when local -> remote /home/roberto/Inmobiliaria/phpmyadmin
```

Here my config:

```
{
    "protocol": "sftp",
    "host": "****t",
    "port": 22,
    "username": "root",
    "remotePath": "/var/www/html",
    "ignore": [
        "\\.vscode"
    ]
}

```

Is there a problem with the config? Thanks for all.

**Comment by Nabeatsu** [comment]
Hi, I have same problem. That's sent by the server, it could mean anything though. Perhaps it's a resource issue.For example,  too many files open, too many concurrent requests, etc.
I succeeded if I changed sftp.json to the following. Added directories contain extremely large size files such as images.

```json
"ignore": [
        ".vscode",
        ".git",
        ".DS_Store",
        "tmp",
        "public/photos_photos",
        "uploads"
    ],
```
This information is hope for your help. Good luck!

**Comment by jakubLangr** [comment]
I have the same error and the above did not help. I went to the local directory and I do not have a single file >1MB. But admittedly, this is a custom server (on AWS this works fine), so there could be problems elsewhere. As pointed out, it would be helpful if the error message was more informative.
