### ISSUE TITLE
Diff with remote => Error: Config not found

### ISSUE THREAD

**Issue by DatXN** [liximomo/vscode-sftp#439]
I got this error when select diff with remote:
```
[error] Error: Config Not Found. (file:///c:/RXN/Projects/rxnus/src/index.html) 
	at Object.u [as handleCtxFromUri] (C:\Users\DatNguyen\.vscode\extensions\liximomo.sftp-1.8.4\dist\extension.js:1:41657)
	at module.exports.t.createFileCommand.<anonymous> (C:\Users\DatNguyen\.vscode\extensions\liximomo.sftp-1.8.4\dist\extension.js:1:4045)
	at Generator.next (<anonymous>)
	at module.exports.r (C:\Users\DatNguyen\.vscode\extensions\liximomo.sftp-1.8.4\dist\extension.js:1:3325)
	at new Promise (<anonymous>)
	at module.exports.r (C:\Users\DatNguyen\.vscode\extensions\liximomo.sftp-1.8.4\dist\extension.js:1:3102)
	at module.exports.t.createFileCommand.a.default.doCommandRun.a.map.t (C:\Users\DatNguyen\.vscode\extensions\liximomo.sftp-1.8.4\dist\extension.js:1:3987)
	at Array.map (<anonymous>)
	at module.exports.t.createFileCommand.<anonymous> (C:\Users\DatNguyen\.vscode\extensions\liximomo.sftp-1.8.4\dist\extension.js:1:3980)
	at Generator.next (<anonymous>)
	at s (C:\Users\DatNguyen\.vscode\extensions\liximomo.sftp-1.8.4\dist\extension.js:1:3158)
	at <anonymous> 
```

This is my config file: (inside project folder \ .vscode\sftp.json
```

{
  "protocol": "sftp",
  "host": "******",
  "port": 22,
  "username": "xxxxx",
  "remotePath": "/var/www/html",
  "privateKeyPath": "xxxxx",
  "passphrase": "xxxxx",
  "context": "dist",
  "watcher": {
    "files": "**/*",
    "autoUpload": false,
    "autoDelete": false
  }
}

```

**Comment by liximomo** [comment]
Remove `"context": "dist"`. sftp can only work with files in context.

**Comment by DatXN** [comment]
Thank you :)
