### ISSUE TITLE
sftp/ftp proxy 

### ISSUE THREAD

**Issue by corsik** [liximomo/vscode-sftp#440]
Hi, tell me how to set up work through the corporate Proxy Squid port 3128

[error] Error: [corsikb4.beget.tech]: Timed out while waiting for handshake
	at Client.module.exports.a.default._connectSSHClient.e.on.on.e (C:\Users\SusidskiyIA\.vscode\extensions\liximomo.sftp-1.8.4\dist\extension.js:70:102739)
	at emitOne (events.js:121:20)
	at Client.emit (events.js:211:7)
	at Timeout._onTimeout (C:\Users\SusidskiyIA\.vscode\extensions\liximomo.sftp-1.8.4\node_modules\ssh2\lib\client.js:697:14)
	at ontimeout (timers.js:475:11)
	at tryOnTimeout (timers.js:310:5)
	at Timer.listOnTimeout (timers.js:270:5) 

{
    "protocol": "sftp",
    "host": "corsikb4.beget.tech",
    "port": 22,
    "username": "corsikb4_presta",
    "password": "password",
    "remotePath": "/"
}

{
    "http.proxy": "http://172.20.152.146:3128",
    "http.proxySupport": "on",
    "blade.format.enable": true,
    "sftp.downloadWhenOpenInRemoteExplorer": true,
    "sftp.printDebugLog": true,
}

**Comment by liximomo** [comment]
try "http.proxySupport": "override",

**Comment by corsik** [comment]
Tried, does not work.
```
{
    "http.proxy": "http://172.20.152.146:3128",
    "http.proxySupport": "override",
    "blade.format.enable": true,
    "sftp.downloadWhenOpenInRemoteExplorer": true,
    "sftp.printDebugLog": true
}
```
```
[debug] Local ident: 'SSH-2.0-ssh2js0.2.1'
[debug] Client: Trying corsikb4.beget.tech on port 22 ...
[debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
```

**Comment by liximomo** [comment]
https://github.com/Microsoft/vscode/issues/60773
