### ISSUE TITLE
Will not connect with private key

### ISSUE THREAD

**Issue by cpreston321** [liximomo/vscode-sftp#451]
Specs:
Computer: Macbook Pro
OS: Mojowave
----------------------------------------
This is the log I get when I connect with my private key when I try donwloading the dir but when I connect with "SSH Terminal"  it connects fine.

`[error] TypeError: privKey.getPrivatePEM is not a function
    at Client.connect (/Users/cpreston/.vscode/extensions/liximomo.sftp-1.9.0/node_modules/ssh2/lib/client.js:228:17)
    at module.exports.a.default._connectSSHClient.Promise (/Users/cpreston/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:102790)
    at new Promise (<anonymous>)
    at p.<anonymous> (/Users/cpreston/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:102431)
    at Generator.next (<anonymous>)
    at module.exports.r (/Users/cpreston/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:99448)
    at new Promise (<anonymous>)
    at module.exports.r (/Users/cpreston/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:99225)
    at p._connectSSHClient (/Users/cpreston/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:102122)
    at p.<anonymous> (/Users/cpreston/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:100904)
    at Generator.next (<anonymous>)
    at s (/Users/cpreston/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:99281)
    at <anonymous> `

**Comment by aegluke** [comment]
Same here. It happened after the Update to VSCode 1.30.2 with 1.30.1 everything works correct.
config:
{
    "protocol": "sftp",
    "host": ".....",
    "port": 22,
    "username": "...",
    "privateKeyPath": "~/.ssh/Private.key",
    "passphrase": true,
    "uploadOnSave": true,
    "remotePath": "...."
}

**Comment by pengyan518** [comment]
same here, It happened after the Update to VSCode 1.30.2 with 1.30.1 everything works correct.
macOS Mojave 10.14.2:

```
[error] ReferenceError: key is not defined
	at Function.OpenSSH_Old_Private.parse (/Users/jw/.vscode/extensions/liximomo.sftp-1.9.0/node_modules/ssh2-streams/lib/keyParser.js:779:15)
	at parseKey (/Users/jw/.vscode/extensions/liximomo.sftp-1.9.0/node_modules/ssh2-streams/lib/keyParser.js:1280:36)
	at Client.connect (/Users/jw/.vscode/extensions/liximomo.sftp-1.9.0/node_modules/ssh2/lib/client.js:225:19)
	at module.exports.a.default._connectSSHClient.Promise (/Users/jw/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:102790)
	at new Promise (<anonymous>)
	at p.<anonymous> (/Users/jw/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:102431)
	at Generator.next (<anonymous>)
	at module.exports.r (/Users/jw/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:99448)
	at new Promise (<anonymous>)
	at module.exports.r (/Users/jw/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:99225)
	at p._connectSSHClient (/Users/jw/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:102122)
	at p.<anonymous> (/Users/jw/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:100904)
	at Generator.next (<anonymous>)
	at s (/Users/jw/.vscode/extensions/liximomo.sftp-1.9.0/dist/extension.js:70:99281)
	at <anonymous> 

```

**Comment by liximomo** [comment]
**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by bolarson** [comment]
I used a *.ppk converted key from Putty and it worked.

**Comment by pengyan518** [comment]
Thanks a lot! 1.9.1 works fine!
