### ISSUE TITLE
Watcher and .git folder (Error: No such file)

### ISSUE THREAD

**Issue by VasyaHH** [liximomo/vscode-sftp#459]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Watcher ignore "ignore" setting of my config and watch for changes in git folder.

**To Reproduce**
My config:
```
{
    "protocol": "sftp",
    "host": "example.com",
    "port":22,
    "username": "user",
    "password": "xxxx",
    "remotePath": "/home/user/dev/www/",
    "uploadOnSave": true,
    "ignore": [
        ".vscode",
        ".git",
        ".DS_Store",
        "nbproject"
    ],
    "watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
    },
    "syncMode": "full"
}
```
Save any file (.vscode/sftp.json in my case) and you will see the log with error:
```
[info] [watcher-update] /home/user/aaWORK/git/project/project-WWW/.vscode
[info] [watcher-update] /home/user/aaWORK/git/project/project-WWW/.vscode/sftp.json
[info] [watcher-update] /home/user/aaWORK/git/project/project-WWW/.git/index.lock
[info] [watcher-update] /home/user/aaWORK/git/project/project-WWW/.git/index.lock
[error] Error: No such file
	at SFTPStream._transform (/home/user/.vscode/extensions/liximomo.sftp-1.9.1/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (/home/user/.vscode/extensions/liximomo.sftp-1.9.1/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (/home/user/.vscode/extensions/liximomo.sftp-1.9.1/node_modules/ssh2/lib/Channel.js:167:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (/home/user/.vscode/extensions/liximomo.sftp-1.9.1/node_modules/ssh2-streams/lib/ssh.js:3291:10)
	at SSH2Stream._transform (/home/user/.vscode/extensions/liximomo.sftp-1.9.1/node_modules/ssh2-streams/lib/ssh.js:689:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (/home/user/.vscode/extensions/liximomo.sftp-1.9.1/node_modules/ssh2-streams/lib/ssh.js:249:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) remove /home/user/aaWORK/git/project/project-WWW/.git/index.lock

```
**Desktop (please complete the following information):**
 - OS: Linux
 - VSCode Version [e.g. 1.30.2]
 - Extension Version [e.g. 1.9.1]

**Comment by liximomo** [comment]
Please try the [1.9.2-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by VasyaHH** [comment]
> Please try the [1.9.2-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

```
[info] [watcher-update] /home/user/aaWORK/git/project/project-WWW/.vscode/sftp.json
[info] [watcher-update] /home/user/aaWORK/git/project/project-WWW/.vscode
[info] [watcher-update] /home/user/aaWORK/git/project/project-WWW/.git/index.lock
[info] [watcher-update] /home/user/aaWORK/git/project/project-WWW/.git/index.lock
[trace] handle removeRemote for /home/user/aaWORK/git/project/project-WWW/.git/index.lock
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[error] Error: No such file
	at SFTPStream._transform (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/node_modules/ssh2/lib/Channel.js:167:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/node_modules/ssh2-streams/lib/ssh.js:3291:10)
	at SSH2Stream._transform (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/node_modules/ssh2-streams/lib/ssh.js:689:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/node_modules/ssh2-streams/lib/ssh.js:249:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) remove /home/user/aaWORK/git/project/project-WWW/.git/index.lock
```

**Comment by liximomo** [comment]
@VasyaHH This is not v1.9.2-debug. Please make sure reload vscode after install v1.9.2.

**Comment by liximomo** [comment]
@VasyaHH Sorry. Try  [1.9.2-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) again.

**Comment by VasyaHH** [comment]
> @VasyaHH Sorry, I forget to merge the fix. Try [1.9.2-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) again.

```
[info] [watcher/updated] /home/user/aaWORK/git/project/project-WWW/.vscode
[warn] ENOENT: no such file or directory, open '/home/user/.ssh/config' load /home/user/.ssh/config failed
[error] TypeError: c.ignore is not a function
	at Object.<anonymous> (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:42126)
	at Generator.next (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41497)
	at new Promise (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41274)
	at Object.module.exports.t.default [as upload] (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41958)
	at /home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:43116
	at Generator.next (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42583)
	at new Promise (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42360)
	at module.exports.e.forEach.e (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42967)
	at Array.forEach (<anonymous>)
	at module.exports.o.leading (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42956)
	at g (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45108)
	at /home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45474
	at D (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45481)
	at m (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:43676)
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:548:455
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at e.$onFileEvent (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:549:995)
	at t._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
	at t._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
	at t._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:657:126)
	at t._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
	at Socket.n._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) upload /home/user/aaWORK/git/project/project-WWW/.vscode
[info] [watcher/updated] /home/user/aaWORK/git/project/project-WWW/.vscode/sftp.json
[warn] ENOENT: no such file or directory, open '/home/user/.ssh/config' load /home/user/.ssh/config failed
[error] TypeError: c.ignore is not a function
	at Object.<anonymous> (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:42126)
	at Generator.next (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41497)
	at new Promise (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41274)
	at Object.module.exports.t.default [as upload] (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41958)
	at /home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:43116
	at Generator.next (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42583)
	at new Promise (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42360)
	at module.exports.e.forEach.e (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42967)
	at Array.forEach (<anonymous>)
	at module.exports.o.leading (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42956)
	at g (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45108)
	at v (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45331)
	at Timeout.y [as _onTimeout] (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45221)
	at ontimeout (timers.js:475:11)
	at tryOnTimeout (timers.js:310:5)
	at Timer.listOnTimeout (timers.js:270:5) upload /home/user/aaWORK/git/project/project-WWW/.vscode/sftp.json
[info] [watcher/updated] /home/user/aaWORK/git/project/project-WWW/.git/index.lock
[warn] ENOENT: no such file or directory, open '/home/user/.ssh/config' load /home/user/.ssh/config failed
[error] TypeError: c.ignore is not a function
	at Object.<anonymous> (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:42126)
	at Generator.next (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41497)
	at new Promise (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41274)
	at Object.module.exports.t.default [as upload] (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41958)
	at /home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:43116
	at Generator.next (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42583)
	at new Promise (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42360)
	at module.exports.e.forEach.e (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42967)
	at Array.forEach (<anonymous>)
	at module.exports.o.leading (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42956)
	at g (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45108)
	at /home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45474
	at D (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45481)
	at m (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:43676)
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:548:344
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at e.$onFileEvent (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:549:995)
	at t._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
	at t._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
	at t._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:657:126)
	at t._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
	at Socket.n._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) upload /home/user/aaWORK/git/project/project-WWW/.git/index.lock
[info] [watcher/removed] /home/user/aaWORK/git/project/project-WWW/.git/index.lock
[warn] ENOENT: no such file or directory, open '/home/user/.ssh/config' load /home/user/.ssh/config failed
[error] TypeError: c.ignore is not a function
	at Object.<anonymous> (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:42126)
	at Generator.next (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41497)
	at new Promise (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41274)
	at Object.module.exports.t.default [as removeRemote] (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:1:41958)
	at /home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:43482
	at Generator.next (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42583)
	at new Promise (<anonymous>)
	at module.exports.r (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:42360)
	at module.exports.e.forEach.e (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:43379)
	at Array.forEach (<anonymous>)
	at module.exports.o.leading (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:43368)
	at g (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45108)
	at /home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45474
	at D (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:45481)
	at module.exports.C.create.t.files.t.autoDelete.n.onDidDelete.e (/home/user/.vscode/extensions/liximomo.sftp-1.9.2-debug/dist/extension.js:78:44043)
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:548:566
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at e.$onFileEvent (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:549:995)
	at t._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
	at t._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
	at t._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:657:126)
	at t._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
	at Socket.n._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) remove /home/user/aaWORK/git/project/project-WWW/.git/index.lock

```

**Comment by liximomo** [comment]
Thanks for the feedback.

**Comment by liximomo** [comment]
@VasyaHH Please try  [1.9.2-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) again.

**Comment by VasyaHH** [comment]
> @VasyaHH Please try [1.9.2-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) again.

Save file `.vscode/sftp.json`:
```
[info] [watcher/updated] /home/user/aaWORK/git/project/project-WWW/.vscode
[info] [watcher/updated] /home/user/aaWORK/git/project/project-WWW/.vscode/sftp.json
[info] [watcher/updated] /home/user/aaWORK/git/project/project-WWW/.git/index.lock
[info] [watcher/removed] /home/user/aaWORK/git/project/project-WWW/.git/index.lock

```
