### ISSUE TITLE
All configured authentication methods failed when both privateKey

### ISSUE THREAD

**Issue by nangeblog** [liximomo/vscode-sftp#474]
{
    "name": "p40-1",
    "protocol": "sftp",
    "host": "xxx",
    "port":22,
    "username": "xxx",
    "remotePath": "xxx",
    "uploadOnSave":false,
    "downloadOnOpen":false,
    
    "ignore": [".vscode", ".git", ".DS_Store"],
    "hop": {
      "host": "xxx",
      "protocol": "sftp",
      "privateKeyPath": "xxx",
      "passphrase":"xxx",
      "port":8695,
      "username": "xxx"

    }
  }
 

[info] hopping from abc to edf
[error] Error: [def]: All configured authentication methods failed
	at Client.module.exports.a.default._connectSSHClient.e.on.on.e (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\dist\extension.js:70:106825)
	at emitOne (events.js:121:20)
	at Client.emit (events.js:211:7)
	at doNextAuth (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\node_modules\ssh2\lib\client.js:404:12)
	at tryNextAuth (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\node_modules\ssh2\lib\client.js:473:5)
	at SSH2Stream.onUSERAUTH_FAILURE (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\node_modules\ssh2\lib\client.js:583:5)
	at emitTwo (events.js:126:13)
	at SSH2Stream.emit (events.js:214:7)
	at parsePacket (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\node_modules\ssh2-streams\lib\ssh.js:3771:10)
	at SSH2Stream._transform (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\node_modules\ssh2-streams\lib\ssh.js:689:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\node_modules\ssh2-streams\lib\ssh.js:249:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\node_modules\ssh2\lib\Channel.js:167:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\node_modules\ssh2-streams\lib\ssh.js:3291:10)
	at SSH2Stream._transform (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\node_modules\ssh2-streams\lib\ssh.js:689:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (C:\Users\chennan2\.vscode\extensions\liximomo.sftp-1.9.2\node_modules\ssh2-streams\lib\ssh.js:249:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20)

**Comment by Hiuyee124** [comment]
could you tell me how you solve this? 
thanks a lot!
