### ISSUE TITLE
[error] Error: Unexpected packet before version

### ISSUE THREAD

**Issue by Dalinar42** [liximomo/vscode-sftp#480]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
My SSH isn't working and stops because of some sort of version mismatch. I've tried doing SSH in the terminal, but no random text pops out

**To Reproduce**

1. Go to 'Command Prompt'
2. Run command 'SFTP: Download Project'
3. See error

[info] config at c:\Users\USERNAME\Documents\SchoolMount {"remotePath":"/home/REMOTEPATH","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"School Linux","host":"XXX.XXX.XXX.XXX","port":215,"username":"******","password":"******"}
[error] Error: Unexpected packet before version
	at SFTPStream._transform (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2-streams\lib\sftp.js:306:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2\lib\Channel.js:167:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2-streams\lib\ssh.js:3291:10)
	at SSH2Stream._transform (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2-streams\lib\ssh.js:689:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2-streams\lib\ssh.js:249:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) 

**Expected behavior**
I expect it to connect and download my files from my school's server.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version 1.30.2
 - Extension Version 1.9.3

**Extension Logs from Startup** - *required*

[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at c:\Users\USERNAME\Documents\SchoolMount {"remotePath":"/home/nel14030","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"School Linux","host":"XXX.XXX.XXX.XXX","port":215,"username":"******","password":"******"}
[trace] run command 'Download Project'
[trace] handle download folder for c:\Users\USERNAME\Documents\SchoolMount
[debug] Local ident: 'SSH-2.0-ssh2js0.3.1'
[debug] Client: Trying XXX.XXX.XXX.XXX on port 215 ...
[debug] Client: Connected
[debug] Remote ident: 'SSH-2.0-OpenSSH_7.4'
[debug] Outgoing: Writing KEXINIT
[debug] DEBUG: Comparing KEXINITs ...
[debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[debug] (remote) KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[debug] KEX algorithm: ecdh-sha2-nistp256
[debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[debug] (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[debug] Host key format: ssh-rsa
[debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
[debug] Client->Server Cipher: aes128-ctr
[debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
[debug] Server->Client Cipher: aes128-ctr
[debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Client->Server HMAC algorithm: hmac-sha2-256
[debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Server->Client HMAC algorithm: hmac-sha2-256
[debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[debug] Client->Server compression algorithm: none
[debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[debug] Server->Client compression algorithm: none
[debug] Outgoing: Writing KEXECDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing USERAUTH_REQUEST (none)
[debug] Client: none auth failed
[debug] Outgoing: Writing USERAUTH_REQUEST (password)
[debug] Outgoing: Writing CHANNEL_OPEN (0, session)
[debug] Outgoing: Writing CHANNEL_REQUEST (0, subsystem: sftp)
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[error] Error: Unexpected packet before version
   at SFTPStream._transform (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2-streams\lib\sftp.js:306:27)
   at SFTPStream.Transform._read (_stream_transform.js:186:10)
   at SFTPStream._read (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2-streams\lib\sftp.js:183:15)
   at SFTPStream.Transform._write (_stream_transform.js:174:12)
   at doWrite (_stream_writable.js:387:12)
   at writeOrBuffer (_stream_writable.js:373:5)
   at SFTPStream.Writable.write (_stream_writable.js:290:11)
   at Channel.ondata (_stream_readable.js:639:20)
   at emitOne (events.js:116:13)
   at Channel.emit (events.js:211:7)
   at addChunk (_stream_readable.js:263:12)
   at readableAddChunk (_stream_readable.js:250:11)
   at Channel.Readable.push (_stream_readable.js:208:10)
   at SSH2Stream.<anonymous> (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2\lib\Channel.js:167:15)
   at emitOne (events.js:116:13)
   at SSH2Stream.emit (events.js:211:7)
   at parsePacket (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2-streams\lib\ssh.js:3291:10)
   at SSH2Stream._transform (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2-streams\lib\ssh.js:689:13)
   at SSH2Stream.Transform._read (_stream_transform.js:186:10)
   at SSH2Stream._read (C:\Users\USERNAME\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2-streams\lib\ssh.js:249:15)
   at SSH2Stream.Transform._write (_stream_transform.js:174:12)
   at doWrite (_stream_writable.js:387:12)
   at writeOrBuffer (_stream_writable.js:373:5)
   at SSH2Stream.Writable.write (_stream_writable.js:290:11)
   at Socket.ondata (_stream_readable.js:639:20)
   at emitOne (events.js:116:13)
   at Socket.emit (events.js:211:7)
   at addChunk (_stream_readable.js:263:12)
   at readableAddChunk (_stream_readable.js:250:11)
   at Socket.Readable.push (_stream_readable.js:208:10)
   at TCP.onread (net.js:594:20) 
[debug] Outgoing: Writing CHANNEL_EOF (0)
[debug] Outgoing: Writing CHANNEL_CLOSE (0)

**Comment by liximomo** [comment]
dup of #202

**Comment by Dalinar42** [comment]
Not a duplicate because there is no stray echo statement.
