### ISSUE TITLE
Upload fails for .gitignore

### ISSUE THREAD

**Issue by ajfick** [liximomo/vscode-sftp#484]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Uploading a .gitignore file appears to fail in any project on MacOs while uploading any other file works as expected. 

**To Reproduce**
1. Edit .gitignore file 
2. Save file and upload to remote
3. Get error in console

**Expected behavior**
Expected .gitignore file to be uploaded to remote server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS v10.12.6
 - VSCode Version: 1.30.2
 - Extension Version: 1.9.3

**Extension Logs from Startup** - *required*
```
[error] Error: Failure
	at SFTPStream._transform (/Users/my_user/.vscode/extensions/liximomo.sftp-1.9.3/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:186:10)
	at SFTPStream._read (/Users/my_user/.vscode/extensions/liximomo.sftp-1.9.3/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SFTPStream.Writable.write (_stream_writable.js:290:11)
	at Channel.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Channel.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Channel.Readable.push (_stream_readable.js:208:10)
	at SSH2Stream.<anonymous> (/Users/my_user/.vscode/extensions/liximomo.sftp-1.9.3/node_modules/ssh2/lib/Channel.js:167:15)
	at emitOne (events.js:116:13)
	at SSH2Stream.emit (events.js:211:7)
	at parsePacket (/Users/my_user/.vscode/extensions/liximomo.sftp-1.9.3/node_modules/ssh2-streams/lib/ssh.js:3291:10)
	at SSH2Stream._transform (/Users/my_user/.vscode/extensions/liximomo.sftp-1.9.3/node_modules/ssh2-streams/lib/ssh.js:689:13)
	at SSH2Stream.Transform._read (_stream_transform.js:186:10)
	at SSH2Stream._read (/Users/my_user/.vscode/extensions/liximomo.sftp-1.9.3/node_modules/ssh2-streams/lib/ssh.js:249:15)
	at SSH2Stream.Transform._write (_stream_transform.js:174:12)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at SSH2Stream.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata (_stream_readable.js:639:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20) 
```

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md#error-failure

**Comment by Shaffron** [comment]
1. check directory is exist on remote server
2. check directory permission

**Comment by ajfick** [comment]
@Shaffron The directory exists, and the permissions are correct as well. I actually just noticed this issue with another set of files.. I've got a `contact.php` and a `sendContact.js` file .. both permissions are identical and they are located in the same directory. `sendContact.js` uploads correctly, `contact.php` fails every time. It can however be downloaded without issue.

**Comment by stefnotch** [comment]
I have the same issue. 
To reproduce, create a local `.gitignore` and try to upload it.
