### ISSUE TITLE
TypeError: Cannot read property 'toLocaleLowerCase' of undefined  (since 1.9.4)

### ISSUE THREAD

**Issue by RixzZ** [liximomo/vscode-sftp#491]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Since version 1.9.4, the extension throws and error everytime you try to do something with it. If I rollback to 1.9.3 it works as expected.

**To Reproduce**
1. Install v1.9.4
2. Go to a existing config (or create a new one) and do any of the Sync actions. You can also go to the Remote Explorer sidebar button and no config will show up.
3. See error prompt on the lower right corner.

**Expected behavior**
Should work as on previous versions.

**Screenshots**
I compared the 'extension.js' file after formatting it between 1.9.3 and 1.9.4 and the problem seems to be here:
![image](https://user-images.githubusercontent.com/1339272/53443502-2538aa80-3a0c-11e9-9158-e6507a2e913f.png)
In version 1.9.3 the extension didn't use the function that now is failing.

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 29)
 - VSCode Version: 1.31.1
 - Extension Version: 1.9.4

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

```[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at /home/rixzz/Documents/Git/@RA/REDACTED {"remotePath":"/home/pi/Git/REDACTED/","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"RPI - Git/REDACTED","host":"rpi","username":"******","agent":"$SSH_AUTH_SOCK","syncOption":{"delete":true}}
[trace] run command 'Sync Local To Remote'
[error] TypeError: Cannot read property 'toLocaleLowerCase' of undefined
	at module.exports.C.h.config.forEach.e (/home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:70:61534)
	at l.forEach (<anonymous>)
	at /home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:70:61500
	at C (/home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:70:61612)
	at module.exports.t.default.getConfig (/home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:70:64116)
	at Object.u [as handleCtxFromUri] (/home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:1:41708)
	at module.exports.t.createFileCommand.<anonymous> (/home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:1:4045)
	at Generator.next (<anonymous>)
	at module.exports.r (/home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:1:3325)
	at new Promise (<anonymous>)
	at module.exports.r (/home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:1:3102)
	at module.exports.t.createFileCommand.doCommandRun.a.map.t (/home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:1:3987)
	at Array.map (<anonymous>)
	at module.exports.t.createFileCommand.<anonymous> (/home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:1:3980)
	at Generator.next (<anonymous>)
	at s (/home/rixzz/.vscode/extensions/liximomo.sftp-1.9.4/dist/extension.js:1:3158) ```

**Comment by liximomo** [comment]
Fix in v1.9.5
