### ISSUE TITLE
upload or download file failed due to TCP.onread failed.

### ISSUE THREAD

**Issue by Andy-Amoy** [liximomo/vscode-sftp#511]
**Do you read the FAQ?**
- [x] Yes.

**Describe the bug**
.vscode\sftp.json like below:
{
    "name": "dev",
    "context": "D:\\code\\dev",
    "protocol": "sftp",
    "host": "jumpbox.xxx.com",
    "port": 9122,
    "username": "root",
    "remotePath": "/data/dev",
    "uploadOnSave": true,
    "downloadOnOpen": false,
    "syncMode": "full",
    "ignore": [
        ".vscode",
        ".git",
        ".DS_Store"
    ],
    "privateKeyPath": "C:\\Users\\myuser\\.ssh\\id_rsa_4096"
}

 **DEBUG log:**
[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at d:\code\ads_serving {"remotePath":"/data/dev","uploadOnSave":true,"downloadOnOpen":false,"ignore":[".vscode",".git",".DS_Store"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"dev","context":"D:\\code\\dev","host":"jumpbox.xxx.com","port":9122,"username":"******","syncMode":"full","privateKeyPath":"C:\\Users\\myuser\\.ssh\\id_rsa_4096"}
[trace] run command 'Upload File'
[trace] handle upload file for d:\code\dev\serving\debug.proto
[debug] Local ident: 'SSH-2.0-ssh2js0.3.1'
[debug] Client: Trying jumpbox.xxx.com on port 9122 ...
[debug] Client: Connected
[debug] Remote ident: 'SSH-2.0-paramiko_2.4.0'
[debug] Outgoing: Writing KEXINIT
[debug] DEBUG: Comparing KEXINITs ...
[debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[debug] (remote) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[debug] KEX algorithm: ecdh-sha2-nistp256
[debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[debug] (remote) Host key formats: ssh-rsa
[debug] Host key format: ssh-rsa
[debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,3des-cbc
[debug] Client->Server Cipher: aes128-ctr
[debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,3des-cbc
[debug] Server->Client Cipher: aes128-ctr
[debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
[debug] Client->Server HMAC algorithm: hmac-sha2-256
[debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
[debug] Server->Client HMAC algorithm: hmac-sha2-256
[debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Client->Server compression algorithms: none
[debug] Client->Server compression algorithm: none
[debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Server->Client compression algorithms: none
[debug] Server->Client compression algorithm: none
[debug] Outgoing: Writing KEXECDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing USERAUTH_REQUEST (none)
[debug] Client: none auth failed
[debug] Outgoing: Writing USERAUTH_REQUEST (publickey -- check)
[debug] Outgoing: Writing USERAUTH_REQUEST (publickey)
[debug] Outgoing: Writing CHANNEL_OPEN (0, session)
[debug] Outgoing: Writing CHANNEL_REQUEST (0, subsystem: sftp)
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing MKDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[error] Error: Failure
    at SFTPStream._transform (C:\Users\myuser\.vscode\extensions\liximomo.sftp-1.12.0\node_modules\ssh2-streams\lib\sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (C:\Users\myuser\.vscode\extensions\liximomo.sftp-1.12.0\node_modules\ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SFTPStream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:672:20)
    at Channel.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Channel.Readable.push (_stream_readable.js:219:10)
    at SSH2Stream.<anonymous> (C:\Users\myuser\.vscode\extensions\liximomo.sftp-1.12.0\node_modules\ssh2\lib\Channel.js:167:15)
    at SSH2Stream.emit (events.js:182:13)
    at parsePacket (C:\Users\myuser\.vscode\extensions\liximomo.sftp-1.12.0\node_modules\ssh2-streams\lib\ssh.js:3291:10)
    at SSH2Stream._transform (C:\Users\myuser\.vscode\extensions\liximomo.sftp-1.12.0\node_modules\ssh2-streams\lib\ssh.js:689:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (C:\Users\myuser\.vscode\extensions\liximomo.sftp-1.12.0\node_modules\ssh2-streams\lib\ssh.js:249:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SSH2Stream.Writable.write (_stream_writable.js:294:11)
    at Socket.ondata (_stream_readable.js:672:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20) 

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - VSCode Version [1.32.3]
 - Extension Version [1.12.0]

**Comment by Andy-Amoy** [comment]
it seems due to some network issue, close as it not reproduce after I change some configurations
