### ISSUE TITLE
Using Win10's built-in SSH returns "Timed out while waiting for handshake"

### ISSUE THREAD

**Issue by Eagle3386** [liximomo/vscode-sftp#513]
**Do you read the FAQ?**
- [X] Yes, even similar issues (suggesting higher timeout of 20s instead of 10s; didn't help)
- [x] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Setting up everything just like on my Win7 machine, but uploading a modified file fails on Win10 using built-in OpenSSH client, no matter which key format (PuTTY, SSH2, SSH.COM) is used and with or without password on the private key.
Maybe it's related to #507?

**To Reproduce**
1. Go to any file within your setup workspace, e. g. `file.ext`
2. Having auto-save set to true, modify the file, e. g. type `x` and wait a second.
3. See error

**Expected behavior**
Upload should happen just as it does on my Win7 machine.

**Screenshots**
Not needed, log posted above.

**Desktop (please complete the following information):**
 - OS: Win 10 Pro (RS5, 180914-1434)
 - VSCode Version 1.32.3 (user setup)
 - Extension Version 1.12.1

**Extension Logs from Startup** - *required*
```
[info] config at X:\WS\Code {"remotePath":"/var/www/me/htdocs/sub.domain.net",
  "uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,
  "protocol":"sftp","connectTimeout":20000,"interactiveAuth":false,"secure":false,
  "remoteTimeOffsetInHours":0,"algorithms":{"kex":["ecdh-sha2-nistp521"],
    "cipher":["aes256-gcm","aes256-gcm@openssh.com"],"serverHostKey":["ssh-rsa",
      "ecdsa-sha2-nistp521"],"hmac":["hmac-sha2-512"]},"host":"domain.net",
  "ignoreFile":".gitignore","name":"me","passphrase":"******","port":22,
  "privateKeyPath":"X:\\WS\\Private.key","username":"******"}
[info] [file-save] X:\WS\Code\file.ext
[trace] handle upload file for X:\WS\Code\file.ext
[debug] Local ident: 'SSH-2.0-ssh2js0.3.1'
[debug] Client: Trying domain.net on port 22 ...
[debug] Client: Connected
[debug] Remote ident: 'SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u7'
[debug] Outgoing: Writing KEXINIT
[debug] DEBUG: Comparing KEXINITs ...
[debug] (local) KEX algorithms: ecdh-sha2-nistp521
[debug] (remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[debug] KEX algorithm: ecdh-sha2-nistp521
[debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp521
[debug] (remote) Host key formats: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
[debug] Host key format: ssh-rsa
[debug] (local) Client->Server ciphers: aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
[debug] Client->Server Cipher: aes256-gcm@openssh.com
[debug] (local) Server->Client ciphers: aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
[debug] Server->Client Cipher: aes256-gcm@openssh.com
[debug] (local) Client->Server HMAC algorithms: hmac-sha2-512
[debug] (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Client->Server HMAC algorithm: hmac-sha2-512
[debug] (local) Server->Client HMAC algorithms: hmac-sha2-512
[debug] (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Server->Client HMAC algorithm: hmac-sha2-512
[debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[debug] Client->Server compression algorithm: none
[debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[debug] Server->Client compression algorithm: none
[debug] Outgoing: Writing KEXECDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[error] Error: [domain.net]: Timed out while waiting for handshake
    at Client.module.exports._connectSSHClient.e.on.on.e (C:\Users\me\.vscode\extensions\liximomo.sftp-1.12.1\dist\extension.js:70:106943)
    at Client.emit (events.js:187:15)
    at Timeout._onTimeout (C:\Users\me\.vscode\extensions\liximomo.sftp-1.12.1\node_modules\ssh2\lib\client.js:678:14)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10) download X:\WS\Code\file.ext
```

**Comment by Eagle3386** [comment]
### Update:
Using the new `sshCustomParams` parameter with a value of `-i X:\\Keys\\Private.key` within my `sftp.json` file, I pressed <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>P</kbd>, selected `SFTP: Open SSH in Terminal`, the profile, typed my private key's password at the newly created terminal and **BOOM**, connection established! - though, any file change still results in the same error as shown in the log above (hanging at `SERVICE_REQUEST (ssh-userauth)` for a couple of seconds, then failing with `Timed out while waiting for handshake`). 😭

Nonetheless, this eliminates both, key and password, from the list of potential errors. 😎

**Comment by liximomo** [comment]
@Eagle3386  Please try [1.12.2](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by Eagle3386** [comment]
@liximomo Downloaded, installed, run, worked:
```
[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
(...)
[many more `register command` lines]
(...)
[unchanged config print log]
[warn] ENOENT: no such file or directory, open 'C:\Users\me\.ssh\config' load C:\Users\me\.ssh\config failed
[info] [file-save] X:\WS\Code\file.ext
[trace] handle upload file for X:\WS\Code\file.ext
[debug] Local ident: 'SSH-2.0-ssh2js0.4.2'**
[debug] Client: Trying domain.net on port 22 ...
[debug] Client: Connected
[debug] Remote ident: 'SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u7'
[debug] Outgoing: Writing KEXINIT
(...)
[unchanged key exchange debug log]
(...)
[debug] Outgoing: Writing KEXECDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing USERAUTH_REQUEST (none)
[debug] Client: none auth failed
[debug] Outgoing: Writing USERAUTH_REQUEST (publickey -- check)
[debug] Outgoing: Writing USERAUTH_REQUEST (publickey)
[debug] Outgoing: Writing CHANNEL_OPEN (0, session)
[debug] Outgoing: Writing CHANNEL_REQUEST (0, subsystem: sftp)
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing MKDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing WRITE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[info] local -> remote X:\WS\Code\file.ext
[debug] Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
```

So, updating ssh2js from 0.3.1 to 0.4.2 was everything needed or is there more to it?

Also, what about these two warnings (extracted from log above):
- **`[warn] ENOENT: no such file or directory, open 'C:\Users\me\.ssh\config' load C:\Users\me\.ssh\config failed`**
- **`[debug] Client: none auth failed`** (just after `Writing USERAUTH_REQUEST (publickey -- check)`)

Lastly, can you give an ETA for 1.12.2's official (i. e. "non-debug version") release date? 😎

**Comment by liximomo** [comment]
V1.12.2 has been released.

**Comment by Eagle3386** [comment]
No answers to my questions? 🤔😥

**Comment by liximomo** [comment]
Don't worry about them. SFTP try different ways to connect server. It's normal that some fails.

**Comment by Eagle3386** [comment]
I'm not worried. Instead, I - as a developer myself - would like to know what actually fixed my issue.

So, if possible, please provide such details.
Thanks in advance! ☺

**Comment by wenxiayili** [comment]
> V1.12.2 has been released.

I can not find release 1.12.2 ? Could you tell me？
Now release is 1.12.9
