### ISSUE TITLE
Unable to update symbol linked folders

### ISSUE THREAD

**Issue by pmsmall** [liximomo/vscode-sftp#540]
The error stack is:
[error] Error: Failure
	at SFTPStream._transform (C:\Users\Frank\.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:190:10)
	at SFTPStream._read (C:\Users\Frank\.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SFTPStream.Writable.write (_stream_writable.js:294:11)
	at Channel.ondata (_stream_readable.js:672:20)
	at Channel.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Channel.Readable.push (_stream_readable.js:219:10)
	at SSH2Stream.<anonymous> (C:\Users\Frank\.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2\lib\Channel.js:167:15)
	at SSH2Stream.emit (events.js:182:13)
	at parsePacket (C:\Users\Frank\.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2-streams\lib\ssh.js:3295:10)
	at SSH2Stream._transform (C:\Users\Frank\.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2-streams\lib\ssh.js:693:13)
	at SSH2Stream.Transform._read (_stream_transform.js:190:10)
	at SSH2Stream._read (C:\Users\Frank\.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2-streams\lib\ssh.js:252:15)
	at SSH2Stream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SSH2Stream.Writable.write (_stream_writable.js:294:11)
	at Socket.ondata (_stream_readable.js:672:20)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onread (net.js:636:20) when remote -> local (the local path)

**Comment by Zaczero** [comment]
Same issue, happens when trying to download symlink.
For example I have a symlink called phpmyadmin on my server that redirects to /usr/share/phpmyadmin.
When SFTP tries to download that symlink the error happens.
I think it should skip those.

**Comment by Interfish** [comment]
Same issue, hope the author could fix it soon

**Comment by dmitribatulin** [comment]
Same here... Adding symlinked entities into ignore list - didn't help. 
Reproduced on any version until 1.2.0 (didn't check versions below).

**Comment by nathan0066** [comment]
> The error stack is:
> [error] Error: Failure
> at SFTPStream._transform (C:\Users\Frank.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2-streams\lib\sftp.js:412:27)
> at SFTPStream.Transform._read (_stream_transform.js:190:10)
> at SFTPStream._read (C:\Users\Frank.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2-streams\lib\sftp.js:183:15)
> at SFTPStream.Transform._write (_stream_transform.js:178:12)
> at doWrite (_stream_writable.js:410:12)
> at writeOrBuffer (_stream_writable.js:394:5)
> at SFTPStream.Writable.write (_stream_writable.js:294:11)
> at Channel.ondata (_stream_readable.js:672:20)
> at Channel.emit (events.js:182:13)
> at addChunk (_stream_readable.js:279:12)
> at readableAddChunk (_stream_readable.js:264:11)
> at Channel.Readable.push (_stream_readable.js:219:10)
> at SSH2Stream. (C:\Users\Frank.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2\lib\Channel.js:167:15)
> at SSH2Stream.emit (events.js:182:13)
> at parsePacket (C:\Users\Frank.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2-streams\lib\ssh.js:3295:10)
> at SSH2Stream._transform (C:\Users\Frank.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2-streams\lib\ssh.js:693:13)
> at SSH2Stream.Transform._read (_stream_transform.js:190:10)
> at SSH2Stream._read (C:\Users\Frank.vscode\extensions\liximomo.sftp-1.12.2\node_modules\ssh2-streams\lib\ssh.js:252:15)
> at SSH2Stream.Transform._write (_stream_transform.js:178:12)
> at doWrite (_stream_writable.js:410:12)
> at writeOrBuffer (_stream_writable.js:394:5)
> at SSH2Stream.Writable.write (_stream_writable.js:294:11)
> at Socket.ondata (_stream_readable.js:672:20)
> at Socket.emit (events.js:182:13)
> at addChunk (_stream_readable.js:279:12)
> at readableAddChunk (_stream_readable.js:264:11)
> at Socket.Readable.push (_stream_readable.js:219:10)
> at TCP.onread (net.js:636:20) when remote -> local (the local path)

Hi 
    I also had this problem, but I suddenly found “symlink” can‘t work on FAT or NTFS
