### ISSUE TITLE
A lot of warnings "Can't set modified time to the file because Permission denied"

### ISSUE THREAD

**Issue by tpimh** [liximomo/vscode-sftp#550]
**Describe the bug**
There is no way to disable setting modification time for uploaded files. A lot of warning buzz is produced: `[warn] Can't set modified time to the file because Permission denied`

**To Reproduce**
1. Connect to a server with a user account that doesn't have timestamp modification permission
2. Sync local to remote
3. See a lot of warnings

**Expected behavior**
Having an option to disable timestamp modification.

**Desktop (please complete the following information):**
 - OS: macOS
 - VSCode 1.33.1
 - Extension 1.12.3

**Comment by liximomo** [comment]
The warning will only show once in v1.12.5

**Comment by ikerya** [comment]
It shows in v1.12.9

**Comment by maprangsoft** [comment]
latest v1.12.9 alert when upload file to server

![1621343907709](https://user-images.githubusercontent.com/25447955/118658068-43219e00-b816-11eb-8398-610ccf0e2641.jpg)

**Comment by eurodomenii** [comment]
Same issue for version 1.12.9

**Comment by paddy41601** [comment]
same issue for latest version (1.12.9)

**Comment by Pilot-Marc** [comment]
I get this warning consistently on v1.12.9, Ubuntu 20.04 LTS.  File uploads correctly, timestamp shows server time and not that of the local timestamp.  Error log ...

```
[06-01 11:23:28] [error] Error: No such file
	at SFTPStream._transform (~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
	at SFTPStream._read (~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
	at Channel.ondata (internal/streams/readable.js:719:22)
	at Channel.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Channel.Readable.push (internal/streams/readable.js:223:10)
	at SSH2Stream.<anonymous> (~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2/lib/Channel.js:167:15)
	at SSH2Stream.emit (events.js:315:20)
	at parsePacket (~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:3288:10)
	at SSH2Stream._transform (~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:694:13)
	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
	at SSH2Stream._read (~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
	at Socket.ondata (internal/streams/readable.js:719:22)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote

```

**Comment by the-kid-who-danced** [comment]
+1
macOS :: VSCode 1.56.2

**Comment by romeothethird** [comment]
I found a workaround:

Go inside `~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js` look for `options.emitClose = false;`

Add `options.autoDestroy = false;` after both instances.

**Comment by helmiItsavirus** [comment]
@romeothethird I don't understand where is it. Could you write the solution

```
// For backwards compat do not emit close on destroy.
  options.emitClose = false;
  options.autoDestroy = false;
```
I tried to place there but seems doesn't work

**Comment by ghost** [comment]
Thanks for sharing the workaround and getting to the bottom of this. It was a serious distraction today; gave me the impression files weren't saving, even though they were.

**Comment by howhowcan** [comment]
@helmiItsavirus It works for me after reopening vscode, maybe you can try this.
