### ISSUE TITLE
Error: Can't create directory: File exists

### ISSUE THREAD

**Issue by pluveto** [liximomo/vscode-sftp#558]
**Do you read the FAQ?**
- [v] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
在点击同步到远程之后, 遇到 Error: Can't create directory: File exists 无法同步
**To Reproduce**
1. 填写好正确的配置信息
2. 进行第一次同步, 发现正确.
3. 修改文件, 进行第二次同步, 报错:  Error: Can't create directory: File exists 

**Expected behavior**
不应该报错
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [版本 10.0.17763.503]
 - VSCode 和 Extension 都是最新版

**Extension Logs from Startup** - *required*
```
[05-20 20:52:08] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[05-20 20:52:08] [debug] register command "Config" from "./commandConfig.ts"
[05-20 20:52:08] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[05-20 20:52:08] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[05-20 20:52:08] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[05-20 20:52:08] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[05-20 20:52:08] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[05-20 20:52:08] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[05-20 20:52:08] [debug] register command "Diff" from "./fileCommandDiff.ts"
[05-20 20:52:08] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[05-20 20:52:08] [debug] register command "Download" from "./fileCommandDownload.ts"
[05-20 20:52:08] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[05-20 20:52:08] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[05-20 20:52:08] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[05-20 20:52:08] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[05-20 20:52:08] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[05-20 20:52:08] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[05-20 20:52:08] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[05-20 20:52:08] [debug] register command "List" from "./fileCommandList.ts"
[05-20 20:52:08] [debug] register command "List All" from "./fileCommandListAll.ts"
[05-20 20:52:08] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[05-20 20:52:08] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[05-20 20:52:08] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[05-20 20:52:08] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[05-20 20:52:08] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[05-20 20:52:08] [debug] register command "Upload" from "./fileCommandUpload.ts"
[05-20 20:52:08] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[05-20 20:52:08] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[05-20 20:52:08] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[05-20 20:52:08] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[05-20 20:52:08] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[05-20 20:52:08] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[05-20 20:52:08] [info] config at a:\src\blog\public {"remotePath":"/domains/note.pluvet.com/private_html","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"My Server","host":"103.251.89.195","port":21,"username":"******","password":"******"}
[05-20 20:52:18] [trace] run command 'Sync Local To Remote'
[05-20 20:52:19] [trace] handle sync local ➞ remote for a:\src\blog\public
[05-20 20:52:19] [debug] < '220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\r\n220-You are user number 6 of 50 allowed.\r\n220-Local time is now 20:52. Server port: 21.\r\n220-This is a private system - No anonymous login\r\n220-IPv6 connections are also welcome on this server.\r\n220 You will be disconnected after 15 minutes of inactivity.\r\n'
[05-20 20:52:19] [debug] > USER mccom
[05-20 20:52:19] [debug] < '331 User mccom OK. Password required\r\n'
[05-20 20:52:19] [debug] > PASS ******
[05-20 20:52:19] [debug] < '230-This server supports FXP transfers\r\n230 OK. Current restricted directory is /\r\n'
[05-20 20:52:19] [debug] > FEAT
[05-20 20:52:19] [debug] < '211-Extensions supported:\r\n EPRT\r\n IDLE\r\n MDTM\r\n SIZE\r\n MFMT\r\n REST STREAM\r\n MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;\r\n MLSD\r\n AUTH TLS\r\n PBSZ\r\n PROT\r\n UTF8\r\n TVFS\r\n ESTA\r\n PASV\r\n EPSV\r\n SPSV\r\n ESTP\r\n211 End.\r\n'
[05-20 20:52:19] [debug] > TYPE I
[05-20 20:52:19] [debug] < '200 TYPE is now 8-bit binary\r\n'
[05-20 20:52:19] [debug] > PASV
[05-20 20:52:19] [debug] < '227 Entering Passive Mode (103,251,89,195,138,149)\r\n'
[05-20 20:52:19] [debug] > LIST /domains/note.pluvet.com
[05-20 20:52:19] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 3 matches total\r\n'
[05-20 20:52:19] [debug] > PASV
[05-20 20:52:19] [debug] < '227 Entering Passive Mode (103,251,89,195,137,146)\r\n'
[05-20 20:52:19] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:19] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:19] [debug] > PASV
[05-20 20:52:19] [debug] < '227 Entering Passive Mode (103,251,89,195,140,65)\r\n'
[05-20 20:52:19] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:19] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:19] [debug] < '226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:19] [debug] > PASV
[05-20 20:52:19] [debug] < '227 Entering Passive Mode (103,251,89,195,139,41)\r\n'
[05-20 20:52:19] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:19] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:19] [debug] > PASV
[05-20 20:52:20] [debug] < '227 Entering Passive Mode (103,251,89,195,137,161)\r\n'
[05-20 20:52:20] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:20] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:20] [debug] < '226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:20] [debug] > PASV
[05-20 20:52:20] [debug] < '227 Entering Passive Mode (103,251,89,195,140,104)\r\n'
[05-20 20:52:20] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:20] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:20] [debug] > PASV
[05-20 20:52:20] [debug] < '227 Entering Passive Mode (103,251,89,195,136,244)\r\n'
[05-20 20:52:20] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:20] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:20] [debug] < '226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:20] [debug] > PASV
[05-20 20:52:20] [debug] < '227 Entering Passive Mode (103,251,89,195,139,190)\r\n'
[05-20 20:52:20] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:20] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:20] [debug] < '226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:20] [debug] > PASV
[05-20 20:52:20] [debug] < '227 Entering Passive Mode (103,251,89,195,137,157)\r\n'
[05-20 20:52:20] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:20] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:20] [debug] < '226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:20] [debug] > PASV
[05-20 20:52:20] [debug] < '227 Entering Passive Mode (103,251,89,195,139,57)\r\n'
[05-20 20:52:20] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:20] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:20] [debug] < '226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:20] [debug] > PASV
[05-20 20:52:20] [debug] < '227 Entering Passive Mode (103,251,89,195,139,44)\r\n'
[05-20 20:52:20] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:21] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:21] [debug] < '226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:21] [debug] > PASV
[05-20 20:52:21] [debug] < '227 Entering Passive Mode (103,251,89,195,138,192)\r\n'
[05-20 20:52:21] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:21] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:21] [debug] < '226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:21] [debug] > PASV
[05-20 20:52:21] [debug] < '227 Entering Passive Mode (103,251,89,195,138,118)\r\n'
[05-20 20:52:21] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:21] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:21] [debug] > PASV
[05-20 20:52:21] [debug] < '227 Entering Passive Mode (103,251,89,195,140,152)\r\n'
[05-20 20:52:21] [debug] > LIST /domains/note.pluvet.com/private_html
[05-20 20:52:21] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:21] [debug] < '226-Options: -l \r\n226 12 matches total\r\n'
[05-20 20:52:21] [debug] > MKD /domains/note.pluvet.com/private_html/.vscode
[05-20 20:52:21] [debug] < '550 Can\'t create directory: File exists\r\n'
[05-20 20:52:21] [debug] > PASV
[05-20 20:52:21] [debug] < '227 Entering Passive Mode (103,251,89,195,137,191)\r\n'
[05-20 20:52:21] [debug] > LIST /domains/note.pluvet.com/private_html/2019
[05-20 20:52:21] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:21] [debug] > PASV
[05-20 20:52:21] [debug] < '227 Entering Passive Mode (103,251,89,195,138,182)\r\n'
[05-20 20:52:21] [debug] > LIST /domains/note.pluvet.com/private_html/about
[05-20 20:52:21] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:21] [debug] < '226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:21] [debug] > PASV
[05-20 20:52:21] [debug] < '227 Entering Passive Mode (103,251,89,195,137,192)\r\n'
[05-20 20:52:21] [debug] > LIST /domains/note.pluvet.com/private_html/archives
[05-20 20:52:22] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:22] [debug] > PASV
[05-20 20:52:22] [debug] < '227 Entering Passive Mode (103,251,89,195,140,28)\r\n'
[05-20 20:52:22] [debug] > LIST /domains/note.pluvet.com/private_html/css
[05-20 20:52:22] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 5 matches total\r\n'
[05-20 20:52:22] [debug] > PASV
[05-20 20:52:22] [debug] < '227 Entering Passive Mode (103,251,89,195,139,179)\r\n'
[05-20 20:52:22] [debug] > LIST /domains/note.pluvet.com/private_html/fancybox
[05-20 20:52:22] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:22] [debug] < '226-Options: -l \r\n226 10 matches total\r\n'
[05-20 20:52:22] [debug] > PASV
[05-20 20:52:22] [debug] < '227 Entering Passive Mode (103,251,89,195,138,137)\r\n'
[05-20 20:52:22] [debug] > LIST /domains/note.pluvet.com/private_html/fonts
[05-20 20:52:22] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:22] [debug] < '226-Options: -l \r\n226 18 matches total\r\n'
[05-20 20:52:22] [debug] > PASV
[05-20 20:52:22] [debug] < '227 Entering Passive Mode (103,251,89,195,136,240)\r\n'
[05-20 20:52:22] [debug] > LIST /domains/note.pluvet.com/private_html/images
[05-20 20:52:22] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:22] [debug] > PASV
[05-20 20:52:22] [debug] < '227 Entering Passive Mode (103,251,89,195,140,9)\r\n'
[05-20 20:52:22] [debug] > LIST /domains/note.pluvet.com/private_html/js
[05-20 20:52:22] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 7 matches total\r\n'
[05-20 20:52:22] [debug] > PASV
[05-20 20:52:22] [debug] < '227 Entering Passive Mode (103,251,89,195,139,243)\r\n'
[05-20 20:52:22] [debug] > LIST /domains/note.pluvet.com/private_html/lib
[05-20 20:52:22] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 5 matches total\r\n'
[05-20 20:52:22] [debug] > PASV
[05-20 20:52:22] [debug] < '227 Entering Passive Mode (103,251,89,195,138,253)\r\n'
[05-20 20:52:23] [debug] > LIST /domains/note.pluvet.com/private_html/sass
[05-20 20:52:23] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:23] [debug] > PASV
[05-20 20:52:23] [debug] < '227 Entering Passive Mode (103,251,89,195,139,238)\r\n'
[05-20 20:52:23] [debug] > LIST /domains/note.pluvet.com/private_html/stylesheets
[05-20 20:52:23] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 0 matches total\r\n'
[05-20 20:52:23] [debug] > MKD /domains/note.pluvet.com/private_html
[05-20 20:52:23] [debug] < '550 Can\'t create directory: File exists\r\n'
[05-20 20:52:23] [debug] > PASV
[05-20 20:52:23] [debug] < '227 Entering Passive Mode (103,251,89,195,138,15)\r\n'
[05-20 20:52:23] [debug] > LIST /domains/note.pluvet.com/private_html/2019
[05-20 20:52:23] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:23] [debug] < '226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:23] [debug] > PASV
[05-20 20:52:23] [debug] < '227 Entering Passive Mode (103,251,89,195,138,139)\r\n'
[05-20 20:52:23] [debug] > LIST /domains/note.pluvet.com/private_html/archives
[05-20 20:52:23] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:23] [debug] > PASV
[05-20 20:52:23] [debug] < '227 Entering Passive Mode (103,251,89,195,137,164)\r\n'
[05-20 20:52:23] [debug] > LIST /domains/note.pluvet.com/private_html/css
[05-20 20:52:23] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 5 matches total\r\n'
[05-20 20:52:23] [debug] > PASV
[05-20 20:52:23] [debug] < '227 Entering Passive Mode (103,251,89,195,139,165)\r\n'
[05-20 20:52:23] [debug] > LIST /domains/note.pluvet.com/private_html/css
[05-20 20:52:23] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:23] [debug] < '226-Options: -l \r\n226 5 matches total\r\n'
[05-20 20:52:23] [debug] > PASV
[05-20 20:52:23] [debug] < '227 Entering Passive Mode (103,251,89,195,140,84)\r\n'
[05-20 20:52:23] [debug] > LIST /domains/note.pluvet.com/private_html/fancybox
[05-20 20:52:24] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:24] [debug] < '226-Options: -l \r\n226 10 matches total\r\n'
[05-20 20:52:24] [debug] > PASV
[05-20 20:52:24] [debug] < '227 Entering Passive Mode (103,251,89,195,139,166)\r\n'
[05-20 20:52:24] [debug] > LIST /domains/note.pluvet.com/private_html/lib
[05-20 20:52:24] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 5 matches total\r\n'
[05-20 20:52:24] [debug] > PASV
[05-20 20:52:24] [debug] < '227 Entering Passive Mode (103,251,89,195,139,214)\r\n'
[05-20 20:52:24] [debug] > LIST /domains/note.pluvet.com/private_html/lib
[05-20 20:52:24] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 5 matches total\r\n'
[05-20 20:52:24] [debug] > PASV
[05-20 20:52:24] [debug] < '227 Entering Passive Mode (103,251,89,195,137,23)\r\n'
[05-20 20:52:24] [debug] > LIST /domains/note.pluvet.com/private_html/lib
[05-20 20:52:24] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:24] [debug] < '226-Options: -l \r\n226 5 matches total\r\n'
[05-20 20:52:24] [debug] > PASV
[05-20 20:52:24] [debug] < '227 Entering Passive Mode (103,251,89,195,137,1)\r\n'
[05-20 20:52:24] [debug] > LIST /domains/note.pluvet.com/private_html/lib
[05-20 20:52:24] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 5 matches total\r\n'
[05-20 20:52:24] [debug] > PASV
[05-20 20:52:24] [debug] < '227 Entering Passive Mode (103,251,89,195,137,254)\r\n'
[05-20 20:52:24] [debug] > LIST /domains/note.pluvet.com/private_html/lib
[05-20 20:52:24] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 5 matches total\r\n'
[05-20 20:52:24] [debug] > MKD /domains/note.pluvet.com
[05-20 20:52:24] [debug] < '550 Can\'t create directory: File exists\r\n'
[05-20 20:52:24] [debug] > PASV
[05-20 20:52:24] [debug] < '227 Entering Passive Mode (103,251,89,195,138,78)\r\n'
[05-20 20:52:24] [debug] > LIST /domains/note.pluvet.com/private_html/2019/05
[05-20 20:52:24] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:24] [debug] > PASV
[05-20 20:52:25] [debug] < '227 Entering Passive Mode (103,251,89,195,136,246)\r\n'
[05-20 20:52:25] [debug] > LIST /domains/note.pluvet.com/private_html/archives/2019
[05-20 20:52:25] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:25] [debug] < '226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:25] [debug] > PASV
[05-20 20:52:25] [debug] < '227 Entering Passive Mode (103,251,89,195,140,91)\r\n'
[05-20 20:52:25] [debug] > LIST /domains/note.pluvet.com/private_html/css/fonts
[05-20 20:52:25] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:25] [debug] < '226-Options: -l \r\n226 5 matches total\r\n'
[05-20 20:52:25] [debug] > PASV
[05-20 20:52:25] [debug] < '227 Entering Passive Mode (103,251,89,195,139,250)\r\n'
[05-20 20:52:25] [debug] > LIST /domains/note.pluvet.com/private_html/css/images
[05-20 20:52:25] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:25] [debug] < '226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:25] [debug] > PASV
[05-20 20:52:25] [debug] < '227 Entering Passive Mode (103,251,89,195,137,193)\r\n'
[05-20 20:52:25] [debug] > LIST /domains/note.pluvet.com/private_html/fancybox/helpers
[05-20 20:52:25] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 6 matches total\r\n'
[05-20 20:52:25] [debug] > PASV
[05-20 20:52:25] [debug] < '227 Entering Passive Mode (103,251,89,195,138,192)\r\n'
[05-20 20:52:25] [debug] > LIST /domains/note.pluvet.com/private_html/lib/font-awesome
[05-20 20:52:25] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:25] [debug] > PASV
[05-20 20:52:25] [debug] < '227 Entering Passive Mode (103,251,89,195,140,39)\r\n'
[05-20 20:52:25] [debug] > LIST /domains/note.pluvet.com/private_html/lib/jquery
[05-20 20:52:25] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:25] [debug] < '226-Options: -l \r\n226 0 matches total\r\n'
[05-20 20:52:25] [debug] > PASV
[05-20 20:52:25] [debug] < '227 Entering Passive Mode (103,251,89,195,137,155)\r\n'
[05-20 20:52:26] [debug] > LIST /domains/note.pluvet.com/private_html/lib/justified-gallery
[05-20 20:52:26] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:26] [debug] < '226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:26] [debug] > PASV
[05-20 20:52:26] [debug] < '227 Entering Passive Mode (103,251,89,195,139,58)\r\n'
[05-20 20:52:26] [debug] > LIST /domains/note.pluvet.com/private_html/lib/meslo-LG
[05-20 20:52:26] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 0 matches total\r\n'
[05-20 20:52:26] [debug] > PASV
[05-20 20:52:26] [debug] < '227 Entering Passive Mode (103,251,89,195,140,49)\r\n'
[05-20 20:52:26] [debug] > LIST /domains/note.pluvet.com/private_html/lib/vazir-font
[05-20 20:52:26] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:26] [debug] < '226-Options: -l \r\n226 0 matches total\r\n'
[05-20 20:52:26] [debug] > MKD /domains
[05-20 20:52:26] [debug] < '550 Can\'t create directory: File exists\r\n'
[05-20 20:52:26] [debug] > PASV
[05-20 20:52:26] [debug] < '227 Entering Passive Mode (103,251,89,195,139,188)\r\n'
[05-20 20:52:26] [debug] > LIST /domains/note.pluvet.com/private_html/2019/05
[05-20 20:52:26] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:26] [debug] > PASV
[05-20 20:52:26] [debug] < '227 Entering Passive Mode (103,251,89,195,140,86)\r\n'
[05-20 20:52:26] [debug] > LIST /domains/note.pluvet.com/private_html/archives/2019
[05-20 20:52:26] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:26] [debug] < '226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:26] [debug] > PASV
[05-20 20:52:26] [debug] < '227 Entering Passive Mode (103,251,89,195,138,140)\r\n'
[05-20 20:52:26] [debug] > LIST /domains/note.pluvet.com/private_html/lib/font-awesome
[05-20 20:52:26] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:26] [debug] > PASV
[05-20 20:52:26] [debug] < '227 Entering Passive Mode (103,251,89,195,138,36)\r\n'
[05-20 20:52:26] [debug] > LIST /domains/note.pluvet.com/private_html/lib/font-awesome
[05-20 20:52:27] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:27] [debug] > PASV
[05-20 20:52:27] [debug] < '227 Entering Passive Mode (103,251,89,195,139,5)\r\n'
[05-20 20:52:27] [debug] > LIST /domains/note.pluvet.com/private_html/lib/justified-gallery
[05-20 20:52:27] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:27] [debug] > PASV
[05-20 20:52:27] [debug] < '227 Entering Passive Mode (103,251,89,195,138,244)\r\n'
[05-20 20:52:27] [debug] > LIST /domains/note.pluvet.com/private_html/lib/justified-gallery
[05-20 20:52:27] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 2 matches total\r\n'
[05-20 20:52:27] [debug] > MKD /
[05-20 20:52:27] [debug] < '550 Can\'t create directory: File exists\r\n'
[05-20 20:52:27] [debug] > PASV
[05-20 20:52:27] [error] Error: Can't create directory: File exists
	at v (C:\Users\zhangzijing\.vscode\extensions\liximomo.sftp-1.12.6\dist\extension.js:70:110480)
	at d.<anonymous> (C:\Users\zhangzijing\.vscode\extensions\liximomo.sftp-1.12.6\dist\extension.js:70:111203)
	at d.emit (events.js:182:13)
	at d.module.exports.d._write (C:\Users\zhangzijing\.vscode\extensions\liximomo.sftp-1.12.6\dist\extension.js:70:124025)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at d.Writable.write (_stream_writable.js:294:11)
	at Socket.p (C:\Users\zhangzijing\.vscode\extensions\liximomo.sftp-1.12.6\dist\extension.js:70:113574)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onread (net.js:636:20) 
[05-20 20:52:27] [debug] < '227 Entering Passive Mode (103,251,89,195,138,65)\r\n'
[05-20 20:52:27] [debug] > LIST /domains/note.pluvet.com/private_html/2019/05/20
[05-20 20:52:27] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:27] [debug] > PASV
[05-20 20:52:27] [debug] < '227 Entering Passive Mode (103,251,89,195,138,223)\r\n'
[05-20 20:52:27] [debug] > LIST /domains/note.pluvet.com/private_html/archives/2019/05
[05-20 20:52:27] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:27] [debug] < '226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:27] [debug] > PASV
[05-20 20:52:27] [debug] < '227 Entering Passive Mode (103,251,89,195,140,96)\r\n'
[05-20 20:52:27] [debug] > LIST /domains/note.pluvet.com/private_html/lib/font-awesome/css
[05-20 20:52:27] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 0 matches total\r\n'
[05-20 20:52:27] [debug] > PASV
[05-20 20:52:27] [debug] < '227 Entering Passive Mode (103,251,89,195,138,62)\r\n'
[05-20 20:52:27] [debug] > LIST /domains/note.pluvet.com/private_html/lib/font-awesome/webfonts
[05-20 20:52:27] [debug] < '150 Accepted data connection\r\n'
[05-20 20:52:27] [debug] < '226-Options: -l \r\n226 0 matches total\r\n'
[05-20 20:52:27] [debug] > PASV
[05-20 20:52:28] [debug] < '227 Entering Passive Mode (103,251,89,195,138,145)\r\n'
[05-20 20:52:28] [debug] > LIST /domains/note.pluvet.com/private_html/lib/justified-gallery/css
[05-20 20:52:28] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 0 matches total\r\n'
[05-20 20:52:28] [debug] > PASV
[05-20 20:52:28] [debug] < '227 Entering Passive Mode (103,251,89,195,137,117)\r\n'
[05-20 20:52:28] [debug] > LIST /domains/note.pluvet.com/private_html/lib/justified-gallery/js
[05-20 20:52:28] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 0 matches total\r\n'
[05-20 20:52:28] [debug] > PASV
[05-20 20:52:28] [debug] < '227 Entering Passive Mode (103,251,89,195,137,0)\r\n'
[05-20 20:52:28] [debug] > LIST /domains/note.pluvet.com/private_html/2019/05/20
[05-20 20:52:28] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:28] [debug] > PASV
[05-20 20:52:28] [debug] < '227 Entering Passive Mode (103,251,89,195,138,208)\r\n'
[05-20 20:52:28] [debug] > LIST /domains/note.pluvet.com/private_html/2019/05/20/hello-world
[05-20 20:52:28] [debug] < '150 Accepted data connection\r\n226-Options: -l \r\n226 1 matches total\r\n'
[05-20 20:52:38] [debug] > NOOP
[05-20 20:52:38] [debug] < '200 Zzz...\r\n'
```

**Comment by liximomo** [comment]
Please try [1.12.7-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).
