### ISSUE TITLE
Error: No such file

### ISSUE THREAD

**Issue by bgyoo91** [liximomo/vscode-sftp#569]
**Do you read the FAQ?**
- [v] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
"SFTP: Open SSH in Terminal" works fine.
But other commands do not work (SFTP: Download active file .... )
I created the rsa key and added the public key to the server authorized_keys.
here is my ssh config file
```
Host my-server
    HostName ipadress
    Port 22
    User bgyoo
    PubKeyAuthentication yes
    IdentityFile ~/.ssh/id_rsa
    IdentitiesOnly yes
    ForwardX11 no
```
sftp.json
```
{
    "name": "My Server",
    "host": "my-server",
    "protocol": "sftp",
    "port": 22,
    "username": "bgyoo",
    "remotePath": "/var/services/homes/bgyoo/www",
    "uploadOnSave": false,
    "privateKeyPath": "/home/bgyoo/.ssh/id_rsa",
    "ignore": [
        ".vscode",
        ".git",
        ".DS_Store",
        ".sftp.json"
    ]
}
```
and here is sftp debug log
```
[06-03 15:14:11] [trace] run command 'Download Project'
[06-03 15:14:13] [trace] handle download folder for /home/bgyoo/Workspace/www
[06-03 15:14:13] [debug] Local ident: 'SSH-2.0-ssh2js0.4.2'
[06-03 15:14:13] [debug] Client: Trying bgyoo.iptime.org on port 22 ...
[06-03 15:14:13] [debug] Client: Connected
[06-03 15:14:13] [debug] Remote ident: 'SSH-2.0-OpenSSH_7.4'
[06-03 15:14:13] [debug] Outgoing: Writing KEXINIT
[06-03 15:14:13] [debug] DEBUG: Comparing KEXINITs ...
[06-03 15:14:13] [debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[06-03 15:14:13] [debug] (remote) KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
[06-03 15:14:13] [debug] KEX algorithm: ecdh-sha2-nistp256
[06-03 15:14:13] [debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[06-03 15:14:13] [debug] (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[06-03 15:14:13] [debug] Host key format: ssh-rsa
[06-03 15:14:13] [debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[06-03 15:14:13] [debug] (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[06-03 15:14:13] [debug] Client->Server Cipher: aes128-ctr
[06-03 15:14:13] [debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[06-03 15:14:13] [debug] (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[06-03 15:14:13] [debug] Server->Client Cipher: aes128-ctr
[06-03 15:14:13] [debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[06-03 15:14:13] [debug] (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[06-03 15:14:13] [debug] Client->Server HMAC algorithm: hmac-sha2-256
[06-03 15:14:13] [debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[06-03 15:14:13] [debug] (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[06-03 15:14:13] [debug] Server->Client HMAC algorithm: hmac-sha2-256
[06-03 15:14:13] [debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[06-03 15:14:13] [debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[06-03 15:14:13] [debug] Client->Server compression algorithm: none
[06-03 15:14:13] [debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[06-03 15:14:13] [debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[06-03 15:14:13] [debug] Server->Client compression algorithm: none
[06-03 15:14:13] [debug] Outgoing: Writing KEXECDH_INIT
[06-03 15:14:13] [debug] DEBUG: Checking host key format
[06-03 15:14:13] [debug] DEBUG: Checking signature format
[06-03 15:14:13] [debug] DEBUG: Verifying host fingerprint
[06-03 15:14:13] [debug] DEBUG: Host accepted by default (no verification)
[06-03 15:14:13] [debug] DEBUG: Verifying signature
[06-03 15:14:13] [debug] Outgoing: Writing NEWKEYS
[06-03 15:14:13] [debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[06-03 15:14:13] [debug] Outgoing: Writing USERAUTH_REQUEST (none)
[06-03 15:14:13] [debug] Client: none auth failed
[06-03 15:14:13] [debug] Outgoing: Writing USERAUTH_REQUEST (publickey -- check)
[06-03 15:14:13] [debug] Outgoing: Writing USERAUTH_REQUEST (publickey)
[06-03 15:14:13] [debug] Outgoing: Writing CHANNEL_OPEN (0, session)
[06-03 15:14:13] [debug] Outgoing: Writing CHANNEL_REQUEST (0, subsystem: sftp)
[06-03 15:14:13] [debug] Outgoing: Writing CHANNEL_DATA (0)
[06-03 15:14:13] [debug] Outgoing: Writing LSTAT
[06-03 15:14:13] [debug] Outgoing: Writing CHANNEL_DATA (0)
[06-03 15:14:13] [error] Error: No such file
	at SFTPStream._transform (/home/bgyoo/.vscode/extensions/liximomo.sftp-1.12.7/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:190:10)
	at SFTPStream._read (/home/bgyoo/.vscode/extensions/liximomo.sftp-1.12.7/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SFTPStream.Writable.write (_stream_writable.js:294:11)
	at Channel.ondata (_stream_readable.js:672:20)
	at Channel.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Channel.Readable.push (_stream_readable.js:219:10)
	at SSH2Stream.<anonymous> (/home/bgyoo/.vscode/extensions/liximomo.sftp-1.12.7/node_modules/ssh2/lib/Channel.js:167:15)
	at SSH2Stream.emit (events.js:182:13)
	at parsePacket (/home/bgyoo/.vscode/extensions/liximomo.sftp-1.12.7/node_modules/ssh2-streams/lib/ssh.js:3295:10)
	at SSH2Stream._transform (/home/bgyoo/.vscode/extensions/liximomo.sftp-1.12.7/node_modules/ssh2-streams/lib/ssh.js:693:13)
	at SSH2Stream.Transform._read (_stream_transform.js:190:10)
	at SSH2Stream._read (/home/bgyoo/.vscode/extensions/liximomo.sftp-1.12.7/node_modules/ssh2-streams/lib/ssh.js:252:15)
	at SSH2Stream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SSH2Stream.Writable.write (_stream_writable.js:294:11)
	at Socket.ondata (_stream_readable.js:672:20)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onread (net.js:636:20) 
```

local dir `~/www/.vscode`
local ssh path` ~/.ssh/id_rsa`

server dir `/var/services/homes/bgyoo/www`
server ssh dir `/var/services/homes/bgyoo/.ssh/authorized_keys`

**Desktop (please complete the following information):**
 - OS: [Linux]
 - VSCode Version [1.34.0]
 - Extension Version [1.12.7]

**Comment by jbrwilkinson** [comment]
x-ref #266

**Comment by rivasspro** [comment]
Bajar la versión a 1.55 vscode es la solución! Ya después que arreglen ese detalle en las actualizaciones, mientras también desactive las actualizaciones automáticas.
https://code.visualstudio.com/updates/v1_55
![Screenshot_20210511-012236_Chrome](https://user-images.githubusercontent.com/84003987/117768098-80bf6f00-b1f7-11eb-9a32-14aef527bdfd.jpg)
