### ISSUE TITLE
Handshake failed: signature verification failed

### ISSUE THREAD

**Issue by gich14** [liximomo/vscode-sftp#610]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**

Trying to upload a file and get error.

**To Reproduce**
1. Clickright on a modified file.
2. Select Upload file
3. See error

[07-30 17:20:20] [trace] run command 'Upload File'
[07-30 17:20:20] [trace] handle upload file for d:\Profiles\gseumois\_ssg\_svn_repo\expdbreport_1.1\section\show_database.php
[07-30 17:20:20] [debug] Local ident: 'SSH-2.0-ssh2js0.4.2'
[07-30 17:20:20] [debug] Client: Trying lmarcrndadm01.ptx.fr.sopra on port 22 ...
[07-30 17:20:20] [debug] Client: Connected
[07-30 17:20:20] [debug] Remote ident: 'SSH-2.0-OpenSSH_6.6.1'
[07-30 17:20:20] [debug] Outgoing: Writing KEXINIT
[07-30 17:20:20] [debug] DEBUG: Comparing KEXINITs ...
[07-30 17:20:20] [debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[07-30 17:20:20] [debug] (remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[07-30 17:20:20] [debug] KEX algorithm: ecdh-sha2-nistp256
[07-30 17:20:20] [debug] (local) Host key formats: ssh-dss
[07-30 17:20:20] [debug] (remote) Host key formats: ssh-dss
[07-30 17:20:20] [debug] Host key format: ssh-dss
[07-30 17:20:20] [debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[07-30 17:20:20] [debug] (remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[07-30 17:20:20] [debug] Client->Server Cipher: aes128-ctr
[07-30 17:20:20] [debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[07-30 17:20:20] [debug] (remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[07-30 17:20:20] [debug] Server->Client Cipher: aes128-ctr
[07-30 17:20:20] [debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-30 17:20:20] [debug] (remote) Client->Server HMAC algorithms: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[07-30 17:20:20] [debug] Client->Server HMAC algorithm: hmac-sha2-256
[07-30 17:20:20] [debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-30 17:20:20] [debug] (remote) Server->Client HMAC algorithms: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[07-30 17:20:20] [debug] Server->Client HMAC algorithm: hmac-sha2-256
[07-30 17:20:20] [debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[07-30 17:20:20] [debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[07-30 17:20:20] [debug] Client->Server compression algorithm: none
[07-30 17:20:20] [debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[07-30 17:20:20] [debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[07-30 17:20:20] [debug] Server->Client compression algorithm: none
[07-30 17:20:20] [debug] Outgoing: Writing KEXECDH_INIT
[07-30 17:20:20] [debug] DEBUG: Checking host key format
[07-30 17:20:20] [debug] DEBUG: Checking signature format
[07-30 17:20:20] [debug] DEBUG: Verifying host fingerprint
[07-30 17:20:20] [debug] DEBUG: Host accepted by default (no verification)
[07-30 17:20:20] [debug] DEBUG: Verifying signature
[07-30 17:20:20] [debug] DEBUG: Signature verification failed
[07-30 17:20:20] [debug] Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)
[07-30 17:20:20] [debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[07-30 17:20:20] [debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[07-30 17:20:20] [debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[07-30 17:20:20] [error] Error: [lmarcrndadm01.ptx.fr.sopra]: Handshake failed: signature verification failed
	at Client.module.exports._connectSSHClient.e.on.on.e (d:\Profiles\gseumois\_soft\VSCode\data\extensions\liximomo.sftp-1.12.7\dist\extension.js:70:107136)
	at Client.emit (events.js:187:15)
	at SSH2Stream.<anonymous> (d:\Profiles\gseumois\_soft\VSCode\data\extensions\liximomo.sftp-1.12.7\node_modules\ssh2\lib\client.js:357:10)
	at SSH2Stream.emit (events.js:187:15)
	at onKEXDH_REPLY (d:\Profiles\gseumois\_soft\VSCode\data\extensions\liximomo.sftp-1.12.7\node_modules\ssh2-streams\lib\ssh.js:2919:10)
	at SSH2Stream.<anonymous> (d:\Profiles\gseumois\_soft\VSCode\data\extensions\liximomo.sftp-1.12.7\node_modules\ssh2-streams\lib\ssh.js:216:45)
	at SSH2Stream.emit (events.js:182:13)
	at parse_KEXDH_REPLY (d:\Profiles\gseumois\_soft\VSCode\data\extensions\liximomo.sftp-1.12.7\node_modules\ssh2-streams\lib\ssh.js:4066:8)
	at parse_KEX (d:\Profiles\gseumois\_soft\VSCode\data\extensions\liximomo.sftp-1.12.7\node_modules\ssh2-streams\lib\ssh.js:4028:14)
	at parsePacket (d:\Profiles\gseumois\_soft\VSCode\data\extensions\liximomo.sftp-1.12.7\node_modules\ssh2-streams\lib\ssh.js:3863:12)
	at SSH2Stream._transform (d:\Profiles\gseumois\_soft\VSCode\data\extensions\liximomo.sftp-1.12.7\node_modules\ssh2-streams\lib\ssh.js:693:13)
	at SSH2Stream.Transform._read (_stream_transform.js:190:10)
	at SSH2Stream._read (d:\Profiles\gseumois\_soft\VSCode\data\extensions\liximomo.sftp-1.12.7\node_modules\ssh2-streams\lib\ssh.js:252:15)
	at SSH2Stream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SSH2Stream.Writable.write (_stream_writable.js:294:11)
	at Socket.ondata (_stream_readable.js:666:20)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) 

OS: Windows_NT x64 10.0.18362
 - VSCode Version: 1.36.1
 - Extension Version 1.12.7

**Comment by Snake66GH** [comment]
Currently, I am facing the same problem as the above-mentioned one:

It does not matter if I use username and password or username and private key for the authentication, the result is the same. Moreover, ssh connection normally works using a command prompt, PuTTy and PowerShell.

[08-29 15:10:16] [trace] run command 'Sync Remote To Local'
[08-29 15:10:16] [info] Using profile: DSIM LOCAL
[08-29 15:10:16] [trace] handle sync remote ➞ local for c:\Users\ec071\Documents\Visual Studio Code\PROFILES\DSIM\SRC
[08-29 15:10:16] [debug] Local ident: 'SSH-2.0-ssh2js0.4.2'
[08-29 15:10:16] [debug] Client: Trying dfd006.xeop.de on port 22 ...
[08-29 15:10:16] [debug] Client: Connected
[08-29 15:10:16] [debug] Remote ident: 'SSH-2.0-3.2.0 SSH OpenVMS V5.5 VMS_sftp_version 3'
[08-29 15:10:16] [debug] Outgoing: Writing KEXINIT
[08-29 15:10:16] [debug] DEBUG: Comparing KEXINITs ...
[08-29 15:10:16] [debug] (local) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
[08-29 15:10:16] [debug] (remote) KEX algorithms: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[08-29 15:10:16] [debug] KEX algorithm: diffie-hellman-group14-sha1
[08-29 15:10:16] [debug] (local) Host key formats: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[08-29 15:10:16] [debug] (remote) Host key formats: ssh-dss
[08-29 15:10:16] [debug] Host key format: ssh-dss
[08-29 15:10:16] [debug] (local) Client->Server ciphers: 3des-cbc,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[08-29 15:10:16] [debug] (remote) Client->Server ciphers: aes128-cbc,3des-cbc,twofish128-cbc,cast128-cbc,twofish-cbc,blowfish-cbc,aes192-cbc,aes256-cbc,twofish192-cbc,twofish256-cbc,arcfour,aes128-ctr,aes192-ctr,aes256-ctr,des-cbc@ssh.com,rc2-cbc@ssh.com
[08-29 15:10:16] [debug] Client->Server Cipher: 3des-cbc
[08-29 15:10:16] [debug] (local) Server->Client ciphers: 3des-cbc,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[08-29 15:10:16] [debug] (remote) Server->Client ciphers: aes128-cbc,3des-cbc,twofish128-cbc,cast128-cbc,twofish-cbc,blowfish-cbc,aes192-cbc,aes256-cbc,twofish192-cbc,twofish256-cbc,arcfour,aes128-ctr,aes192-ctr,aes256-ctr,des-cbc@ssh.com,rc2-cbc@ssh.com
[08-29 15:10:16] [debug] Server->Client Cipher: 3des-cbc
[08-29 15:10:16] [debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-29 15:10:16] [debug] (remote) Client->Server HMAC algorithms: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-sha256@ssh.com,hmac-sha256-96@ssh.com,hmac-ripemd160@ssh.com,hmac-ripemd160-96@ssh.com,hmac-tiger128@ssh.com,hmac-tiger128-96@ssh.com,hmac-tiger160@ssh.com,hmac-tiger160-96@ssh.com,hmac-tiger192@ssh.com,hmac-tiger192-96@ssh.com
[08-29 15:10:16] [debug] Client->Server HMAC algorithm: hmac-sha1
[08-29 15:10:16] [debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-29 15:10:16] [debug] (remote) Server->Client HMAC algorithms: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-sha256@ssh.com,hmac-sha256-96@ssh.com,hmac-ripemd160@ssh.com,hmac-ripemd160-96@ssh.com,hmac-tiger128@ssh.com,hmac-tiger128-96@ssh.com,hmac-tiger160@ssh.com,hmac-tiger160-96@ssh.com,hmac-tiger192@ssh.com,hmac-tiger192-96@ssh.com
[08-29 15:10:16] [debug] Server->Client HMAC algorithm: hmac-sha1
[08-29 15:10:16] [debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[08-29 15:10:16] [debug] (remote) Client->Server compression algorithms: none,zlib
[08-29 15:10:16] [debug] Client->Server compression algorithm: none
[08-29 15:10:16] [debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[08-29 15:10:16] [debug] (remote) Server->Client compression algorithms: none,zlib
[08-29 15:10:16] [debug] Server->Client compression algorithm: none
[08-29 15:10:16] [debug] Outgoing: Writing KEXDH_INIT
[08-29 15:10:16] [debug] DEBUG: Checking host key format
[08-29 15:10:16] [debug] DEBUG: Checking signature format
[08-29 15:10:16] [debug] DEBUG: Verifying host fingerprint
[08-29 15:10:16] [debug] DEBUG: Host accepted by default (no verification)
[08-29 15:10:16] [debug] DEBUG: Verifying signature
[08-29 15:10:16] [debug] DEBUG: Signature verification failed
[08-29 15:10:16] [debug] Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)
[08-29 15:10:16] [debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[08-29 15:10:16] [debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[08-29 15:10:16] [debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[08-29 15:10:16] [error] Error: [dfd006.xeop.de]: Handshake failed: signature verification failed
	at Client.module.exports._connectSSHClient.e.on.on.e (C:\Users\ec071\.vscode\extensions\liximomo.sftp-1.12.8\dist\extension.js:70:107250)
	at Client.emit (events.js:187:15)
	at SSH2Stream.<anonymous> (C:\Users\ec071\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2\lib\client.js:357:10)
	at SSH2Stream.emit (events.js:187:15)
	at onKEXDH_REPLY (C:\Users\ec071\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\ssh.js:2919:10)
	at SSH2Stream.<anonymous> (C:\Users\ec071\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\ssh.js:216:45)
	at SSH2Stream.emit (events.js:182:13)
	at parse_KEXDH_REPLY (C:\Users\ec071\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\ssh.js:4066:8)
	at parse_KEX (C:\Users\ec071\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\ssh.js:4028:14)
	at parsePacket (C:\Users\ec071\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\ssh.js:3863:12)
	at SSH2Stream._transform (C:\Users\ec071\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\ssh.js:693:13)
	at SSH2Stream.Transform._read (_stream_transform.js:190:10)
	at SSH2Stream._read (C:\Users\ec071\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\ssh.js:252:15)
	at SSH2Stream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SSH2Stream.Writable.write (_stream_writable.js:294:11)
	at Socket.ondata (_stream_readable.js:666:20)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
