### ISSUE TITLE
When i try to connect and download files from my remote server, i receive to following warning followed by a bunch of errors. --- [08-14 09:31:59] [warn] ENOENT: no such file or directory, open 'C:\Users\MY-PC\.ssh\config' load C:\Users\MY-PC\.ssh\config failed

### ISSUE THREAD

**Issue by ykeita** [liximomo/vscode-sftp#623]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**

**To Reproduce**
1. Create a sftp.json file
2. press F1 then select project from the SFTP: List All
3. Choose project folder

**Expected behavior**
Project is supposed to be downloaded from remote server to local workspace

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win
 - VSCode Version 1.37.0
 - Extension Version 1.12.8

**Extension Logs from Startup** - *required*
[08-14 09:31:46] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[08-14 09:31:46] [debug] register command "Config" from "./commandConfig.ts"
[08-14 09:31:46] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[08-14 09:31:46] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[08-14 09:31:46] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[08-14 09:31:46] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[08-14 09:31:46] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[08-14 09:31:46] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[08-14 09:31:46] [debug] register command "Diff" from "./fileCommandDiff.ts"
[08-14 09:31:46] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[08-14 09:31:46] [debug] register command "Download" from "./fileCommandDownload.ts"
[08-14 09:31:46] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[08-14 09:31:46] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[08-14 09:31:46] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[08-14 09:31:46] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[08-14 09:31:46] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[08-14 09:31:46] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[08-14 09:31:46] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[08-14 09:31:46] [debug] register command "List" from "./fileCommandList.ts"
[08-14 09:31:46] [debug] register command "List All" from "./fileCommandListAll.ts"
[08-14 09:31:46] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[08-14 09:31:46] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[08-14 09:31:46] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[08-14 09:31:46] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[08-14 09:31:46] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[08-14 09:31:46] [debug] register command "Upload" from "./fileCommandUpload.ts"
[08-14 09:31:46] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[08-14 09:31:46] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[08-14 09:31:46] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[08-14 09:31:46] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[08-14 09:31:46] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[08-14 09:31:46] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[08-14 09:31:46] [info] config at d:\Workspace\My App Dev {"remotePath":"/var/app/current","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"My App Dev","host":"ec2-ip.compute-1.amazonaws.com","port":22,"username":"******","privateKeyPath":"C:\\Users\\My-PC\\.ssh\\ssh-k072319"}
[08-14 09:31:59] [trace] run command 'List All'
[08-14 09:31:59] [warn] ENOENT: no such file or directory, open 'C:\Users\My-PC\.ssh\config' load C:\Users\My-PC\.ssh\config failed
[08-14 09:32:05] [debug] Local ident: 'SSH-2.0-ssh2js0.4.2'
[08-14 09:32:05] [debug] Client: Trying ec2-ip.compute-1.amazonaws.com on port 22 ...
[08-14 09:32:05] [debug] Client: Connected
[08-14 09:32:05] [debug] Remote ident: 'SSH-2.0-OpenSSH_7.4'
[08-14 09:32:05] [debug] Outgoing: Writing KEXINIT
[08-14 09:32:05] [debug] DEBUG: Comparing KEXINITs ...
[08-14 09:32:05] [debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[08-14 09:32:05] [debug] (remote) KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[08-14 09:32:05] [debug] KEX algorithm: ecdh-sha2-nistp256
[08-14 09:32:05] [debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[08-14 09:32:05] [debug] (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[08-14 09:32:05] [debug] Host key format: ssh-rsa
[08-14 09:32:05] [debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[08-14 09:32:05] [debug] (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
[08-14 09:32:05] [debug] Client->Server Cipher: aes128-ctr
[08-14 09:32:05] [debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[08-14 09:32:05] [debug] (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
[08-14 09:32:05] [debug] Server->Client Cipher: aes128-ctr
[08-14 09:32:05] [debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-14 09:32:05] [debug] (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-14 09:32:05] [debug] Client->Server HMAC algorithm: hmac-sha2-256
[08-14 09:32:05] [debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-14 09:32:05] [debug] (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-14 09:32:05] [debug] Server->Client HMAC algorithm: hmac-sha2-256
[08-14 09:32:05] [debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[08-14 09:32:05] [debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[08-14 09:32:05] [debug] Client->Server compression algorithm: none
[08-14 09:32:05] [debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[08-14 09:32:05] [debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[08-14 09:32:05] [debug] Server->Client compression algorithm: none
[08-14 09:32:05] [debug] Outgoing: Writing KEXECDH_INIT
[08-14 09:32:05] [debug] DEBUG: Checking host key format
[08-14 09:32:05] [debug] DEBUG: Checking signature format
[08-14 09:32:05] [debug] DEBUG: Verifying host fingerprint
[08-14 09:32:05] [debug] DEBUG: Host accepted by default (no verification)
[08-14 09:32:05] [debug] DEBUG: Verifying signature
[08-14 09:32:05] [debug] Outgoing: Writing NEWKEYS
[08-14 09:32:05] [debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[08-14 09:32:05] [debug] Outgoing: Writing USERAUTH_REQUEST (none)
[08-14 09:32:05] [debug] Client: none auth failed
[08-14 09:32:05] [debug] Outgoing: Writing USERAUTH_REQUEST (publickey -- check)
[08-14 09:32:05] [debug] Outgoing: Writing USERAUTH_REQUEST (publickey)
[08-14 09:32:05] [debug] Outgoing: Writing CHANNEL_OPEN (0, session)
[08-14 09:32:05] [debug] Outgoing: Writing CHANNEL_REQUEST (0, subsystem: sftp)
[08-14 09:32:05] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:05] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:05] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:06] [debug] Outgoing: Writing READDIR
[08-14 09:32:06] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:06] [debug] Outgoing: Writing READDIR
[08-14 09:32:06] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:06] [debug] Outgoing: Writing CLOSE
[08-14 09:32:06] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing LSTAT
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [trace] handle download folder for d:\Workspace\My App Dev
[08-14 09:32:08] [debug] Outgoing: Writing LSTAT
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing READDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing READDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing CLOSE
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing OPENDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing READDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing READDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing READDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing READDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:08] [debug] Outgoing: Writing READDIR
[08-14 09:32:08] [debug] Outgoing: Writing CHANNEL_DATA (0)

[ ..................]

[08-14 09:32:10] [debug] Outgoing: Writing READDIR
[08-14 09:32:10] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:10] [error] Error: Failure
	at SFTPStream._transform (C:\Users\My-PC\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:190:10)
	at SFTPStream._read (C:\Users\My-PC\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SFTPStream.Writable.write (_stream_writable.js:294:11)
	at Channel.ondata (_stream_readable.js:666:20)
	at Channel.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Channel.Readable.push (_stream_readable.js:219:10)
	at SSH2Stream.<anonymous> (C:\Users\My-PC\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2\lib\Channel.js:167:15)
	at SSH2Stream.emit (events.js:182:13)
	at parsePacket (C:\Users\My-PC\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\ssh.js:3295:10)
	at SSH2Stream._transform (C:\Users\My-PC\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\ssh.js:693:13)
	at SSH2Stream.Transform._read (_stream_transform.js:190:10)
	at SSH2Stream._read (C:\Users\My-PC\.vscode\extensions\liximomo.sftp-1.12.8\node_modules\ssh2-streams\lib\ssh.js:252:15)
	at SSH2Stream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SSH2Stream.Writable.write (_stream_writable.js:294:11)
	at Socket.ondata (_stream_readable.js:666:20)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) 
[08-14 09:32:10] [debug] Outgoing: Writing READDIR
[08-14 09:32:10] [debug] Outgoing: Writing CHANNEL_DATA (0)
[08-14 09:32:10] [debug] Outgoing: Writing READDIR
[08-14 09:32:10] [debug] Outgoing: Writing CHANNEL_DATA (0)

[ ..................]

**Comment by ekifox** [comment]
I have the same error.

**Comment by lordspace** [comment]
This happened to me too. Installed the extension. Set up ssh with key file and it doesn't connect ?!?

**Comment by hassandraga** [comment]
This issue is full of details and logs by @ykeita, then closed for "needs-more-info". Okay.
However, it's happen also to me, but it's just a warning, SFTP still working fine.
