### ISSUE TITLE
HOST specified but : prop "host" fails because ["host" is required]

### ISSUE THREAD

**Issue by TonyGravagno** [liximomo/vscode-sftp#638]
**Do you read the FAQ?**
- [X] Yes.

**Describe the bug**
Error in log on every VSCode startup. This is obviously an exception being thrown which results in the value of 'host' not being set, and an error being displayed as well as the return stack.

```
[2019-09-01 11:54:16.108] [renderer1] [error] Config validation fail: prop "host" fails because ["host" is required]. Maybe you should set a profile first.: Error: Config validation fail: prop "host" fails because ["host" is required]. Maybe you should set a profile first.
	at module.exports.t.default.getConfig (C:\Users\tony\.vscode\extensions\liximomo.sftp-1.12.8\dist\extension.js:70:64465)
	at C:\Users\tony\.vscode\extensions\liximomo.sftp-1.12.8\dist\extension.js:78:79302
	at Generator.next (<anonymous>)
	at module.exports.r (C:\Users\tony\.vscode\extensions\liximomo.sftp-1.12.8\dist\extension.js:78:78303)
	at new Promise (<anonymous>)
	at module.exports.r (C:\Users\tony\.vscode\extensions\liximomo.sftp-1.12.8\dist\extension.js:78:78080)
	at C:\Users\tony\.vscode\extensions\liximomo.sftp-1.12.8\dist\extension.js:78:79218
	at module.exports.t.default.init.c.onDidOpenTextDocument.e (C:\Users\tony\.vscode\extensions\liximomo.sftp-1.12.8\dist\extension.js:78:79635)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at define.constructor._documentsAndEditors.onDidAddDocuments.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:539:115)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at u.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:543:316)
	at d._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:668:1006)
	at d._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:668:698)
	at d._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:667:346)
	at d._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:666:141)
	at define.constructor._protocol.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:664:400)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:179:815)
	at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:179:861)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at n.constructor.e.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:775:104)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:179:815)
	at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:179:861)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at y._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:834)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:116)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at f.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:588)
	at define.constructor._register._socket.onData.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:919)
	at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:190:329)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Desktop (please complete the following information):**
 - OS: Win 8.1
 - VSCode Version 1.37.1
 - Extension Version 1.12.8

**Extension Logs from Startup** - *required*
 [info] config at c:\Development\VSCode\Remote\DEVSIG {"remotePath":"/site","uploadOnSave":false,"downloadOnOpen":false,"ignore":[".vscode",".git",".DS_Store"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":true,"secure":false,"remoteTimeOffsetInHours":0,"name":"devsig","host":"hidden.host","username":"\*\*\*\*\*","password":"\*\*\*\*\*"}

Regarding:
> Config validation fail: prop "host" fails because ["host" is required]. Maybe you should set a profile first.: Error: Config validation fail: prop "host" fails because ["host" is required]. Maybe you should set a profile first.

My config does have a **host** value, see above (hidden.host). I originally had two hosts defined in profiles, with a defaultProfile set, same error. I've tried unsuccessfully to change the order of the properties and make other changes to fool the code to avoid [this error](https://github.com/liximomo/vscode-sftp/blob/master/src/core/fileService.ts#L464).

**Comment by liximomo** [comment]
> Maybe you should set a profile first.

**Comment by TonyGravagno** [comment]
The exception gets logged on VSCode startup .... before a user has a chance to set the profile. The default profile setting doesn't seem to be processed. Perhaps that is the real problem.

**Comment by liximomo** [comment]
Could you list the steps to reproduce?
