### ISSUE TITLE
sftp failing with IdentityFile set in config with encrypted keys

### ISSUE THREAD

**Issue by kolorafa** [liximomo/vscode-sftp#639]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
When having "IdentifyFile" setup for specific host in ~/.ssh/config connection is failing with "Error: Cannot parse privateKey: Encrypted OpenSSH private key detected, but no passphrase given"

**To Reproduce**

1. Set `sftp.json`:
```
{
    "name": "serverx",
    "host": "serverx",
    "protocol": "sftp",
    "remotePath": "/path",
    "agent": "$SSH_AUTH_SOCK",
    "uploadOnSave": true
}
```

2. Set `.ssh/config`:
```
Host serverx
    HostName 1.2.3.4
    Port 22
    User root
    IdentityFile ~/.ssh/id_rsa
```
3. have id_rsa password encrypted

4. See error:
Encrypted OpenSSH private key detected, but no passphrase

5. Comment out "IdentifyFile" from .ssh/config - works

**Expected behavior**
Work :)

"id_rsa" was used for test, the use-case is that this server uses different key name - that is not loaded into agent by default, but is loaded only for the coding time

But when you add IdentifyFile it breaks vscode, if you remove it it then "ssh" will not ask for password in case it's not already loaded into ssh-agent.

Ignoring the IdentifyFile would not be desired because it would break: https://github.com/liximomo/vscode-sftp/issues/557

**Desktop (please complete the following information):**
 - OS: [Linux]
 - VSCode Version [e.g. 1.37.1]
 - Extension Version [e.g. 1.12.3]

**Extension Logs from Startup** - *required*
```
[09-02 18:09:32] [info] config at /... {"remotePath":"/path","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"serverx","host":"serverx","agent":"$SSH_AUTH_SOCK"}
[09-02 18:09:33] [trace] run command 'Upload File'
[09-02 18:09:33] [trace] handle upload file for /.../test.php
[09-02 18:09:33] [error] Error: Cannot parse privateKey: Encrypted OpenSSH private key detected, but no passphrase given
	at Client.connect (/home/kolorafa/.vscode-oss/extensions/liximomo.sftp-1.12.8/node_modules/ssh2/lib/client.js:241:13)
	at module.exports._connectSSHClient.Promise (/home/kolorafa/.vscode-oss/extensions/liximomo.sftp-1.12.8/dist/extension.js:70:107292)
	at new Promise (<anonymous>)
	at p.<anonymous> (/home/kolorafa/.vscode-oss/extensions/liximomo.sftp-1.12.8/dist/extension.js:70:106933)
	at Generator.next (<anonymous>)
	at module.exports.r (/home/kolorafa/.vscode-oss/extensions/liximomo.sftp-1.12.8/dist/extension.js:70:103875)
	at new Promise (<anonymous>)
	at module.exports.r (/home/kolorafa/.vscode-oss/extensions/liximomo.sftp-1.12.8/dist/extension.js:70:103652)
	at p._connectSSHClient (/home/kolorafa/.vscode-oss/extensions/liximomo.sftp-1.12.8/dist/extension.js:70:106624)
	at p.<anonymous> (/home/kolorafa/.vscode-oss/extensions/liximomo.sftp-1.12.8/dist/extension.js:70:105406)
	at Generator.next (<anonymous>)
	at s (/home/kolorafa/.vscode-oss/extensions/liximomo.sftp-1.12.8/dist/extension.js:70:103708) 
```

**Comment by alex1704** [comment]
Same issue for me. Thank you for posting this, i was scratching my head why agent does not work enough time to get irritated)

**Comment by liximomo** [comment]
A better way is to use profiles to toggle `agent` option.

**Comment by dboune** [comment]
@liximomo From what I can tell, quickly looking, it appears you added a warning, but the behavior has not changed. If I'm wrong please reboot me.

My use case as follows: I have "too many" SSH keys, and some servers will end up giving me a "Too many authentications" message, as SSH attempts to try each key.

On the command line I get around this by using `.ssh/config`, specifying an `IdentityFile`.

I had hoped this would work for `vscode-sftp`, but alas, now I'm forced to add `{passphrase: true}` enter my key passphrase instead of being able to take advantage of the SSH Agent.

Command line SSH does not have this restriction, so it can be told to use a specific key AND still use the SSH Agent.

I wish vscode-sftp could do the same.
