### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by damienrj** [liximomo/vscode-sftp#640]
**Do you read the FAQ?**
- [X ] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Using the following config I am not able to connect to the host.  `SFTP: Open SSH in Terminal` works fine however.
I also tried specifying the private key, but also didn't connect. 

```json
{
    "name" : "notebook",
    "host": "bastion",
    "protocol": "sftp",
    "port": 22,
    "username": "damien",
    "remotePath": "/home/sync",
    "uploadOnSave": true,
    "agent": "$SSH_AUTH_SOCK"
}
```

```
Host bastion
  HostName xx.xxx.xxx.xxx
  ControlPath ~/.ssh/sockets/master-%r@%h:%p
  ControlMaster auto
  ControlPersist 2h
  ForwardAgent yes
```

**Expected behavior**
I expected to be able to connect to remote server.

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCode Version 1.37.1
 - Extension Version 1.12.8

**Extension Logs from Startup** - *required*
```
[09-03 13:55:23] [trace] run command 'Upload File'
[09-03 13:55:23] [trace] handle upload file for setup.py
[09-03 13:55:23] [debug] Local ident: 'SSH-2.0-ssh2js0.4.2'
[09-03 13:55:23] [debug] Client: Trying 35.238.62.164 on port 22 ...
[09-03 13:55:23] [debug] Client: Connected
[09-03 13:55:23] [debug] Remote ident: 'SSH-2.0-OpenSSH_7.4'
[09-03 13:55:23] [debug] Outgoing: Writing KEXINIT
[09-03 13:55:23] [debug] DEBUG: Comparing KEXINITs ...
[09-03 13:55:23] [debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[09-03 13:55:23] [debug] (remote) KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[09-03 13:55:23] [debug] KEX algorithm: ecdh-sha2-nistp256
[09-03 13:55:23] [debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[09-03 13:55:23] [debug] (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[09-03 13:55:23] [debug] Host key format: ssh-rsa
[09-03 13:55:23] [debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[09-03 13:55:23] [debug] (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
[09-03 13:55:23] [debug] Client->Server Cipher: aes128-ctr
[09-03 13:55:23] [debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[09-03 13:55:23] [debug] (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
[09-03 13:55:23] [debug] Server->Client Cipher: aes128-ctr
[09-03 13:55:23] [debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[09-03 13:55:23] [debug] (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[09-03 13:55:23] [debug] Client->Server HMAC algorithm: hmac-sha2-256
[09-03 13:55:23] [debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[09-03 13:55:23] [debug] (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[09-03 13:55:23] [debug] Server->Client HMAC algorithm: hmac-sha2-256
[09-03 13:55:23] [debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[09-03 13:55:23] [debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[09-03 13:55:23] [debug] Client->Server compression algorithm: none
[09-03 13:55:23] [debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[09-03 13:55:23] [debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[09-03 13:55:23] [debug] Server->Client compression algorithm: none
[09-03 13:55:23] [debug] Outgoing: Writing KEXECDH_INIT
[09-03 13:55:23] [debug] DEBUG: Checking host key format
[09-03 13:55:23] [debug] DEBUG: Checking signature format
[09-03 13:55:23] [debug] DEBUG: Verifying host fingerprint
[09-03 13:55:23] [debug] DEBUG: Host accepted by default (no verification)
[09-03 13:55:23] [debug] DEBUG: Verifying signature
[09-03 13:55:23] [debug] Outgoing: Writing NEWKEYS
[09-03 13:55:23] [debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[09-03 13:55:23] [debug] Outgoing: Writing USERAUTH_REQUEST (none)
[09-03 13:55:23] [debug] Client: none auth failed
[09-03 13:55:23] [debug] Outgoing: Writing USERAUTH_REQUEST (publickey -- check)
[09-03 13:55:23] [debug] Outgoing: Writing USERAUTH_REQUEST (publickey)
[09-03 13:55:23] [debug] Client: Agent key #1 failed
[09-03 13:55:23] [debug] Agent: Trying key #2
[09-03 13:55:23] [debug] Outgoing: Writing USERAUTH_REQUEST (publickey -- check)
[09-03 13:55:23] [debug] Client: Agent key #2 failed
[09-03 13:55:23] [debug] Agent: No more keys left to try
[09-03 13:55:23] [debug] Client: agent auth failed
[09-03 13:55:23] [debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[09-03 13:55:23] [debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[09-03 13:55:23] [debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[09-03 13:55:23] [debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[09-03 13:55:23] [error] Error: [35.238.62.164]: All configured authentication methods failed
	at Client.module.exports._connectSSHClient.e.on.on.e (/Users/damien/.vscode/extensions/liximomo.sftp-1.12.8/dist/extension.js:70:107250)
	at Client.emit (events.js:187:15)
	at doNextAuth (/Users/damien/.vscode/extensions/liximomo.sftp-1.12.8/node_modules/ssh2/lib/client.js:413:12)
	at tryNextAuth (/Users/damien/.vscode/extensions/liximomo.sftp-1.12.8/node_modules/ssh2/lib/client.js:482:5)
	at tryNextAgentKey (/Users/damien/.vscode/extensions/liximomo.sftp-1.12.8/node_modules/ssh2/lib/client.js:492:9)
	at SSH2Stream.onUSERAUTH_FAILURE (/Users/damien/.vscode/extensions/liximomo.sftp-1.12.8/node_modules/ssh2/lib/client.js:585:14)
	at SSH2Stream.emit (events.js:182:13)
	at parsePacket (/Users/damien/.vscode/extensions/liximomo.sftp-1.12.8/node_modules/ssh2-streams/lib/ssh.js:3775:10)
	at SSH2Stream._transform (/Users/damien/.vscode/extensions/liximomo.sftp-1.12.8/node_modules/ssh2-streams/lib/ssh.js:693:13)
	at SSH2Stream.Transform._read (_stream_transform.js:190:10)
	at SSH2Stream._read (/Users/damien/.vscode/extensions/liximomo.sftp-1.12.8/node_modules/ssh2-streams/lib/ssh.js:252:15)
	at SSH2Stream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SSH2Stream.Writable.write (_stream_writable.js:294:11)
	at Socket.ondata (_stream_readable.js:666:20)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) 
```

**Comment by damienrj** [comment]
For some reason adding `"interactiveAuth": true,` made it work. Not sure how I would know from the error log.

**Comment by hardianlawi** [comment]
I am facing the same problem and adding that did not make it work.

**Comment by shouguicai** [comment]
> I am facing the same problem and adding that did not make it work.
same to me, do u find the solution?
