### ISSUE TITLE
Upload on main folder not possible / sub folder working fine

### ISSUE THREAD

**Issue by spxw** [liximomo/vscode-sftp#652]
My project has the following structure:

> main folder
-- index.php
>> css folder
-- style.css

When changing and saving style.css the upload is working fine (1). Where else changing and saving index.php leads to an error (2) which I do not unterstand. Here are the logs for both cases:

(1)
[09-19 23:24:25] [debug] > PASV
[09-19 23:24:25] [debug] < '227 Entering Passive Mode (192,162,84,123,175,238).\r\n'
[09-19 23:24:25] [debug] > STOR css/style2.css
[09-19 23:24:25] [debug] < '150 Opening BINARY mode data connection for css/style2.css\r\n'
[09-19 23:24:25] [debug] < '226 Transfer complete\r\n'
[09-19 23:24:25] [debug] set remote time(local) 1568928265000
[09-19 23:24:25] [debug] > MFMT 20190919212425 css/style.css
[09-19 23:24:25] [debug] < '213 Modify=20190919212425; css/style.css\r\n'
[09-19 23:24:25] [info] local ➞ remote c:\DEV\xxx\css\style.css

(2)
[09-19 23:25:24] [debug] > MKD .
[09-19 23:25:24] [debug] < '550 .: File already exists\r\n'
[09-19 23:25:24] [error] Error: .: File already exists
	at v (c:\Users\xxx\.vscode\extensions\liximomo.sftp-1.12.8-debug\dist\extension.js:70:110899)
	at d.<anonymous> (c:\Users\xxx\.vscode\extensions\liximomo.sftp-1.12.8-debug\dist\extension.js:70:111622)
	at d.emit (events.js:182:13)
	at d.module.exports.d._write (c:\Users\xxx\.vscode\extensions\liximomo.sftp-1.12.8-debug\dist\extension.js:70:124444)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at d.Writable.write (_stream_writable.js:294:11)
	at Socket.p (c:\Users\xxx\.vscode\extensions\liximomo.sftp-1.12.8-debug\dist\extension.js:70:113993)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) download c:\DEV\xxx\test.php

For debug logging I used https://github.com/liximomo/vscode-sftp/tree/debug-pacakge

May be the error is in fornt of the screen. I don't get it. Thanks!

**Comment by liximomo** [comment]
I need the full logs.

**Comment by spxw** [comment]
[09-20 08:19:20] [info] [file-save] c:\DEV\uploadtest\css\style.css
[09-20 08:19:20] [trace] handle upload file for c:\DEV\uploadtest\css\style.css
[09-20 08:19:20] [debug] > PASV
[09-20 08:19:20] [debug] < '227 Entering Passive Mode (192,162,84,123,175,220).\r\n'
[09-20 08:19:20] [debug] > LIST .
[09-20 08:19:20] [debug] < '150 Opening BINARY mode data connection for file list\r\n'
[09-20 08:19:20] [debug] < '226 Transfer complete\r\n'
[09-20 08:19:20] [debug] > PASV
[09-20 08:19:20] [debug] < '227 Entering Passive Mode (192,162,84,123,176,191).\r\n'
[09-20 08:19:20] [debug] > STOR css/style.css
[09-20 08:19:20] [debug] < '150 Opening BINARY mode data connection for css/style.css\r\n'
[09-20 08:19:20] [debug] < '226 Transfer complete\r\n'
[09-20 08:19:20] [debug] > MFMT 20190920061920 css/style.css
[09-20 08:19:20] [debug] < '213 Modify=20190920061920; css/style.css\r\n'
[09-20 08:19:20] [info] local ➞ remote c:\DEV\uploadtest\css\style.css


[09-20 08:19:33] [info] [file-save] c:\DEV\uploadtest\index.php
[09-20 08:19:33] [trace] handle upload file for c:\DEV\uploadtest\index.php
[09-20 08:19:33] [debug] > PASV
[09-20 08:19:33] [debug] < '227 Entering Passive Mode (192,162,84,123,176,146).\r\n'
[09-20 08:19:33] [debug] > LIST .
[09-20 08:19:33] [debug] < '150 Opening BINARY mode data connection for file list\r\n'
[09-20 08:19:33] [debug] < '226 Transfer complete\r\n'
[09-20 08:19:33] [debug] > MKD .
[09-20 08:19:33] [debug] < '550 .: The file already exists\r\n'
[09-20 08:19:33] [error] Error: .: The file already exists
	at v (c:\Users\xxx\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:110952)
	at d.<anonymous> (c:\Users\xxx\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:111675)
	at d.emit (events.js:182:13)
	at d.module.exports.d._write (c:\Users\xxx\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:124497)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at d.Writable.write (_stream_writable.js:294:11)
	at Socket.p (c:\Users\xxx\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:114046)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) download c:\DEV\uploadtest\index.php

**Comment by liximomo** [comment]
I mean all logs from the startup.

**Comment by spxw** [comment]
Final response: Seemed to have been a wrong configuration on my side. It's working now. Sorry for the circumstances :(
