### ISSUE TITLE
Error: path contains invalid WIN32 path characters

### ISSUE THREAD

**Issue by frammkor** [liximomo/vscode-sftp#682]
**Do you read the FAQ?**
- [ ] Yes.
- [ *] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Early this day I started to use this extension the VS code over my PC running Linux. Latter I tried to work on the same project over my other pc, that runs Windows. After installing the extension, when defining the folder to use I created a folder called "use SFTP" but at some point I got an error, believing that the " "(SPACE) what causing the issue I changed it to "useSFTP" but I keep getting an error.  

Looking to the first line in the console it appears that the destination folder did not update. And i can't find a way to change it manually. But I might be wrong by assuming this. I appreciate any help. Thanks in advance.
**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux]
 - VSCode Version 1.39.2
 - Extension Version 1.12.9

**Extension Logs from Startup**

[11-01 00:36:48] [error] Error: c:\Users\FrancoUser\Desktop\useSFTP\c:\Users\FrancoUser\Desktop\For SFTP\css contains invalid WIN32 path characters.
	at Object.e (c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:80815)
	at Promise (c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:1:23644)
	at new Promise (<anonymous>)
	at Object.e (c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:1:23542)
	at t.default.ensureDir (c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:74956)
	at c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:60185
	at Generator.next (<anonymous>)
	at c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:59793
	at new Promise (<anonymous>)
	at r (c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:59570)
	at u (c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:60040)
	at c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:61041
	at Generator.next (<anonymous>)
	at c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:59793
	at new Promise (<anonymous>)
	at r (c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:59570)
	at f (c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:60966)
	at Promise.all.a.map.n (c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:60249)
	at Array.map (<anonymous>)
	at c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:60242
	at Generator.next (<anonymous>)
	at s (c:\Users\FrancoUser\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:59626)

**Comment by MajesticFalcon** [comment]
I am having the same issue

**Comment by liximomo** [comment]
Please post your config here.

**Comment by Pasgru** [comment]
I hope this thread will be seen, I have the same issue. It only happens when I right-click in the root folder and click "download folder". Then I get the same error message as stated above. I believe the error is in the first line where 2 paths get concatenated.

[04-02 21:57:20] [error] Error: c:\Users\Pascal\Desktop\Test\c:\Users\Pascal\Desktop\Test\logs contains invalid WIN32 path characters.
	at Object.e (c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:80815)
	at c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:1:23551
	at new Promise (<anonymous>)
	at Object.e (c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:1:23449)
	at t.default.ensureDir (c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:74956)
	at c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:60185
	at Generator.next (<anonymous>)
	at c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:59793
	at new Promise (<anonymous>)
	at r (c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:59570)
	at u (c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:60040)
	at c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:61041
	at Generator.next (<anonymous>)
	at c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:59793
	at new Promise (<anonymous>)
	at r (c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:59570)
	at f (c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:60966)
	at c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:60249
	at Array.map (<anonymous>)
	at c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:60242
	at Generator.next (<anonymous>)
	at s (c:\Users\Pascal\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:59626)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)

my config file is very simple with nothing special added. 

"name": "name",
"host": "link.io",
"protocol": "sftp",
"port": 22,
"username": "pasgru",
"remotePath": "/",
"uploadOnSave": false

The error also occurs when I try to set the connection to be "Both directions". If you need anything further just let me know.

- Windows 10
- SFTP 1.12.9
- VSCode 1.55.0

**Comment by Fuglen** [comment]
I had the same issue and error shown below. I fixed it by deleting the "?" hidden folder on the remote.

[06-21 09:22:27] [error] Error: e:\The Flying Birds\TFB-Dev\TFB-Lobby\? contains invalid WIN32 path characters.
	at Object.e (c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:70:81635)
	at c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:1:23488
	at new Promise (<anonymous>)
	at Object.e (c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:1:23388)
	at s.ensureDir (c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:70:75778)
	at c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:60237
	at Generator.next (<anonymous>)
	at c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:59843
	at new Promise (<anonymous>)
	at r (c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:59617)
	at u (c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:60091)
	at c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:63694
	at Array.map (<anonymous>)
	at c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:63681
	at c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:63877
	at Generator.next (<anonymous>)
	at s (c:\Users\simon\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:59674)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
