### ISSUE TITLE
[error]: context: undefined reason: Error: (undefined) Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by qcbf** [liximomo/vscode-sftp#69]
## Expected Behavior
[Description of the expected behavior]

## Actual Behavior
[Description of the actual behavior]

## Steps to Reproduce the Problem

  1.
  1.
  1.

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 [error]: context: undefined reason: Error: (undefined) Cannot read property 'replace' of undefined
	at runTask (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-0.9.3\out\src\helper\createCommand.js:13:19)
	at Array.forEach (native)
	at runTasks (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-0.9.3\out\src\helper\createCommand.js:16:52)
	at getTarget.then.target (C:\Users\Administrator\.vscode\extensions\liximomo.sftp-0.9.3\out\src\helper\createCommand.js:22:9)
	at <anonymous>

## Specifications

  - Version:
  - Platform:

**Comment by Phontana** [comment]
Same here. This wasn't happening with the 0.8.11 version of the plugin. I'm on macOS.

**Comment by UnrealKazu** [comment]
A rollback to the 0.8.11 is a temporary workaround for this bug.

The problem occurs (for example) occurs when performing a `SFTP: Upload` command. The following list of endpoints is empty, due to this bug.

**Comment by liximomo** [comment]
Fix in 0.9.4.
