### ISSUE TITLE
Config Not Found

### ISSUE THREAD

**Issue by spillsthrills** [liximomo/vscode-sftp#697]
**Do you read the FAQ?**
- [ X ]  Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
When trying to Diff a remote file I am getting the error "Config Not Found".

**To Reproduce**
1. Go to a file in on your local computer and use the Diff with Remote command.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.1
 - VSCode Version 1.40.2
 - Extension Version 1.12.3

12-02 13:43:30] [trace] run command 'Diff'
[12-02 13:43:30] [error] Error: Config Not Found. (file:///Volumes/myFiles/Main/api/v1/dump.cfm) 
	at Object.u [as handleCtxFromUri] (/Volumes/myfiles/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:41793)
	at Object.<anonymous> (/Volumes/myfiles/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3993)
	at Generator.next (<anonymous>)
	at /Volumes/evo850/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3273
	at new Promise (<anonymous>)
	at r (/Volumes/evo850/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3050)
	at /Volumes/evo850/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3935
	at Array.map (<anonymous>)
	at Object.<anonymous> (/Volumes/evo850/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3928)
	at Generator.next (<anonymous>)
	at s (/Volumes/evo850/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3106) 
[12-02 13:43:31] [debug] > NOOP
[12-02 13:43:31] [debug] < '200 OK\r\n'

**Comment by jbrink90** [comment]
Hello. Is the local folder you're currently working in on a remote drive, a flash drive, or does it happen to be a folder that is being synced by a backup service, like Nextcloud or Dropbox? That was my issue in this situation.

**Comment by michaelschutz** [comment]
I'm new to VSCode and sftp, and found this to be an issue too. Same error message when project files are in a Dropbox folder. It worked fine for me when I put my local files (MacOS) in a folder outside of my Dropbox.

@TheConsciousness did you find a solution which would still allow you to sync your local files, though? I work on multiple machines, and would rather do tasks locally like SASS compiling, so it would be really helpful to be able to still sync local files between machines and still use this extension.

Or, is there a fix for this that could become a part of the extension?

**Comment by jbrink90** [comment]
@michaelschutz Unfortunately I did not. I've always trusted Notepad++'s version of SFTP, so I fell back to it.
