### ISSUE TITLE
[error]: context: undefined reason: TypeError: Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by pogus55** [liximomo/vscode-sftp#70]
[error]: context: undefined reason: TypeError: Cannot read property 'localeCompare' of undefined
	at configs.map.sort (C:\Users\INFOREX93\.vscode-insiders\extensions\liximomo.sftp-0.9.3\out\src\commands\sync.js:24:32)
	at Array.sort (native)
	at Promise (C:\Users\INFOREX93\.vscode-insiders\extensions\liximomo.sftp-0.9.3\out\src\commands\sync.js:24:10)
	at Promise (<anonymous>)
	at getAllProjects (C:\Users\INFOREX93\.vscode-insiders\extensions\liximomo.sftp-0.9.3\out\src\commands\sync.js:14:30)
	at getFolderTarget (C:\Users\INFOREX93\.vscode-insiders\extensions\liximomo.sftp-0.9.3\out\src\commands\sync.js:66:12)
	at item (C:\Users\INFOREX93\.vscode-insiders\extensions\liximomo.sftp-0.9.3\out\src\helper\createCommand.js:17:20)
	at args (C:\Users\INFOREX93\.vscode-insiders\extensions\liximomo.sftp-0.9.3\out\src\helper\checkRequire.js:12:9)
	at e._executeContributedCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:443:983)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:444:382)

**Comment by liximomo** [comment]
Fix in 0.9.4.

**Comment by wudobi** [comment]
good!
