### ISSUE TITLE
Error on upload, uploads anyway. 

### ISSUE THREAD

**Issue by phimuskapsi** [liximomo/vscode-sftp#704]
This was working fine up until last night, now every time I upload I get this result.
The strange thing is that it is actually uploading the file to the server. It just always reports it as an error.

`[12-19 11:43:56] [error] Error: Failure
	at SFTPStream._transform (c:\Users\WorkRemote\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:189:10)
	at SFTPStream._read (c:\Users\WorkRemote\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:177:12)
	at doWrite (_stream_writable.js:417:12)
	at writeOrBuffer (_stream_writable.js:401:5)
	at SFTPStream.Writable.write (_stream_writable.js:301:11)
	at Channel.ondata (_stream_readable.js:713:22)
	at Channel.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Channel.Readable.push (_stream_readable.js:210:10)
	at SSH2Stream.<anonymous> (c:\Users\WorkRemote\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\Channel.js:167:15)
	at SSH2Stream.emit (events.js:200:13)
	at parsePacket (c:\Users\WorkRemote\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:3288:10)
	at SSH2Stream._transform (c:\Users\WorkRemote\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:694:13)
	at SSH2Stream.Transform._read (_stream_transform.js:189:10)
	at SSH2Stream._read (c:\Users\WorkRemote\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:177:12)
	at doWrite (_stream_writable.js:417:12)
	at writeOrBuffer (_stream_writable.js:401:5)
	at SSH2Stream.Writable.write (_stream_writable.js:301:11)
	at Socket.ondata (_stream_readable.js:713:22)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17) when local ➞ remote`

**Comment by phimuskapsi** [comment]
Figured this out! Server actually ran out of space. Closing.
