### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Alexzanderk** [liximomo/vscode-sftp#717]
**Do you read the FAQ?**
- [x] Yes.

**Describe the bug**
When I sync local > remote I get error `Permission denied`

**To Reproduce**
1. Edit local file
2. Run command sync local to remote 
3. See error
```
[error] Error: Permission denied
	at SFTPStream._transform (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:190:10)
	at SFTPStream._read (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SFTPStream.Writable.write (_stream_writable.js:294:11)
	at Channel.ondata (_stream_readable.js:666:20)
	at Channel.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Channel.Readable.push (_stream_readable.js:219:10)
	at SSH2Stream.<anonymous> (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2/lib/Channel.js:167:15)
	at SSH2Stream.emit (events.js:182:13)
	at parsePacket (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:3288:10)
	at SSH2Stream._transform (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:694:13)
	at SSH2Stream.Transform._read (_stream_transform.js:190:10)
	at SSH2Stream._read (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SSH2Stream.Writable.write (_stream_writable.js:294:11)
	at Socket.ondata (_stream_readable.js:666:20)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) 
```

**Desktop (please complete the following information):**
 - OS: [Mac]
 - VSCode Version [e.g. 1.39.0]
 - Extension Version [e.g. 1.12.9]

**Extension Logs from Startup** - *required*
```
[01-28 10:11:00] [info] config at /Users/admin/Documents/work/projects/****{"remotePath":"/nodejs","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"Dev server","host":"*****","port":"*****","username":"******","privateKeyPath":"/Users/admin/.ssh/id_rsa"}
```

```
[01-28 10:13:29] [trace] run command 'Sync Local To Remote'
[01-28 10:13:30] [trace] handle sync local ➞ remote for /Users/admin/Documents/work/projects/****
[01-28 10:13:30] [debug] Outgoing: Writing MKDIR
[01-28 10:13:30] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing LSTAT
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing OPENDIR
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing READDIR
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing READDIR
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing CLOSE
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing MKDIR
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing MKDIR
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing MKDIR
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing MKDIR
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing LSTAT
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing LSTAT
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing LSTAT
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing LSTAT
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [debug] Outgoing: Writing OPENDIR
[01-28 10:13:31] [debug] Outgoing: Writing CHANNEL_DATA (0)
[01-28 10:13:31] [error] Error: Permission denied
	at SFTPStream._transform (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:190:10)
	at SFTPStream._read (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SFTPStream.Writable.write (_stream_writable.js:294:11)
	at Channel.ondata (_stream_readable.js:666:20)
	at Channel.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Channel.Readable.push (_stream_readable.js:219:10)
	at SSH2Stream.<anonymous> (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2/lib/Channel.js:167:15)
	at SSH2Stream.emit (events.js:182:13)
	at parsePacket (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:3288:10)
	at SSH2Stream._transform (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:694:13)
	at SSH2Stream.Transform._read (_stream_transform.js:190:10)
	at SSH2Stream._read (/Users/admin/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SSH2Stream.Writable.write (_stream_writable.js:294:11)
	at Socket.ondata (_stream_readable.js:666:20)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) 
[01-28 10:13:31] [debug] Outgoing: Writing READDIR
```

**Comment by Alexzanderk** [comment]
Problem is if your remote path choice global folder and it is not your group and user - permission will be denied
When I chose my folder in a remote path - everything is fine
But as for me, it is strange because I got allows for the changed file and why permission denied (( I can't understand

```
remote path - root where is my proj
├── ssl
├── proj1-backend
└── proj2_server(my folder with the app)
```
