### ISSUE TITLE
Can't use the keybinding for sftp.upload.file or sftp.upload.file, error outputted.

### ISSUE THREAD

**Issue by yCodeTech** [liximomo/vscode-sftp#734]
For some reason I can't bind keyboard shortcuts to either `sftp.upload.file` or `sftp.upload.file` commands. I'm trying to utilise the keyboard shortcuts so I can upload one or multiple selected files at once (and not being active in the editor).

    {
        "key": "ctrl+u",
        "command": "sftp.upload"
    }

With a file selected in the explorer, this command logs this:

 `[03-03 00:48:08] [warn] The "Upload" command get canceled because of missing targets.`

<hr>

    {
        "key": "ctrl+u",
        "command": "sftp.upload.file"
    }

With a file selected in the explorer, this command spits out the _**Cannot read property 'resource' of undefined**_ error. The error log:

    [03-03 00:47:32] [error] TypeError: Cannot read property 'resource' of undefined
	at Object.t.uriFromExplorerContextOrEditorContext [as getFileTarget] (c:\Users\Stuart\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:1:6062)
	at Object.<anonymous> (c:\Users\Stuart\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:1:3771)
	at Generator.next (<anonymous>)
	at c:\Users\Stuart\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:1:3273
	at new Promise (<anonymous>)
	at r (c:\Users\Stuart\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:1:3050)
	at Object.doCommandRun (c:\Users\Stuart\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:1:3722)
	at Object.<anonymous> (c:\Users\Stuart\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:67363)
	at Generator.next (<anonymous>)
	at c:\Users\Stuart\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:66955
	at new Promise (<anonymous>)
	at r (c:\Users\Stuart\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:66732)
	at Object.run (c:\Users\Stuart\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:78:67269)
	at v._executeContributedCommand (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:543:163)
	at v.$executeContributedCommand (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:543:538)
	at p._doInvokeHandler (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:676:202)
	at p._invokeHandler (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:675:901)
	at p._receiveRequest (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:545)
	at p._receiveOneMessage (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:673:373)
	at d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:671:588
	at l.fire (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:541)
	at _.fire (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:190:934)
	at d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:838:649
	at l.fire (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:541)
	at _.fire (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:190:934)
	at t.PersistentProtocol._receiveMessage (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:195:277)
	at d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:192:459
	at l.fire (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:541)
	at p.acceptChunk (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:445)
	at d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:796
	at Socket.t (d:\Users\Stuart\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:196:732)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

**Comment by mims1979** [comment]
I can confirm same issue.  It would be really convenient to have a keyboard shortcut to just upload the active file instead of having to use context menu

**Comment by aekaterini** [comment]
I also have the same issue with VSCode on Mac OS 11.2.1.
Any solution to this?

**Comment by ghost** [comment]
I don't know of a quick fix but I will add this to the backlog.

**Comment by chschatz** [comment]
> I don't know of a quick fix but I will add this to the backlog.

Is there any solution yet?

**Comment by gabycasper007** [comment]
still no solution?
