### ISSUE TITLE
SFTP doesn't sync/download remote project

### ISSUE THREAD

**Issue by kolnogorov** [liximomo/vscode-sftp#831]
**Do you read the FAQ?**
- [X] Yes.

**Describe the bug**
SFTP doesn't Sync Remote > Local and can't download anything but folders structure, with the following error message:

```
[09-23 10:32:01] [error] Error: Failure
	at SFTPStream._transform (/Users/lovebeam/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:189:10)
	at SFTPStream._read (/Users/lovebeam/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:177:12)
	at doWrite (_stream_writable.js:435:12)
	at writeOrBuffer (_stream_writable.js:419:5)
	at SFTPStream.Writable.write (_stream_writable.js:309:11)
	at Channel.ondata (_stream_readable.js:728:22)
	at Channel.emit (events.js:223:5)
	at Channel.EventEmitter.emit (domain.js:475:20)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Channel.Readable.push (_stream_readable.js:224:10)
	at SSH2Stream.<anonymous> (/Users/lovebeam/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2/lib/Channel.js:167:15)
	at SSH2Stream.emit (events.js:223:5)
	at SSH2Stream.EventEmitter.emit (domain.js:475:20)
	at parsePacket (/Users/lovebeam/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:3288:10)
	at SSH2Stream._transform (/Users/lovebeam/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:694:13)
	at SSH2Stream.Transform._read (_stream_transform.js:189:10)
	at SSH2Stream._read (/Users/lovebeam/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:177:12)
	at doWrite (_stream_writable.js:435:12)
	at writeOrBuffer (_stream_writable.js:419:5)
	at SSH2Stream.Writable.write (_stream_writable.js:309:11)
	at Socket.ondata (_stream_readable.js:728:22)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
```

**To Reproduce**
1. Go to SFTP: Sync Remote > Local or SFTP: Download Project
2. Run it. It connect to remote server and download all folders, but not the files inside.
3. See error.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - VSCode Version 1.49.1
 - Extension Version [e.g. 1.7.0]

**Comment by martin-braun** [comment]
I can confirm, this is not working on macOS 11, too.

**Comment by matt-mainstreetdesign** [comment]
Can confirm the same issue. Windows 10

**Comment by hubertnguyen** [comment]
I haven't seen an option to browse the remote folder and right-click+download (file or directory). Am I missing something?

**Comment by gian-didom** [comment]
I confirm the same issue

**Comment by ghost** [comment]
Yeah I've seen this as well.  I suspect it's a filesystem permissions issue but need to investigate.
