### ISSUE TITLE
[error] Error: file not exist

### ISSUE THREAD

**Issue by RomaneeSean** [liximomo/vscode-sftp#837]
{
    "name": "flash",
    "host": "97.64.31.24",
    "protocol": "ftp",
    "port": 21,
    "username": "admin",
    "password": "123456",
    "remotePath": "/www/wwwroot/www",
    "uploadOnSave": true,
    "connectTimeout": 30000
}

[10-11 18:54:25] [error] Error: file not exist
	at l.<anonymous> (c:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:98188)
	at Generator.next (<anonymous>)
	at s (c:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:96928)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by criticaldany** [comment]
I have the exact same problem, a few days ago it was working fine, today when I created a new config on a new folder to have multiple connections, each with its own context I start to have this problem, even my old folders don't work anymore.

OS: Ubuntu 20.04
VSCode: Latest Version
SFTP: Latest Version

I saw an old post from 2018 where someone also had this issue but I couldn't see what the fix was for it.

**Comment by miyaohua** [comment]
Have you solved the same problem? Can you tell me about the solution
