### ISSUE TITLE
Error bad file descriptor

### ISSUE THREAD

**Issue by Corwin-byte** [liximomo/vscode-sftp#918]
[error] Error: bad file descriptor
	at SFTPStream._transform (c:\Users\corwi\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
	at SFTPStream._read (c:\Users\corwi\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
	at Channel.ondata (internal/streams/readable.js:719:22)
	at Channel.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Channel.Readable.push (internal/streams/readable.js:223:10)
	at SSH2Stream.<anonymous> (c:\Users\corwi\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\Channel.js:167:15)
	at SSH2Stream.emit (events.js:315:20)
	at parsePacket (c:\Users\corwi\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:3288:10)
	at SSH2Stream._transform (c:\Users\corwi\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:694:13)
	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
	at SSH2Stream._read (c:\Users\corwi\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
	at Socket.ondata (internal/streams/readable.js:719:22)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote c:\Users\corwi\Downloads\ferox\index.js
Can you help me

**Comment by Hype3808** [comment]
same issue

**Comment by helomri** [comment]
me too

**Comment by kdssoftware** [comment]
Same here, this occured when I saved a file.

This was my config:
```json
{
	"name": "workspace",
	"host": "***************",
	"port": 21,
	"protocol": "sftp",
	"username": "********",
	"password": "*******",
	"remotePath": "/html/workspace",
	"context":"workspace",
	"uploadOnSave": true
}
```

**Comment by snowfluffi** [comment]
same issue ,-,

**Comment by fridaystreet** [comment]
same here :-(

**Comment by devendrapoonia** [comment]
Same issue
