### ISSUE TITLE
Don't use this anymore! Very broken module!

### ISSUE THREAD

**Issue by Asitis** [liximomo/vscode-sftp#939]
A general public service announcement: With the latest VSCode update this module has bugs that can be very, very bad! I had to upload a folder to several servers. I copied it to each local file structure and used this module to update it. 

It scrambled several files on all servers; some files disappeared, others where stripped down to the first line. I even saw several files merged into one, with errors to booth all over the filesystem. I spent 6 hours to untangle all the files, replacing them from backups and checking everything. Now this happened on live sites with active users. We had hours of downtime due to this module being abandoned.

Edit: Yeah, yeah, I know you shouldn't use this on production environments. Everything uses composer and git, but every now and again it was very easy to quickly pull in a directory straight from VScode.

**Comment by Niccober** [comment]
Thanks for your report. May I ask if there is a known good alternative for this add-on? Can you recommend a specific extension?

**Comment by mashirozx** [comment]
You shouldn't use this on live production server. Yes, this plugin is buggy since it hasn't been maintained for two or three years. But I have to say it's really convenient  for developing. Strongly recommend you using GIT or normal FTP/SFPT tools (ie.   Putty, WinScp, FileZilla) in production server.

**Comment by maartenvandillen** [comment]
Same problem over here. Lots of errors during upload.

[05-19 09:11:43] [error] Error: No such file
	at SFTPStream._transform (/Users/Maarten/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
	at SFTPStream._read (/Users/Maarten/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
	at Channel.ondata (internal/streams/readable.js:719:22)
	at Channel.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Channel.Readable.push (internal/streams/readable.js:223:10)
	at SSH2Stream.<anonymous> (/Users/Maarten/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2/lib/Channel.js:167:15)
	at SSH2Stream.emit (events.js:315:20)
	at parsePacket (/Users/Maarten/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:3288:10)
	at SSH2Stream._transform (/Users/Maarten/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:694:13)
	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
	at SSH2Stream._read (/Users/Maarten/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
	at Socket.ondata (internal/streams/readable.js:719:22)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote

**Comment by Asitis** [comment]
> Thanks for your report. May I ask if there is a known good alternative for this add-on? Can you recommend a specific extension?

https://github.com/liximomo/vscode-sftp/issues/875 < Check this one. The community is wanting to step up to fix this one.

**Comment by maartenvandillen** [comment]
I have temporarily fixed it using these instructions: https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635

**Comment by nickdekruijk** [comment]
Looking at all the forks of this repo this one seems updated most recently: https://github.com/liximomo/vscode-sftp
Anyone tried this yet?

**Comment by nickdekruijk** [comment]
Looking at all the forks of this repo this one seems updated most recently: https://github.com/Natizyskunk/vscode-sftp/
Anyone tried this yet?

**Comment by lucidlips** [comment]
> Looking at all the forks of this repo this one seems updated most recently: https://github.com/Natizyskunk/vscode-sftp/
> Anyone tried this yet?

Not sure why he wouldnt just publish it if it works ¯\_(ツ)_/¯

**Comment by mashirozx** [comment]
This vscode plugins is not recommended anymore, since it's really buggy, there are some suggestions for you:
if you're on Linux or Mac, you may have a try on inotifywait + rsync, ie:
```sh
#!/bin/bash
while inotifywait -r -e modify,create,delete /root/wd/app; do
  rsync -a -P -e "ssh -i ~/.ssh/id_rsa_server" /root/wd/app/ root@hostname:/root/app/
done
```
If you're Windows, I believe there are alternative softwares, ie. WinScp has a dir mirror function.

**Comment by AWqxKAWERbXo** [comment]
Same goes for me. This once was a great plugin. It just worked. Now it just doesn't.

```

[05-24 09:33:00] [error] Error: No such file
	at SFTPStream._transform (c:\Users\alexplus\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
	at SFTPStream._read (c:\Users\alexplus\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
	at Channel.ondata (internal/streams/readable.js:719:22)
	at Channel.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Channel.Readable.push (internal/streams/readable.js:223:10)
	at SSH2Stream.<anonymous> (c:\Users\alexplus\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\Channel.js:167:15)
	at SSH2Stream.emit (events.js:315:20)
	at parsePacket (c:\Users\alexplus\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:3288:10)
	at SSH2Stream._transform (c:\Users\alexplus\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:694:13)
	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
	at SSH2Stream._read (c:\Users\alexplus\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
	at Socket.ondata (internal/streams/readable.js:719:22)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote p:\xampp\htdocs\xxxxxx\assets\.redaxo

```

**Comment by lucidlips** [comment]
The ssh2-streams node_modules hack works fine for now. Until the ssh2-streams dependancy is patched and this extension updated/forked I suggest just following the steps here:

https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635

I am on vscode version 1.56.2 and everything is working fine since following the steps above.

**Comment by davidcsi** [comment]
I'm having the same "[error] Error: No such file"

```
[05-24 18:03:34] [error] Error: No such file
	at SFTPStream._transform (/Users/david/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
	at SFTPStream._read (/Users/david/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
	at Channel.ondata (internal/streams/readable.js:719:22)
	at Channel.emit (events.js:315:20)
	at Channel.EventEmitter.emit (domain.js:467:12)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Channel.Readable.push (internal/streams/readable.js:223:10)
	at SSH2Stream.<anonymous> (/Users/david/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2/lib/Channel.js:167:15)
	at SSH2Stream.emit (events.js:315:20)
	at SSH2Stream.EventEmitter.emit (domain.js:467:12)
	at parsePacket (/Users/david/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:3288:10)
	at SSH2Stream._transform (/Users/david/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:694:13)
	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
	at SSH2Stream._read (/Users/david/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
	at Socket.ondata (internal/streams/readable.js:719:22)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote /Users/david/Documents/hayo-db/send_message.py
```

**Comment by bersi82** [comment]
> Thanks for your report. May I ask if there is a known good alternative for this add-on? Can you recommend a specific extension?

You can use FTP-Sync
https://github.com/lukasz-wronski/vscode-ftp-sync

**Comment by AWqxKAWERbXo** [comment]
I tried to contact the author of this plug-in but did not get any response.

Is it possible to flag the plug-in as broken via the vs-code extension list?

**Comment by Natizyskunk** [comment]
You can try my version, i've fixed a lot of bugs, maybe this will fix yours 🙂
https://github.com/Natizyskunk/vscode-sftp/releases
