### ISSUE TITLE
Error: No such file VS CODE 1.56

### ISSUE THREAD

**Issue by rogerthedeveloper** [liximomo/vscode-sftp#941]
[05-26 19:55:06] [info] remote ➞ local /dashboard.php
[05-26 19:55:11] [info] [file-save] /dashboard.php
[05-26 19:55:12] [error] Error: No such file
	at SFTPStream._transform (/Users/rspro/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:412:27)
	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
	at SFTPStream._read (/Users/rspro/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js:183:15)
	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
	at Channel.ondata (internal/streams/readable.js:719:22)
	at Channel.emit (events.js:315:20)
	at Channel.EventEmitter.emit (domain.js:467:12)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Channel.Readable.push (internal/streams/readable.js:223:10)
	at SSH2Stream.<anonymous> (/Users/rspro/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2/lib/Channel.js:167:15)
	at SSH2Stream.emit (events.js:315:20)
	at SSH2Stream.EventEmitter.emit (domain.js:467:12)
	at parsePacket (/Users/rspro/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:3288:10)
	at SSH2Stream._transform (/Users/rspro/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:694:13)
	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
	at SSH2Stream._read (/Users/rspro/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/ssh.js:253:15)
	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
	at Socket.ondata (internal/streams/readable.js:719:22)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote /dashboard.php

**Comment by Dennislampert** [comment]
I have the same issue over sftp

**Comment by eco747** [comment]
Same issue over sftp
same stack trace

**Comment by Dennislampert** [comment]
found this:
https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635

**Comment by RPINerd** [comment]
Just for anyone not wanting to follow the #919 comment:

Do a search inside ``~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js``
for `options.emitClose = false;`
Add `options.autoDestroy = false;` after both instances.

This solved this incredibly annoying issue for me

**Comment by mgilank** [comment]
Still got error, 
i have put both options emitclose.

any other recommended alternative for this kind of extension?

**Comment by suqingdong** [comment]
`1.5.5` works

**Comment by eco747** [comment]
Some files are corrupted on upload :(

**Comment by rarahim75** [comment]
> Still got error,
> i have put both options emitclose.
> 
> any other recommended alternative for this kind of extension?

Happened to me too but it's resolved once i restarted vscode.

**Comment by ZellerDorjee** [comment]
@RPINerd Thanks

**Comment by bn-solution** [comment]
Change Extension To Version  1.12.8  **Work**

**Comment by brett-shenk** [comment]
@RPINerd Thanks!!

**Comment by caleywoods** [comment]
> Just for anyone not wanting to follow the #919 comment:
> 
> Do a search inside `~/.vscode/extensions/liximomo.sftp-1.12.9/node_modules/ssh2-streams/lib/sftp.js`
> for `options.emitClose = false;`
> Add `options.autoDestroy = false;` after both instances.
> 
> This solved this incredibly annoying issue for me

Fixed for me on Windows 10 with sftp plugin version 1.12.9. The VSCode extensions path on Windows is likely in `%userprofile%\.vscode\extensions\`. From there you should be able to find the path/file mentioned by @RPINerd

**Comment by bitbytebit1** [comment]
https://github.com/liximomo/vscode-sftp/issues/919

**Comment by Natizyskunk** [comment]
You can try my version, i've fixed a lot of bugs, maybe this will fix yours 🙂
https://github.com/Natizyskunk/vscode-sftp/releases

**Comment by t0in** [comment]
Thanks @RPINerd worked fine here (OS X 10.15.7)

**Comment by fbastos** [comment]
thanks @Natizyskunk work fine!!!!

**Comment by atoomic** [comment]
This also fixed the issue for me... very frustrated first user experience...

**Comment by clayms** [comment]
https://github.com/liximomo/vscode-sftp/issues/941#issuecomment-849849554

fixed it.
