### ISSUE TITLE
vscode 升级到1.57.1后，该功能无法上传了

### ISSUE THREAD

**Issue by zhuzongzhen** [liximomo/vscode-sftp#953]
[06-22 20:42:12] [info] [file-save] e:\work\golang\spctl\cmd\example\main.go
[06-22 20:42:12] [error] Error: No such file
    at SFTPStream._transform (c:\Users\pc\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:412:27)
    at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
    at SFTPStream._read (c:\Users\pc\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
    at Channel.ondata (internal/streams/readable.js:719:22)
    at Channel.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Channel.Readable.push (internal/streams/readable.js:223:10)
    at SSH2Stream.<anonymous> (c:\Users\pc\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\Channel.js:167:15)
    at SSH2Stream.emit (events.js:315:20)
    at parsePacket (c:\Users\pc\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:3288:10)
    at SSH2Stream._transform (c:\Users\pc\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:694:13)
    at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
    at SSH2Stream._read (c:\Users\pc\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
    at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote e:\work\golang\spctl\cmd\example\main.go

**Comment by stone-wind** [comment]
https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-838586635
https://github.com/mscdex/ssh2-streams/pull/174/files

**Comment by dmwin72015** [comment]
不好使啊，依然提示no such file

**Comment by f2h2h1** [comment]
可以试试这个 fork ，配置文件基本不用改动就能直接用
https://github.com/Natizyskunk/vscode-sftp
