### ISSUE TITLE
Timeout while connecting to server

### ISSUE THREAD

**Issue by f4r424hm3d** [liximomo/vscode-sftp#976]
This problem occurred only on wifi but its works on the mobile network.

[12-29 12:50:06] [error] Error: Timeout while connecting to server
    at Timeout._onTimeout (c:\Users\faraz\.vscode\extensions\liximomo.sftp-1.12.9\dist\extension.js:70:109790)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by kahve6** [comment]
There are different types of errors about timeout. One of them "Timed out while waiting for handshake", that was probably occured because of protocol configuration. The other is "Timeout while connecting to server". It means some process are done but some are still waiting. That's why you must wait till the end of process to get error. You can solve this issue with **"connectTimeout"** configuration, in example set as 40000 or more - _default is 10000_ -. Then you can define what was the error. Possibly, it depends on bad connection, port configuration or restrictions.

**Comment by GeekMustHave** [comment]
I am also experiencing the same issue.

[01-31 16:08:48] [error] Error: Timeout while connecting to server
    at Timeout._onTimeout (c:\Users\jschust2\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:70:110631)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) 

The same configuration used WinSCP works correctly, upped timeout to 40000 still go the error shown above.

`{
    "name": "GeekMustGave OpenStuff",
    "host": "*****",
    "protocol": "ftp",
    "port": 22,
    "username": "*******",
    "password": "******",
    "remotePath": "/BlogPosts/OttoPlus",
    "uploadOnSave": true,
    "useTempFile": false,
    "passive": true,
    "openSsh": false,
    "timeout": 40000    
}
`

**Comment by Natizyskunk** [comment]
Could you guys try my version and tell me if it fix your problems ? You can find it [here](https://github.com/Natizyskunk/vscode-sftp).
