### ISSUE TITLE
TypeError: Cannot read property 'resource' of undefined

### ISSUE THREAD

**Issue by aleraymann** [liximomo/vscode-sftp#979]
t Object.t.uriFromExplorerContextOrEditorContext [as getFileTarget] (c:\Users\Alessandro Raymann\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:1:6074)
    at Object.<anonymous> (c:\Users\Alessandro Raymann\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:1:3772)
    at Generator.next (<anonymous>)
    at c:\Users\Alessandro Raymann\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:1:3276
    at new Promise (<anonymous>)
    at r (c:\Users\Alessandro Raymann\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:1:3050)
    at Object.doCommandRun (c:\Users\Alessandro Raymann\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:1:3722)
    at Object.<anonymous> (c:\Users\Alessandro Raymann\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:67425)
    at Generator.next (<anonymous>)
    at c:\Users\Alessandro Raymann\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:67015
    at new Promise (<anonymous>)
    at r (c:\Users\Alessandro Raymann\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:66789)
    at Object.run (c:\Users\Alessandro Raymann\.vscode\extensions\liximomo.sftp-1.12.10\dist\extension.js:78:67330)
    at r._executeContributedCommand (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:31080)
    at r.$executeContributedCommand (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:31622)
    at t._doInvokeHandler (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13802)
    at t._invokeHandler (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13486)
    at t._receiveRequest (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:12148)
    at t._receiveOneMessage (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:10826)
    at c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:8922
    at u.fire (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at r.fire (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18942)
    at c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:34341
    at u.fire (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at r.fire (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18942)
    at n._receiveMessage (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:23523)
    at c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:21057
    at u.fire (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at w.acceptChunk (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:15770)
    at c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:14900
    at Socket.T (c:\Users\Alessandro Raymann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:13813)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) 

sftp.json:
{
    "name": "SGC ",
    "protocol": "sftp",
    "remotePath": "", 
    "port": ,
    "host": "",
    "uploadOnSave": false,
    "profiles": {
      "alessandroSGC": {
        "username": "",
        "password": ""
      }
    }
}

how can i fix this?

thanks

**Comment by chschatz** [comment]
Same issue here. I configured a keymap for upload to server. When right-clicking and upload a file, it works. I get exact the same error when trying to upload via keymap. 
Did you fix it?

**Comment by thisnugroho** [comment]
i had same probem too, but it's already solved by [this post](https://github.com/liximomo/vscode-sftp/issues/323#issuecomment-468500983)
